### ISSUE TITLE
Fire Extinguisher Design and Implementation

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#103]
# **Description**
Extends `station`  and adds an interactable fire extinguisher that can extinguish a generated flame if a station is left too long with an item (i.e. Cooking a steak). The `flame` is generated when the station has been left too long.

## SubFeature/component (optional)

- [x] Design Fire Extinguisher, and flame animation
- [x] Fire Extinguisher station
- [x] #222
- [ ] #223
- [ ] Fire makes a sound
- [ ] Extinguishing a fire makes a sound

## **Examples (optional)**
- **fire extinuisher item**: can be picked up by the player and used to extinguish fires

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Design the fire-extinguisher and flame images (Sep. 1)
- [x] Develop flame animation (Sep. 1)
- [x] Develop a station to get and put back the fire extinguisher (Sep. 5)
- [x] Allow for stations to catch flame (Sep. 7)
- [ ] Allow for fire extinguisher to be used to put flame out (Sep 8)
- [ ] Show the fire extinguisher in the inventory (Sep 9)

**Completion Deadline:** Sep. 8

# **Extras (optional)**
- [x] Implement flame animation
- [ ] Implement blow animation

# **Documentation**
[Fire Extinguisher](https://github.com/UQcsse3200/2024-studio-3/wiki/Fire-Extinguisher)

# **Members**
- Caleb Murphy (Caleb-J-Murphy)
