### ISSUE TITLE
Map Improvements

### ISSUE THREAD

**Issue by bhavyamalik1** [UQcsse3200/2024-studio-3#104]
# **Description**
Improving the map design and updating the artwork to make it more visually pleasing. Fixing hit boxes and colliders so that the customer entities can freely move (which is currently broken by the borders). 

# **Dependencies**
N.A

# **Milestones**
- [ ] Fix the hit boxes and border collisions (Sep. 7)
- [ ] Create improved artwork for the map (Sep. 10)
- [ ]  Implement the new map into the game (Sep. 12)

**Completion Deadline:**  Sep. 13

# **Documentation**
- to be implemented

# **Members**
- Bhavya Malik (bhavyamalik1) 
- Caleb Murphy (caleb-j-murphy)
