### ISSUE TITLE
Level System

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#106]
# **Description**

When the day ends (that is, after the player serves all customers, and the player makes the night time moral decision) the player is shown the end of the day screen containing multiple statistics, as well as the option to go to the next day. When they press the next day button, it will go to the next day (or level). Each level gets progressively harder, with "harder" meaning the player will have to do more interactions throughout the course of the day, whether that be having more total customers during the day, or having orders that have more complicated recipes that require more ingredients.

## SubFeature/component
Each new level will be harder than the last one. Levels will be somewhat random, to add variety and some challenge. For example, on level/day one, customers would only have ask for very simple orders, but by say day five, they could request more complicated orders, or more customers would come in and order.

For each new level, resets would be required for somethings, for example ensuring that there are no vestigal orders or that there are no ingredients left out on a bench for example. Somethings would however have to be persistent, such as say a player's moral rating or money.

# **Dependencies**

- [x] Level Service (#107)
- [x] Level Component (#171)
- [x] Customer Extended (#101)
- [x] End of Day Extended (#105)

# **Milestones**

- [x] Implement class for use with ServiceLocator (Sept 4.)
- [x] Implement functionality for spawning a set amount of customers (Sept. 7)
- [ ] Limit customer spawning depending on their characteristics (Sept. 8)
- [x] Repeat above steps for implementing more levels (Sept. 9)
- [x] Write testing code, as well as manually test (Sept. 9)
- [x] Refine implementations if needed (Sept. 9)
- [ ] Documentation (Sept. 10)

**Completion Deadline:** Sept. 11

# **Documentation**
- [Level System Overview](/UQcsse3200/2024-studio-3/wiki/Level-System-Overview)

# **Members**

- Michael Kidd (@IWontCauseAFuss) (idontwanttocauseafuss)
