### ISSUE TITLE
Level service

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#107]
# **Description**
**Task:** [Level Service](#xx).
**Feature:** [Level System](#106 )

This focuses on creating the initial backend for the level system. This mainly comprises of creating a new service for use in the `ServiceLocator` for global access, with the service then handling events (i.e. going to the next level) and calling appropriate listeners (i.e. spawning a roughly consistent number of customers with orders of required complexity)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create new service class
- [x] Update service locator
- [x] Create new class for registering listeners
- [x] Create new listeners
 
**Completion Deadline:** Sept. 7

 
# **Documentation**
-
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Michael (@IWontCauseAFuss) (idontwanttocauseafuss)
