### ISSUE TITLE
Design Fire Extinguisher and Flame Animation

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#108]
# **Description**
**Task:** [Design Fire Extinguisher and Flame Animation](#).
**Feature:** [Fire Extinguisher Design and Implementation](#103)
Creation of 2 sets of assets. The first being a fire extinguisher sprite that will be used as the station. The second being a flame animation that contains a list of sprites to be cycled through in an animation. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Fire Extinguisher asset (Aug. 31)
- [x] Create Flame Animation (Aug. 31)
- [ ] Document the sprites on a wiki (Aug. 31)
 
**Completion Deadline:** Aug. 31

 
# **Documentation**
- [Fire-Extinguisher](https://github.com/UQcsse3200/2024-studio-3/wiki/Fire-Extinguisher)
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

# **Branch**
[team3/fire_extinguisher)](https://github.com/UQcsse3200/2024-studio-3/tree/team3/fire_extinguisher_assets)
Parent Branch: [team3/fire_extinguisher](https://github.com/UQcsse3200/2024-studio-3/tree/team3/fire_extinguisher)
