### ISSUE TITLE
Interaction Sensor and Key Bindings

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#11]
# **Description**
**Task:** Create Interaction key bindings to interact with objects when close by
**Feature:** Player Action and Interaction (#4)

Some key bindings are already set up in the game base, thus this set needs to be expanded to allow for player interaction. This interaction will need to be able to be picked up by event handlers. Documentation on player controls will also be added. When a player is within 1 meter of an interactable area, then the key binding should take place. Otherwise, the key should take no effect.
 
## **Example**
- When a player is able to interact with an object, they will be able to press "E" to interact with it.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add 'E' to the list of commands able to be used by the user (Aug 19)
- [x] Add a hitbox around the player that can sense other objects that are touching it (Aug 20)
- [x] Write up documentation for the player controls on the wiki (Aug. 28)
- [x] Add interaction hitboxes to the stations (Aug 28)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Player Interactions Wiki](../wiki/Player-Interactions)
- [Sensor Component Test Plan](../wiki/Test-Plan-for-Sensor-Component)
- [Interaction Component Test Plan](../wiki/Test-Plan-for-Interaction-Component)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Member**
- Caleb (Caleb-J-Murphy)
- Bhavya (BhavyaMalik1)

**Comment by JTrenerry** [comment]
Task tickets should have the task label
