### ISSUE TITLE
Fire Extinguisher Station

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#110]
# **Description**
**Task:** [Fire Extinguisher Station](#110).
**Feature:** [Fire Extinguisher Design and Implementation](#103)

`Fire Extinguisher Station`, inherits from `Station` and will add an event handler to the player entity so that when holding a fire extinguisher near a station on fire, it will be able to put the fire out through interacting with it while holding it. This can be done unlimited times. When the player is done with the fire extinguisher, they can then put it back by interacting with the `Fire Extinguisher Station` again.

## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.
- **Pick Up and Put Back**: Player can walk up to the station, pick up the fire extinguisher through `interacting` then place it back in the station through `interacting` again.

# **Dependencies**
- [x] [Fire Extinguisher Asset needs to be made](#108)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add the station to the map (Sep. 3)
- [x] Allow for the item to be picked up by the player (Sep. 4)
- [x] Allow for the item to be put back by the player (Sep. 4)
- [x] Unit test developed for getting and putting back fire extinguisher (Sep. 5)
- [ ] Develop wiki for fire extinguisher components
 
**Completion Deadline:** Sep. 5
 
# **Documentation**
[Fire Extinguisher](https://github.com/UQcsse3200/2024-studio-3/wiki/Fire-Extinguisher)
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

# **Branch**
[team3/fire_extinguisher_station](https://github.com/UQcsse3200/2024-studio-3/tree/team3/fire_extinguisher_station)
Parent Branch: [team3/fire_extinguisher](https://github.com/UQcsse3200/2024-studio-3/tree/team3/fire_extinguisher)

# **Pull Requests**
[Pull Request](https://github.com/UQcsse3200/2024-studio-3/pull/111)
