### ISSUE TITLE
Fire Component and Animation

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#112]
# **Description**
**Task:** [Fire Component](#112).
**Feature:** [Fire Extinguisher Design and Implementation](#103)

When a flame is instantiated at a position, an animated flame should be shown to screen above all other visual elements
 
## **Example (optional)**
- **Flame Spawning**: Flame should be able to be instantiated at a given position above all assets

# **Dependencies**
- [x] [Fire Extinguisher Asset needs to be made](#108)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fire Component needs to be created (Sep. 03)
- [ ] Fire animation needs to be added to the fire component (Sep. 03)
- [x] Fire should be able to be instantiated with location (Sep. 03)
 
**Completion Deadline:** Sep. 03
 
# **Documentation**
- [Fire Extinguisher] (../wiki/Fire-Extinguisher))
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Completed
