### ISSUE TITLE
Order System Extended

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#113]
# **Description**
Will add features to the order system to integrate it with other features, like creating a docket after a customer orders, removing the docket when completing an order, and improving the docket UI. Will also fix bugs found in the order system such as overlapping UI.

## SubFeature/component
Extending Order System
- Create docket after taking customer order (instead of button)
- Remove docket after completing order (instead of timer ending)
- Currency should increment when order is sucessfully complete. (maybe add a currency value to each docket)
- Bug Fixes

Improve docket style
- Use ingredient images instead of text
- Update background texture
- Update timer colour
- Fix the name display
- Display the customer's name who made the order

# **Dependencies**
- [x] (#60 ) to increment currency
- [x] (#8 ) to extend
- [ ] (#101 ) to take order
- [ ] (#xx) completing an order

# **Milestones**
- [x] Increment currency on complete order (Sep. 4)
- [ ] Fix bugs (Sep. 7)
- [ ] Improve docket style (Sep. 10)
- [ ] Docket integration with customers (Sep. 10)
- [ ] Documentation: description, usage, integration (Sep. 11)
- [ ] Tests + checking code coverage (Sep. 11)

**Completion Deadline:** Sep. 12

# **Extras**

# **Documentation**
- [Order System](../wiki/Order-System)
- [Currency](../wiki/Currency-(Gold))
- JavaDocs

# **Members**
- Aadya (@abhat0) (Aadya Bhatia)
- Shravya (@shravya132) (Shravya Chandrasekar)
