### ISSUE TITLE
Win Lose Checking

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#114]
# **Description**
There is little to no point in a game that has no conclusion, some way to know that the player has achieved their goals or failed in the attempt, thus a win and lose mechanic needs to be implemented. This will present as a function called at the end of each 'day' that checks certain variables (i.e. gold) to determine if the player has lost or won, and what the circumstances of this win or lose is. The correct win or loss state will then be triggered. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement Win/Lose Checking Logic #206 (Sept. 8)
- [x] Pull Necessary Game Variable (Gold) #208 (Sept. 9)
- [x] Trigger Win/Lose States #209 (Sept. 10)
- [x] Integrate with End-of-Day Event #210 (Sept. 11)

**Completion Deadline:** Sept. 11

# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Win-Loss-Logic

# **Members**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jackson Van Duikeren (aridspace10)
- Jason Mauchline (DistractedJ)
- Madeleine Coombs (madeleinecoombs)
- Jordan Russo (jRusso03)
