### ISSUE TITLE
Ending Cutscenes

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#115]
# **Description**
To facilitate story closure and cement the consequences of a player's actions, various cutscenes will be created, each correlating to one of the possible ways the player can finish the game. It is planned to start with two cutscenes, one for a good ending, and one for a bad ending, which will be triggered upon attaining their associated ending through gameplay.

# **Dependencies**

Complete integration of cutscenes relies on endings being called(#114 )

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] scripted actions for cutscene 1 (Sep. 5)
- [x] dialogue boxes for cutscene 1 (Sep. 8)
- [x] scripted actions for cutscene 2 (Sep. 9)
- [x] dialogue boxes for cutscene 2 (Sep. 10)
- [x] Both cutscenes trigger with linked ending (Sep. 12)

**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Bankruptcy cutscene
- [ ] Bad moral cutscene

# **Documentation**
- [Main description of feature](../wiki/Cutscenes)

# **Members**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jackson Van Duikeren (aridspace10)
- Jason Mauchline (DistractedJ)
- Madeleine Coombs (madeleinecoombs)
- Jordan Russo (jRusso03)
