### ISSUE TITLE
Music 

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#116]
# **Description**
The music of a game is extremely important to set the overall aesthetic and vibe of the game. With unique music, it allows player to associate music to parts of the game and overall paints an overall better picture.

## **Examples (optional)**
- Main game music will sound like overcooked with a general increase in the beats of music as the round gets closer to the end

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add Main game music (Sep 5)
- [x] Add gameplay music (Sep 10)
- [x] Add end game music (Sep 12)

**Completion Deadline:** Sep 12

# **Documentation**
- None

# **Members**
Princess Emeka-Ugwunali (Princess-Nx)
Jackson Van Duikeren (aridspace10)
Jason Mauchline (DistractedJ)
Madeleine Coombs (madeleinecoombs)
Jordan Russo (jRusso03)
