### ISSUE TITLE
Updated Player Sprite

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#117]
# **Description**
Updating the player sprite to utilise the player animation driver (link_to_animation_ticket), animating player movement in all directions (left/right, up/down, and the diagonals). Also expanding the sprite functionality to include the sprite reflecting the item currently in its inventory.

## SubFeature/component (optional)
- [x] Sprite library(s) design
- [x] Sprite animation (using updated designs)
- [x] Linking new animation to the update of the player's inventory

## **Examples (optional)**
- **Sprite**: Sprite renders initially with an empty inventory (not holding anything), when sprite picks up an item (dish, food item, etc.) the sprite is updated holding this item

# **Milestones**
- [ ] Design group of updated sprites (each holding the different items) (Sept. 8)
- [x] Expand player animation class to utilise the different classes of sprite (Sept. 10)
- [x] Update player inventory and rendering classes to use updated animation class (Sept. 11)

**Completion Deadline:** Sept. 12

# **Extras (optional)**

# **Documentation**
- [Wiki Page For Player Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Player-Interaction-and-Movement-Visuals)

# **Members**
- Alex (@amacn13) (Alex Macnamara)
- Alex (@ATOApplett) (Alex Ong)
