### ISSUE TITLE
Bench Upgrade

### ISSUE THREAD

**Issue by pineapple11111** [UQcsse3200/2024-studio-3#118]
# **Description**

The bench system needs to be overhauled to both allow for neat placement of benches (getting rid of the pixels sticking out and very small mistakes with the margins) and for items to be placed on the benches. Similar to how it is done in the hit video game series Overcooked, the benches should be comprised of multiple square sections—placing an item on the bench in turn placing it in the centre of a section. These sections should align with each other in a grid, and should match the size of stations. 

The way that the benches currently work, they are each long rectangles that need to be adjusted by extremely small increments to line up with one another. While placing objects on benches like these isn't impossible, it is difficult to figure out where on the bench an item should be placed, hence the grid. 

When items are placed they should appear in the correct location on the chosen bench.

# **Milestones**
- [x] **Make grid**: Choose grid size and build a system of placing objects in this grid. The current code in ForestGameArea does something similar to this, but it didn't really work in this way. Benches should not be able to be placed outside of the kitchen area. (8th September)
- [x] **Scale benches/stations**: Rescale benches and stations so that they match the specified tile size. Can be done simultaneously with the previous task since I would imagine it would be convenient for testing if the grid aligns correctly. 
- [x] **Place benches/stations**: Place all benches and stations in the map, same layout as how it was before. (10th September)
- [x] **Implement items being placed on benches**: Allow an item to be placed on a bench tile. (10th/11th September)

## **Dependencies**
- Upgrade Player sprite

## **Documentation**
- [Wiki Page For Bench Upgrade](https://github.com/UQcsse3200/2024-studio-3/wiki/Bench-Upgrade)

## **Members**
- Reza (@pineapple11111)
- Danh (@danhdinh98)
- Sarah (@Sarahkhalek)
