### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#119]
# **Description**
Add the pause menu when the user decides to pause during the game. It will be displayed on the Main Game Screen and will not occupy the entire screen. Pressing `O` will pops up the pause menu, and the menu can be closed by clicking the `exit` button.

## **Examples (optional)**
- **Pause Menu**: menu should include resume, restart, setting and exit buttons. 

# **Dependencies**
- Restart the whole game when "restart" button is clicked. This relies on some functionalities from the Day/Night Cycle (#120)
- `P` keypress for pausing - after the End Of Day Display team got Day/Night Cycle code (at the moment they are using `P` key binding for checking)  (#105)
- Pausing the game and displaying the Pause Menu should also ensure no new order are created and the time of the displayed orders should also be paused (#113)

# **Milestones**
- [x] Create pause menu prototype (Sep. 3)
- [x] Create new component inside components/maingame for pause menu (Sep. 3)
- [x] Implement the UI part of the pause menu (Sep. 8)
- [x] Implement the functionalities that handle each options on the menu (Sep. 10)
- [x] Ensure pause menu can be displayed in the Main Game Screen - modify createUI function inside MainGameScreen (Sep. 10)
- [ ] Documentation (Sep. 12)

**Completion Deadline:** Sep. 12

# **Members**
- Joanna (@Joanna-Wang105) 
- Daleela (@daleelakhairil)
