### ISSUE TITLE
Day/Night Cycle

### ISSUE THREAD

**Issue by AshHarikrishna** [UQcsse3200/2024-studio-3#120]
# Description
When game time reaches an end of day time, trigger the end of day screen using scheduled events. After Moral decision screen has ended, trigger a new day, restart orders, retain info from previous days and track current day and show the time left in the day as a timer.

Examples (optional)
Ticket orders should start at 0 each day, retain info like currency from previous day, track what current day it is. Make a digital timer, that countdown when the day starts. 

# Dependencies
- #8 , 
- #247 , 
- #105,
-  #102 

# Milestones

Integrate End-of-Day Event: Trigger the end-of-day screen at the designated game time. (6 Sep)
Initialise New Day: Reset ticket orders, retain currency, and start a new day after the moral decision screen.(8 Sep)
Track Current Day: Implement tracking for the current day and ensure data retention and finish timer. (10 Sep)
Conduct Testing: Test the end-of-day transition, moral decision screen, and new day (12 Sep)

- [x] Integrate End-of-Day Event: Trigger the end-of-day screen at the designated game time. (6 Sep)
- [x] Initialise New Day: Reset ticket orders, retain currency, and start a new day after the moral decision screen.(8 Sep)
- [x] Track Current Day: Implement tracking for the current day and ensure data retention and finish timer. (10 Sep)
- [x] Conduct Testing: Test the end-of-day transition, moral decision screen, and new day (12 Sep)

# Members
- Ashwin (@AshHarikrishna )
- Calvin (@CalvinJohn99 )
