### ISSUE TITLE
Station Item Update

### ISSUE THREAD

**Issue by nuciforan0** [UQcsse3200/2024-studio-3#121]
# **Description**
Add the ability for a stations held item to be updated, which can be called when a change in the station state is being completed.

## **Examples (optional)**
Through the work of this ticket, stations will be able to:
Update cooking ingredients state while being cooked (uncooked to cooked & cooked to overcooked)
Update dish being made by having ingredients change the state of a dish & combine ingredients

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Single item update in stations - Goal 1 - (Sep. 5)
- [x] Consideration for multiple items to interact - Goal 2 (Sep. 7)
- [ ] Use of the recipe.json to combine all items - Goal 3 (Sep 10.)
- [ ] Testing for this functionality implemented (Sep 12.)

**Completion Deadline:** Sep. 12

# **Documentation**
- Task Ticket ([../wiki/Entity-Component-System-(ECS)](https://github.com/UQcsse3200/2024-studio-3/issues/122))
- ...

# **Members**
- Nick (@nuciforan0) (Nicholas Nucifora)
