### ISSUE TITLE
Continuation and Development of Station Functionality

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#122]
# **Description**
This feature aims to extend the functionality and help to facilitate the interactions between the player, items, and stations. It aims to allow for easy outside interaction between the player and stations i.e. an interaction system with more features. It also aims to add life to stations through station animations, and by extending stations to be able to combine ingredients into dishes to be able to be served to customers. This will add depth and functionality to the game and be used by a variety of teams.

## SubFeature/component
- Developing ideas and specification of the different stations e.g. cutting board, combining station, raw food station
- Station animation and cooking
- Player-Station inventory interation
- Player-Station interaction
- Processing recipie JSON for use

## **Examples (optional)**
- Will add stations for getting raw ingredients, and combing cooked ingredients into dishes.
- Will have a complete interaction system between the player and the station's inventory for giving and taking items
- Will have a system for a player to interact with a station whilst an item is inside i.e. a functional cutting board.
- Will have a combining station that can take recipies.

# **Dependencies**
All dependencies for this feature currently exist in some form. However, some refining of them may be needed for ease of pulling them together for the intended functionality. Some new methods may need to also be written in order to achieve this.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Determine different types of stations (Sep. 5)
- [ ] JSON recipie parsing (Sep. 7)
- [ ] Player-Station complete inventory interaction (Sep. 10)
- [ ] Station animation (Sep. 7)
- [ ] Testing and verification (Sep. 10)

**Completion Deadline:** Sep. 12

# **Documentation**
- Documentation for player - station interaction to be created
- Documentation for all different station types to be created
- Documentation for ingredient combiner to be created
- Documentation for station animation will need to be created.

# **Members**
@silagarv 
@AdamsZach 
@Hayden-Elliott 
@StrayIntellectual 
@nuciforan0
