### ISSUE TITLE
Player Visuals (Movement and Interaction) + Bench Upgrades 

### ISSUE THREAD

**Issue by ATOApplett** [UQcsse3200/2024-studio-3#124]
# **Description**
In this sprint, the team will focus on enhancing player visuals and improving the bench system. For player visuals, we will update the sprite to integrate with the animation driver, enabling animations for movement in all directions and reflecting the currently held item. This includes designing a new set of sprites and expanding the animation class to support these updates. On the bench system side, we will remove the current grid system. This involves revamping the grid system, resizing benches and stations to match the tile size, and implementing the new design to improve usability whilst maintaining the current appearance. By the end of the sprint, these updates aim to refine player interaction and streamline item placement within the game.

## **Sub Tickets**
- **Player Visuals (#117)**: Updating the player sprite to use the player animation driver for movement animations in all directions and expanding functionality to reflect the item currently in the player's inventory.
- **Bench Upgrade (#118)**: The bench system will be revamped to enable precise placement with a grid-based layout, allowing for neat alignment and placement of items, similar to the system in Overcooked, to enhance usability and aesthetics in the game.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Design group of updated sprites (each holding the different items) (Sept. 8)
- [ ] Revamping of the grid system to compensate for the benches and stations (Sept 8)
- [ ] Expand player animation class to utilise the different classes of sprite (Sept. 10)
- [ ] Rescale benches and stations so that they match the specified tile size (Sept 10)
- [ ] Replacement of benches to match the current design however use the new grid system (Sept 10)
- [ ] Update player inventory and rendering classes to use updated animation class (Sept. 12)
- [ ] Implement items being placed on benches (Sept. 12)

**Completion Deadline:** Sep. 12th

# **Extras (optional)**
- [ ] Visually changing the main menu

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- Wiki Page For Player Design (TBA)
- Wiki Page For Bench Upgrade (TBA)

# **Members**
- Danh (@danhdinh98) (Danh Dinh)
- Sarah (@Sarahkhalek) (Sarah Abdulkhalek)
- Alex (@amacn13) (Alex Macnamara)
- Alex (@ATOApplett) (Alex Ong)
- Reza (@pineapple11111) (Reza Panday)
- Rakshit (@Rakshit31773 ) (Rakshit Singh)
