### ISSUE TITLE
[Team 1] Meal Composition and Rating Interactions

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#126]
# **Description**
Adds the in-game functionality of 1) putting together a meal, 2) serving a meal to a customer, and 3) getting a rating from that customer based on its encoded recipe. Each customer order should result in a meal (correct or not) being served to a customer to generate a rating and resolve that instance of the customer. The rating will currently be generated based on the items and forms of items (cooked, chopped, raw) in the meal presented to the customer.  

## Sub-Features
- Meal Creation: this process will occur on a Station (mechanics TBD) and turn Items into a Meal Component, which is able to carried by the Player and placed on other Stations.
- Meal Rating: this process will occur after a customer is presented with the meal, and will contribute to the Daily Performance of the Player in each day of the game. 

## **Dependencies**
- Decisions to be made about how Meal Creation will occur on Stations -- Station type, Item / Station Inventory Handler, etc.
- Decisions to be made about how Customer interactions will occur re: Meals -- likely also regarding Customer and Station functionality.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Functional MealComponent (Sep. 3)
- [x] MealComponent testing (Sep. 4)
- [x] Rating System based on Expected Meal vs Actual Meal (Sep. 9)
- [x] Rating System testing (Sep. 9)
- [x] Meal Creation process implemented (Sep. 10)
- [ ] Meal Creation testing (Sep. 11)

**Completion Deadline:** Sep. 11

# **Extras**
- [ ] Customer Interaction implementation, depends on Rating System Implementation (Sep. xx)
- [ ] Customer Interaction testing (Sep. xx) 
- [ ] Rolling daily average of Customer Rating from Customer Interactions.
- [ ] Allow the Customer to pay for a meal during the Interaction (connection to the Currency system if implemented) 

# **Documentation**
- [Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki)
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-3/)

# **Members**
- Anna Stevens (@goanna5)
- Serene McCormack (@serenemccormack)
- Quoc Bao Huynh (@bhuynh3004)
- Sourav Roy Chowdhury (@Sourav-RC)
- Benjamin Wang (@benjamin-wang1)
