### ISSUE TITLE
Creating dialogue text boxes

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#128]
# **Description**
**Task:** Creating dialogue text boxes
**Feature:** Ending cutscenes(#2)

Users need to understand what the character are saying and what is happening within the scene. This feature will be used not only for the ending cutscene but also for tutorial and any other explanation the game requires. 
 
## **Example (optional)**
![image](https://github.com/user-attachments/assets/95279b40-99fe-4b9c-a69a-79df156c3c00)

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create textbox which will fit to the amount of texts given (September 4th)
- [x] Texts will appear with typewriter like function which will slowly appear on the screen (September 7th)
- [x] Create key binding to allow enter to move to new text or remove textbox (September 8th)
- [ ] Textbox will disappear after a certain amount of time (September 10th)
- [x] Write tests (September 11th)
- [x] Write wiki (September 12th)
 
**Completion Deadline:** Sep. 7th
 
# **Documentation**
- None
 
# **Member**
Princess Emeka-Ugwunali (Princess-Nx)
Jackson Van Duikeren (aridspace10)
Jason Mauchline (DistractedJ)
Madeleine Coombs (madeleinecoombs)
Jordan Russo (jRusso03)
