### ISSUE TITLE
Combining ingredients to create a meal

### ISSUE THREAD

**Issue by willembor** [UQcsse3200/2024-studio-3#129]
# **Description**
In this feature, it will be utilising the bench station of the game. After ingredients have been through stations i.e. stove, cutting board, these ingredients will be combined using the bench station to create a completed meal to give to customers. Additionally, existing recipe functionality will be condensed and improved to better facilitate combining ingredients and the experience of creating recipes. (Discussed more in Examples and Extras).

## **Examples (optional)**
- **Bench Functionality**: Creating a class which handles combining multiple ingredients to produce a final recipe to give to a customer.
- **Clean up recipe functionality**: Collapsing single and multiple item recipe functionality into one, easy to use class.

# **Dependencies**
While there are numerous dependencies, the most significant relates to the combining station functionality outlined in #122.

# **Extras**
- Incorporate CookingComponent into StationInventoryComponent

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Plan reorganisation of CookingComponent and StationInventoryComponent (Sep. 5)
- [x] Collapse single item and multiple item functionality into one class (Sep. 7)
- [x] Testing and Verification of Methods (Sep. 10)

**Completion Deadline:** Sep. 12

# **Documentation**
- Documentation for collapsing single and multiple item recipe functionality
- Documentation for incorporating CookingComponent into StationInventoryComponent
- Documentation for Timer UI element whilst cooking

# **Members**
- Willem (@willembor)
- Alex (@Ashom2)
