### ISSUE TITLE
Grid to place benches

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#130]
# **Description**
**Task:** Grid to place benches 
**Feature:** Bench upgrade (#118)

 This task consists of creating a grid for where the benches should be. This would be suitable when having to place the stations on the game area, they would be on this grid (kitchen) which makes implementing features in the game easier (Would have to have a system to prevent benches being placed outside the kitchen area).

# **Dependencies**
- No dependencies for this task as we already have the map layout hence all we need to do is define the bounds of the kitchen (grid)
 
# **Milestones**
- [x] Defining the x and y bounds of the kitchen grid  (Sept. 8th )
- [x] Having a clear way/function that would be able to add benches inside this defined grid (Sept 8th)
- [x] Create JUnit test to check that the grid is correct (Sept 9th)
 
**Completion Deadline:** 8th of September
 
# **Documentation**
- - [Wiki Page For Bench Upgrade](https://github.com/UQcsse3200/2024-studio-3/wiki/Bench-Upgrade)
 
# **Member**
- @Sarahkhalek

**Comment by pineapple11111** [comment]
could not write junit tests for the grid since it was pretty much hardcoded
