### ISSUE TITLE
Redesign/scale benches

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#131]
# **Description**
**Task:** Making the benches into smaller tiles
**Feature:** Bench upgrade (#118)

This task is about redesigning the benches and making them smaller but splitting them into tiles similarly to how the kitchen floor is being rendered in the game. This would make implementing stations and different ingerdients/tools that need to be added to the game a lot easier. This would require rescaling the dimensions of the bench into probably a 2x2 tile that will be placed in the corresponding areas. 

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Deciding on the best size of the tiles (by experimenting while placing them) (Sept 8th)
- [x] Creating the light brown tiles that are often repeated for the different benches (Septh 8th)
- [x] Creating the additional tiles ones with shadows  (Sept 9th)
- [x] Making sure together the tiles form a consistent design of a bench (Sept 10th)
 
**Completion Deadline:** Sept 10th
 
# **Documentation**
-  [Wiki Page For Bench Upgrade](https://github.com/UQcsse3200/2024-studio-3/wiki/Bench-Upgrade)
 
# **Member**
- @pineapple11111 
- @Sarahkhalek
