### ISSUE TITLE
Creating the benches using new tiles

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#132]
# **Description**
**Task:** Creating the benches using the new tiles
**Feature:** Bench Upgrade #118 

This task consists of creating the benches and placing them in the kitchen area by adding together the newly created tiles. This should make the map layout look the same as sprint 1 but it would be with having the benches split into different tiles making it easier to replace one with a station like a stove or an oven. 

# **Dependencies**
- Creating the grid #130 
- Redesigning benches #131 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Creating the top and bottom benches (Sept 10th)
- [x] Creating the left and right benches (Sept 11th)
- [x] Placing the middle benches (Sept 11th)
- [x] #218
 
**Completion Deadline:** Sept 11th

# **Documentation**
- [Wiki Page For Bench Upgrade](https://github.com/UQcsse3200/2024-studio-3/wiki/Bench-Upgrade)
 
# **Member**
- @danhdinh98
