### ISSUE TITLE
Implementing player animations

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#133]
# **Description**
**Task:** Player animations 
**Feature:** Player sprite update #117 

 This task consists of using the different sprites of the player to implement animations when the playing is moving right, left etc to improve the design and make the game more interactive. 

# **Dependencies**
- #154 [Player Animation Component]
- [Updated Sprite Generation]
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implementing the new sprites/adding them to the game (Sept. 9th)
- [x] Making sure that they update when the user presses on the movement keys (Sept. 10th)
- [x] Create JUnit tests to check that the player sprite updates correct when pressing corresponding arrow keys (Sept 10th)

**Completion Deadline:** Sept. 10th

# **Documentation**
- [Wiki Page For Player Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Player-Interaction-and-Movement-Visuals)
 
# **Member**
- @ATOApplett (Alex Ong)
- @amacn13 (Alex Macnamara)

**Comment by pineapple11111** [comment]
finished tests
