### ISSUE TITLE
Player interactions with items

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#134]
# **Description**
**Task:** Update the player sprite when interacting with items (picking up)
**Feature:** Update player sprite (#117)

This tasks consists of designing different sprites when the player is interacting with items. This needs to be incorporated with the different actions that a player does at each station. 

# **Dependencies**
- For this feature to work completely, we need to collaborate with the stations team which area dealing with the key interactions when an action happens. When this is done, we can our player sprite update to their code.

# **Milestones**
- [x] Create different sprite interactions with objects (Sept 10th)
- [ ] Implement with the station's team (Sept 11th)
- [ ] Create JUnit tests to tests that the sprite changes to the correct one when interacting with items (Sept 12th)

**Completion Deadline:** Sept 12th

# **Documentation**
- [Wiki Page For Player Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Player-Interaction-and-Movement-Visuals)

# **Member**
- @amacn13
