### ISSUE TITLE
Fix the left black border

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#135]
# **Description**
**Task:** Fix the left black border
**Feature:** #124 

This team working on the customers/animals said the black border was preventing the animals from moving properly from top to bottom on the map. Hence this needs to be fixed by adjusting our black border to prevent this problem from happening.

# **Dependencies**
No dependencies
 
# **Milestones**
- [x] Redesigning the black border (Sept 8th)
- [x] Placing it on the map appropriately (Sept 8th)
- [x] Check with the customer team for functionality (Sept 8th)
 
**Completion Deadline:** Sept 8th

# **Documentation**

 
# **Member**
- @Rakshit31773
