### ISSUE TITLE
Multiple Types of Station Entities

### ISSUE THREAD

**Issue by nuciforan0** [UQcsse3200/2024-studio-3#14]
# **Description**
**Task:**  Add different stations to the Station entity #14
**Feature:** [Feature which this tasks contributes to implementing](#2)

Incorporate components to the Station Entity so that the following features are implemented:
Type of Station is stored (Ingrediants, Table, Stove, Bin, etc)
Certain stations can have parameters such as time (for how long it takes to cook) 
Most stations need to store the current entity being stored

# **Dependencies**
- [ ] Dependency 1 (#13)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 - add functions for handling different types of stations (Aug. 19)
- [ ] Step 2 - Incorporate desk framework (Aug. 20)
- [ ] Step 3 - Incorporate Stove (Aug. 23)
- [ ] Step 4  - Incorporate Ingrediants (Aug. 23)
 - [ ] Step 4  - Incorporate Bin(Aug. 23)

**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
