### ISSUE TITLE
Plate Component

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#140]
# **Description**
This covers plates in the game mimics overcooked plates system. Plate component to be used throughout the game.

## **Part Methods**
PlateComponent:
- create
- initializePlateArray
- update
- addMealToPlate
- disepose
- handlePlateInteraction
- interactWithPlate
- pickup
- letdown
- getQuantity
- getItemOnPlate
- setQuantity
- isPickedUp
- isAvailable
- isServable
- isWashed
- isStacked
- setStacked
- getPlateArray
- setPlateArray
- getId
- setID

PlateFactory:
- createTemplatePlate
- spawnPlate
- spawnPlateStack
- spawnMealOnPlate
- diseposePlate
- getMealTexturePath

# **Dependencies**
- [x] Components needs to be implemented to be able to implement this function (prelude)
- [x] PlayerActions needs to be implemented to be able to implement this function  (#4)
- [x] textureImages needs to be created and loaded to be able to implement this function 

# **Milestones**
List of tasks for this feature.
- [x] UML Diagram and sketch (Sep. 7)
- [x] Constructing methods  (Sep. 8)
- [x] Create  plate image .png files (Sep. 8)
- [x] Create Single plates and render(Sep. 8)
- [x] Create multiple plates and render(Sep. 9)
- [x] Making plates interactable by PlayerActions  (Sep. 9) - > Plates can be interacted stacks can be interacted and rerendered
- [x] Create and implement addMealtoPlate and render item on plate(Sep. 10)
- [x] Constructing tests for methods (Sep. 10)
- [x] Completing documentation and wiki (Sep. 11)

**Completion Deadline:** Sep. 11

# **Documentation**
- [PlateComponent Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/PlateComponent)

# **Members**
- Airyl (@airylsuaidi) (Airyl Harridzuan Bin Suaidi)
