### ISSUE TITLE
Currency System Extended

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#141]
# **Description**
**Task:** Currency System
**Feature:** Order System Extended (#113 )

To do:
A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")

# **Dependencies**
- [ ] player to have gold
- [ ] (#8 ) to remove dockets

 
# **Milestones**
- [ ] add trigger to remove gold (Sep 3.)
- [ ] add methods to get set and add and update gold  (Sep 3.)
- [ ] increment gold when order is complete  (Sep 3.)
 
**Completion Deadline:** Sep 3.

# **Documentation**
- [to do: Main description of feature](../wiki/Game-Screens)
- to do: [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Aadya (@abhat0 ) (Aadya Bhatia)
