### ISSUE TITLE
Integrate Dockets with Customers

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#142]
# **Description**
**Task:** Integrate Dockets with Customers
**Feature:** Order System Extended (#113 )

The docket should appear when an order is taken from the customer. The customers name should be on the docket. The docket should be removed when the order is complete.

Take order from customer:
- is the player taking the order? 
- How will the player interact with the customer?

Customer takes meal
- does the player give the meal to the customer? 
- does the customer take a mean from the station?
- does the meal have to be complete for the customer to take / be given?
- how do we know when order is complete?

# **Dependencies**
- [x] (#8 ) to create and remove dockets
- [ ] (#101 ) to have customers 
- [ ] Player takes orders from customers
- [x] Player gives orders to customers
 
# **Milestones**
- [ ] Create docket after a player takes an order from a customer order (team 8 - customers)
- [ ] Docket should have the name of the customer that made the order 
- [x] Remove docket after customer recives a meal from the player/station. 
- [ ] Documentation 
- [ ] Tests
 
**Completion Deadline:** Sep. ??
 
# **Documentation**
- To do: [Main description of feature](../wiki/Game-Screens)
- To do: [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- ???
