### ISSUE TITLE
Order System Bug Fixes

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#143]
# **Description**
**Task:** Order System Bug Fixes (#143)
**Feature:** Order System Extended (#113 )

This task will fix bugs that have been found in the order system classes

# **Dependencies**
- [x] (#8 ) to display dockets
 
# **Milestones**
- [x] Limit to 8 dockets at a time
- [x] Fix order system UI overlapping other UI
- [x] Change docket texture atlas at correcy time intervals
- [x] Docket timers pause when game is paused (Sep. 11)    (team 2 pause screen)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Order System](../wiki/Ordering-System-Overview)
 
# **Member**
- Aadya (@abhat0 ) (Aadya Bhatia)
