### ISSUE TITLE
Game Tutorial (Interactions Only)

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#146]
# **Description**
Introduce players to the core gameplay interactions ie. movement, cooking, interacting with NPCs, and moral decision-making. Guides player through the first day of working at the restaurant, presenting various tasks like picking up items, preparing food, and serving customers, alongside small ethical choices. If time allows, a help menu will also be implemented (accessible from main game screen) allowing players to see a summary of keys and their interactions.

## SubFeature/component (optional)
- **W/A/S/D movement**: Show on-screen instructions prompting players to use the W/A/S/D keys to move in different directions, with visual feedback to indicate it has been done correctly. Completing this task triggers next part of the tutorial.
- **Item interaction**: Instruct the player to pick up an item at a station and move it to another station, with tooltip outline around and visual feedback. 
- **Cooking tasks**: After the player drops an item at the stove, show visual progress bar over the cooking station, showing the cooking time remaining, and explain that items must cook for. a certain amount of time.
- **Moral decisions**: Pop up presenting a simple moral choice (yes or no question), explain the impact of the decisions, provide rewards/ feedback for making both choices.

# **Dependencies**
- #101 and #136 for order system walkthrough
- #121 and #122 for cooking system walkthrough
- #134 for item interactions walkthrough

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement basic player movement tutorial using W/A/S/D keys, with on-screen prompts (Sep. 7)
- [x] Introduce item pickup and drop functionality. (Sep. 8)
- [x] Implement a sequence where the players learns to create and cycle through orders (Sep. 11)
- [x] Testing and documentation (done throughout) (Sep. 11)

**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Help menu
- [ ] Game backstory

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Tia (@tia-w) (teeyahisswag123)
- Lakshay (@LAKSHAYATREJA) (masterlakshay)
