### ISSUE TITLE
Movement Interaction Tutorial

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#148]
# **Description**
**Task:** Movement Interaction Tutorial.
**Feature:** (#146)

Introduces the player to basic movement controls. Players will use the W/A/S/D keys to move around the game world, on-screen prompts show them the controls. Once the player successfully moves in all directions, visual feedback to confirm they have done it correctly/ incorrectly, and the tutorial will advance to the next step.
 
## **Example (optional)**
- **Prompt**: "Press W to move up."
- **Feedback**: After pressing W, the player moves up and an arrow confirms the action, and the next movement prompt (A/S/D) is displayed.

# **Dependencies**
None.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the movement prompts and visuals (Sep. 5)
- [x] Implement movement triggers for feedback (Sep. 6)
- [x] Test movement flow and feedback functionality (Sep. 7)
 
**Completion Deadline:** Sep. 7

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia (@tia-w) (teeyahisswag123)
