### ISSUE TITLE
Fire Extinguisher Blows Out Fire with Animation

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#149]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Fire Extinguisher Design and Implementation](#103)

When the player is holding a fire extinguisher and interacts with the station that is on fire, then the fire is blown out. This will be the only way a fire extinguisher can interact with a station; any other interaction does nothing.
 
## **Example (optional)**
- **Blowing out fire**: Player leaves item in stove too long and it catches alight, they then need to get the fire extinguisher, move over to the station, interact with it while holding the fire extinguisher and blow out the fire.

# **Dependencies**
- [ ] Fire needs to be able to be spawned on a station.

 
# **Milestones**
List of steps that need to be completed for this task. 
- [ ] Add blowing out fire to the interaction with a station (Sep 8)
- [ ] Add a fire extinguisher animation when using the component. (Sep 9)
- [ ] Show the fire extinguisher animation when interacting with the fire extinguisher (Sep. 10)
 
**Completion Deadline:** (Sep 11)
 
# **Documentation**
- [Fire Extinguisher](https://github.com/UQcsse3200/2024-studio-3/wiki/Fire-Extinguisher)
 
# **Member**
- Caleb Murphy (Caleb-j-Murphy)
