### ISSUE TITLE
Item Pickup and Interaction Tutorial

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#150]
# **Description**
**Task:** Item Pickup and Interaction Tutorial.
**Feature:**(#146 )

Tutorial segment where the player learns to pick up items and move them between stations. The tutorial will show a tooltip when the player approaches an item, instructing them to press a certain key to pick it up. The player will then move the item to a designated station and drop it, receiving visual feedback once the action is completed.
 
## **Example (optional)**
- **Prompt:** "Press Space to pick up the meat."
- **Feedback:** The item is highlighted, and upon picking it up, it follows the player’s movement until placed on the next station (also highlighted).

# **Dependencies**
- [ ] (#134) for key presses and item pick-uo.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Establish item interaction logic, implement prompts for what keys to press and tool-tip outline for what station to move item to once picked up (Sep. 6)
- [ ] Determine logic to track player movements once they've picked up the item, to ensure they are placing it at the correct station. (Sep. 7)
- [ ] Integrate item interaction tutorial with movement and test to ensure working properly (Sep. 8)
 
**Completion Deadline:** Sep. 8

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia (@tia-w) (teeyahisswag123)
