### ISSUE TITLE
Cooking Station Tutorial

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#151]
# **Description**
**Task:** Cooking Station Tutorial.
**Feature:** (#146)

Introduce players to cooking mechanics by teaching them to place items on a cooking station. The tutorial will display a progress bar over the station, indicating the cooking time remaining. Players will receive prompts to wait until the item is cooked, with feedback provided once the cooking is complete.
 
## **Example (optional)**
- **Prompt**: "Place the meat on the stove."
- **Feedback**: A progress bar fills up over the stove, and the cooked item renders, progress bar flashes when ready for pickup.

# **Dependencies**
- [x] (#121)
- [x] (#122)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement visual prompts to player to cook the item (Sep 8.)
- [ ] Integrate existing station timers with progress bar pop-ups (Sep. 9)
- [x] Integrate with other tutorials to ensure they all work cohesively (ie. completion of one leads to another) (Sep. 10)
 
**Completion Deadline:** Sep. 10
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia (@tia-w) (teeyahisswag123)
