### ISSUE TITLE
Customer Interaction Tutorial

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#152]
# **Description**
**Task:** Customer Interaction Tutorial.
**Feature:** [Feature which this tasks contributes to implementing](#2)

Teach players how to take orders from NPC customers. The tutorial will introduce the order system and how to read and fulfill customer requests. Players will learn to prepare and serve food within a time limit, and visual feedback will show when a customer is satisfied or becomes angry.
 
## **Example (optional)**
- **Prompt:** "Serve the cooked meat to the customer before they get angry."
- **Feedback:** A patience meter decreases as time passes, and the customer reacts to the service (happy or angry).

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] (#101)
- [x] (#136)

# **Milestones**
- [ ] Establish customer interaction logic and create prompts (Sep. 9)
- [ ] Implement the customer patience meter and feedback (Sep. 10)
- [ ] Integrate with all remaining tutorials (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia (@tia-w) (teeyahisswag123)
- Lakshay (@LAKSHAYATREJA) (masterlakshay)
