### ISSUE TITLE
Create New Tutorial Class to handle all Tutorial Gameplay

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#153]
# **Description**
**Task:** Create New Tutorial Class to handle all Tutorial Gameplay.
**Feature:** (#146)

When player enters start screen, they can click on a 'start tutorial' button to take them to a tutorial screen separate from the main gameplay screen. 
 
## **Example (optional)**

# **Dependencies**
- None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new screen class, TutorialScreen, that will manage the tutorial mode. (Sep. 5)
- [x] Create a way of visually displaying the TutorialScreen UI updates. (Sep. 5)
- [x] Modify Main Menu Screen to include a tutorial button (Sep. 5)
- [x] Implement switch case in tutorial screen to handle specific tutorials ie. pick up items, movement etc. (Sep. 5)
 
**Completion Deadline:** Sep. 5

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**

- e.g. Tia (@tia-w) (teeyahisswag123)
