### ISSUE TITLE
Update Player Sprite Generation

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#155]
# **Description**
**Task:** [Updated Player Sprite Generation]
**Feature:** #117 [Updated Player Sprite]

Generating batch of player sprites, both with an empty inventory and then one holding each of the different items / ingredients etc.
 
## **Example (optional)**
A sprite outline of the generic chef sprite, another outline of the sprite holding a raw tomato, another with a cooked tomato, etc.

# **Dependencies**
No dependencies

# **Milestones**
List of steps that need to be completed for this task.
- [x] General sprite completed (Sept. 5)
- [x] Ingredients sprites completed (Sept. 7)
- [x] Miscellaneous sprites completed (e.g. fire extinguisher, completed dishes) (Sept. 8)
 
**Completion Deadline:** Sept. 9

# **Documentation**
 
# **Member**
- Alex Macnamara (@amacn13)
