### ISSUE TITLE
Plate component framework task

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#156]
# **Description**
**Task:** Plate component Class
**Feature:** PlateComponent(#140)

Plate component class. Handles plates in the game. An item that has states isAvailable, isWashed, spawn and also can be disposed. This covers plates in the game mimics overcooked plates system. Plate component to be used throughout the game.
 
## **Example (optional)**
PlateComponent:
- create() - create plate component
- initializePlateArray() - initialize stack plate array
- update() - update component
- addMealToPlate() - add meal to plate
- dispose() - dispose plate
- handlePlateInteraction() - handle player interactions with the plate
- interactWithPlate() - handle interaction logic
- pickup() - pickup plate interaction logic
- letdown() - letdown plate interaction logic
- getQuantity() - returns quantity of stacked plate
- getItemOnPlate() - returns items on plate
- setQuantity() - set quantity of stacked plate
- isPickedUp() - returns status of pick up items
- isAvailable() - returns status of availability of plate
- isServable() - returns servability of plate
- isWashed() - returns wash status of plate
- isStacked() - returns stack status of plates
- setStacked() - set stack of plates with quantity
- getPlateArray() - returns plateArray
- setPlateArray() - set plateArray
- getId()- returns id of single plate
- setID() - set id of single plate

PlateFactory:
- createTemplatePlate() - PlateTemplate
- spawnPlate() - spawn individual plates with id 
- spawnPlateStack() - spawn stack of plates with quantity
- spawnMealOnPlate() - spawn meal plate render
- diseposePlate() - dispose plate handler
- getMealTexturePath() - return of mealtexturepath from meal name

# **Dependencies**
- [x] Components needs to be implemented to be able to implement this function (prelude)
- [x] PlayerActions needs to be implemented to be able to implement this function  (#4)
- [x] textureImages needs to be created and loaded to be able to implement this function 

# **Milestones**
List of tasks for this feature.
- [x] UML Diagram and sketch (Sep. 7)
- [x] Constructing methods  (Sep. 8)
- [x] Create  plate image .png files (Sep. 8)
- [x] Create Single plates and render(Sep. 8)
- [x] Create multiple plates and render(Sep. 9)
- [x] Making plates interactable by PlayerActions  (Sep. 9) - > Plates can be interacted stacks can be interacted and rerendered
- [x] Create and implement addMealtoPlate and render item on plate(Sep. 10)
- [x] Constructing tests for methods (Sep. 10)
- [x] Completing documentation and wiki (Sep. 11)

 
# **Documentation**
- [PlateComponent Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/PlateComponent)
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
