### ISSUE TITLE
Creating new sprites for meals

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#162]
# **Description**
**Task:** Creating new sprites for meals (#).
**Feature:** [Team 1] Meal Composition and Rating Interactions (#126)

Create new pixel art sprites for each of the 4 meals that can be created as well as a generic "incorrect meal" image to make the design more consistent for the ingredient and recipe entities throughout the game. Although there are some existing sprites, the art style and pixel size is inconsistent and in some cases is blurry or has a watermark.
 
# **Dependencies**
- [ ] [Team 1] Meal Composition and Rating Interactions (#126)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Start a mockup for each meal design (Sep. 8)
- [ ] Step 2 Design sprites for meals (Sep. 10)
- [ ] Step 3 Design new sprites for some items as well (maybe) (Sep. 10)
- [ ] Step 4 Complete and upload to repository (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- 
 
# **Member**
- Anna Stevens (@goanna5)
