### ISSUE TITLE
Servery Station

### ISSUE THREAD

**Issue by nuciforan0** [UQcsse3200/2024-studio-3#163]
# **Description**
Makes the base accepting station which handles the acceptance of the meal and the current big ticket. This can be called by the rating component developed by another team to further handle good and bad submissions. 

## SubFeature/component (optional)
Requires the use of the ticket component to determine the current big ticket's ingredients 
The MealComponent or the PlayerInventory to determine information related to the current meal

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Make a dummy version of the station so other teams can implement it - Goal 1 (Sep. 9)
- [x] Implement the functionality of the station (Sep. 11)
- [ ] Implementing testing (Sep. 12)

**Completion Deadline:** Sep 12.

# **Documentation**

# **Members**
- Nicholas (@nuciforan0) (Nicholas Nucifora)
