### ISSUE TITLE
Extend Inventory Display Component

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#165]
# **Description**
**Task:** Extend Inventory Display Component
**Feature:** (#126)

Extend the current InventoryDisplay component to display a boxes for each inventory slot and the items they hold. This will allow any entity that uses an InventoryComponent to display the items in the inventory to the user if needed.

# **Dependencies**

- [ ] Inventory System (#6)
- [ ] Simple InventoryDisplay Component made to extend (#66)
 
# **Milestones**

- [ ] Create box display images and render them (Sep 8)
- [ ] Add Item images into the boxes (Sep 9)
- [ ] Extension: highlight selected inventory slot (Sep 10)
- [ ] Extension: make the display interactable (i.e. can click on slots to select them, etc)
 
**Completion Deadline:** Sep 10.
 
# **Documentation**
- [Main description of feature](../wiki/Inventory-System)

# **Member**
Benjamin Wang (@benjamin-wang1)
