### ISSUE TITLE
Player Interaction with Stations

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#167]
# **Description**
**Task:** Combine existing systems to allow movement of Items, Ingredients, Meals to move from player to station and vice versa
**Feature:** #122 

Add the player inventory to Service Locater or similar to achieve a global insight to allow interaction trigger on station side to validate interactions and move items around suitably.
 
## **Example (optional)**
- **Taking from Station**: On interaction trigger with station, check that player inventory is empty and that station contains an Item, call onto Player Inventory component and add Item to player inventory 

# **Dependencies**
Need update of Station inventory component to abstract inventory class

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Set up Player inventory on Global (Sept. 7)
- [x] Change interaction trigger to single general purpose handled station side (Sept. 7)
- [x] Add movement of Objects between inventories (Sept. 7)
- [x] Update Inventory Display Component (Sept. 7)
- [x] Appropriate JUNIT tests (Sept. 9)
- [x] Wiki Documentation (Sept. 10)
 
**Completion Deadline:** Sept. 11

 
# **Documentation**
TBD
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Hayden (@Hayden-Elliott )
