### ISSUE TITLE
Moving Boss Sprite

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#168]
# **Description**
**Task:** Moving Sprite
**Feature:** Ending Cutscenes(#115)

A half decent cutscene needs moving elements, so to facilitate this when a cutscene is triggered some sprites will appear and move around the screen. Specifically the boss sprite needs to appear for cutscene 1, bad ending, and move to the middle of the restaurant serving area.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Unique factory function for creating boss sprite (Sep. 6)
- [x] Boss sprite appears and moves to center (Sep. 7)
- [x] Boss sprite placeholder is removed and replaced with actual sprite (Sep. 8)
 
**Completion Deadline:** (Sep. 8)
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- 
 
# **Member**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jackson Van Duikeren (aridspace10)
- Jason Mauchline (DistractedJ)
- Madeleine Coombs (madeleinecoombs)
- Jordan Russo (jRusso03)
