### ISSUE TITLE
Add Item-Handling component 

### ISSUE THREAD

**Issue by StrayIntellectual** [UQcsse3200/2024-studio-3#17]
# **Description**
**Task:** [Add item handling component under station entity](#3).
**Feature:** #3 

Add a method to accept an item within a station (e.g. a oven station should be able to accept a food item and execute a given function based on the food input). 

 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.

# **Dependencies**
- [x] Station needs to be implemented to be able to implement this function (#16)
- [x] Generic item class needed to test function (#15)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial implementation of function (Aug. 23 )
- [x] Unit test implemented (Aug. 25)
- [x] Component tested and implemented (Aug. 26)
- [x] Documentation updated (Aug. 27)
 
**Completion Deadline:** Aug. 27

# **Documentation**
- [Main Description of Feature](https://github.com/UQcsse3200/2024-studio-3/wiki/Stations#stationitemhandlercomponent)
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Andi (@StrayIntellectual )
- Hayden (@Hayden-Elliott ) (Hayden Elliott)
- Callan (@silagarv) (Callan Silagarv)

**Comment by Hayden-Elliott** [comment]
- Checks for if station already has item
- Check if station is compatible

**Comment by Hayden-Elliott** [comment]
Callum - java docs
Hayden - JUnit testing

**Comment by Hayden-Elliott** [comment]
Purposeful partial implementation and subsequent testing due to gaps in functionality to be provided by other teams
