### ISSUE TITLE
Making and Animating Boss Sprite

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#170]
# **Description**
**Task:** Making and Animating Boss Sprite
**Feature:** Ending Cutscenes(#115)

The boss entity would look a lot cooler in the game if it had a texture, so lets give it one, and also add animations while we're at it.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Source boss textures (Sep. 6)
- [x] Apply texture to boss sprite (Sep. 7)
- [x] Animate boss sprite (Sep. 8)
 
**Completion Deadline:** Sep. 8
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jackson Van Duikeren (aridspace10)
- Jason Mauchline (DistractedJ)
- Madeleine Coombs (madeleinecoombs)
- Jordan Russo (jRusso03)
