### ISSUE TITLE
Level Component

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#171]
# **Description**
**Task:** [Level Component](#171)
**Feature:** [Level System](#106)

Implementing a `Component` that tracks variables regarding customers for the current level, and uses them with the `update()` method in order to have a "spawn controller" - an `Entity` which is constantly checking if it can spawn a customer if certain conditions are met.

# **Milestones**
- [x] Define class
- [x] Implement private variables that are needed to be tracked
- [x] Implement methods for setting them and retrieving them
- [x] Overwrite the `update()` so that it acts as a constant monitor for whether or not a customer can be spawned
- [x] Trigger customer spawning event
 
 
# **Documentation**
- 
 
# **Member**
- Michael (@IWontCauseAFuss) (idontwanttocauseafuss)
