### ISSUE TITLE
Implementation of "Advanced spawning" and appropriate "Level Progression"

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#172]
# **Description**
**Task:** [Implementation of "Advanced spawning"](#172).
**Feature:** [Level System](#106)

Currently, the overall Level System is only changing levels when the player quits to the main menu and re-enters the game, and only spawns a generic customer without any configurations. In order to make it fully functional, code implemented by team 8 for spawning a customer with configs and when the player ends the current day/level needs to be unified with the current level system framework in order to have the game at a basic level of functionality. 

# **Dependencies**

- [x] Level Service (#107)
- [x] Level Component (#171)
- [x] Customer Extended (#101)
- [x] End of Day Extended (#105)
 
# **Milestones**

- [x] Learn how other code works
- [x] Update framework to call configured customers when appropriate
- [x] Add next level triggers to end of day code
- [x] TEST!!!
 
**Completion Deadline:** Sept. 9
 
# **Documentation**
- 
 
# **Member**
- Michael (@IWontCauseAFuss) (idontwanttocauseafuss)
