### ISSUE TITLE
Customer movement to counters and leaving restaurants

### ISSUE THREAD

**Issue by V4N5HM** [UQcsse3200/2024-studio-3#175]
# **Description**
**Task:** Refine the customer movement to the counter in the customer spawning area and the trigger to be used when the order is served. Implement a timer to exit the restaurant in case the customer runs out of patience before the event is triggered.
**Feature:** [Customer Extended](https://github.com/UQcsse3200/2024-studio-3/issues/101)
 
 
# **Dependencies**
- [Customers](https://github.com/UQcsse3200/2024-studio-3/wiki/Customers)
- [Service Locator](https://github.com/UQcsse3200/2024-studio-3/wiki/Service-Locator)
- [Event System](https://github.com/UQcsse3200/2024-studio-3/wiki/Event-System)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the PathFollowTask movement to the counter (Sept. 6)
- [x] Create the CustomerBehaviourComponent and create a service in the service locator for the trigger to function. (Sept.9)
- [x] Implement the system timer to work and creating the leaving the restaurant movement (Sept. 9)
- [x]  Create the unit tests(Sept 10)
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Customers](https://github.com/UQcsse3200/2024-studio-3/wiki/Customers)
 
# **Member**
Vansh Mittal (@V4N5HM)
