### ISSUE TITLE
Moral System Buttons.

### ISSUE THREAD

**Issue by nimeshgarg** [UQcsse3200/2024-studio-3#181]
# **Description**
**Task:** [Adding Selection to Moral].
**Feature:** [Moral System](#102)

Adding Clickable Buttons to screen and recording the response in moral system.

# **Dependencies**
- [X] Moral System UI (#144)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add a list of dummy Moral Decisions. (Sept 9)
- [x] Implement a system to keep track of Moral Decisions. (Sept 9)
- [ ] Add UI Element of Buttons (Sept 10)
- [ ] Recording the Response (Sept 10)
- [ ] Adding Documentation (Sept 12)
 
**Completion Deadline:** Sept 12

# **Optional**
- [ ] Fixing the pause/resume to stop the game time when game state is paused.
 
# **Documentation**
- [Moral Decision Display](https://github.com/UQcsse3200/2024-studio-3/wiki/Moral-Decision-Display)
- [Moral Decision](https://github.com/UQcsse3200/2024-studio-3/wiki/Moral-Decision)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Nimesh Garg (@nimeshgarg)

**Comment by nimeshgarg** [comment]
Closing Ticket.
New ticket for Sprint 3 will be created with exact moral decisions as decided by story team along with different screen for each day.
