### ISSUE TITLE
Create Item Component class

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#19]
# **Description**
**Task:** Create an item component class
**Feature:** Items (https://github.com/UQcsse3200/2024-studio-3/issues/5)

All items which will exist in the game will come from an ItemComponent class which will serve as a base for the system to use. These will consist of basic variable such as a weight, is it pickable and much more. Getters and setters will exist for these and multiple constructor which will be used for different type of items depending on their implementation. 

#** Example **
Some of the variable which will be added is
- Type (ENUM)
- Name (string)
- isPickupAble (bool)
- weight (float)
 
# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Item component class created with basic constructor (Aug 19)
- [x] Decide on basic variables which will be needed for the class (Aug 21)
- [x] Getters and setters created for variables (Aug 23)
- [x] Create tests for getters and setters (Aug 28)
- [x] Update wiki (Aug 30)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- None
 
# **Member**
- Jackson Van Duikeren (@aridspace10)
