### ISSUE TITLE
Component Development for Backend Stations

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#194]
# **Description**
**Task:** Create necessary backend components to set up structure and clear flow for future functionality
**Feature:** #122

In coordination with others members of team establish necessary stations and propose components needed. Develop and incorporate systems to polish and establish clear workflow

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get Proposal (Sept. 1)
- [ ] Develop backend components (Sept. 8)
- [ ] Test components (Sept. 9)
- [ ] Wiki (Sept. 9)
 
**Completion Deadline:** Sept. 11

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Callan (@silagarv) (Callan Silagarv)
