### ISSUE TITLE
Colour Palette/ Map Design

### ISSUE THREAD

**Issue by danhdinh98** [UQcsse3200/2024-studio-3#2]
# **Description**

The goal of this spint is to implement the basic visual game design.

The first feature will involve the implemention of an empty restaurant layout to fit with the cooking theme. This will serve as an empty slate and allow for further map improvement for the future implementations. The second feature involves the implementation of the main interactive elements within the map such as the cooking station layout. Extras include implementation of other interactive elements such as doors, benches, etc. and updating the player sprite to fit with the cooking theme.

# **Milestones**
1. Designing the map and main stations/ objects and update wiki documentation
- Design a colour palette
- Design layout of interactive elements and cooking stations e.g. L shaped layout, rectangle shaped layout

2. Implementing map design and main stations/ objects
- Create base dimensions of map
- Create cooking station layout

List of sub-features to have done and in Master by the end of the sprint.
- [x] Design a colour pallete and update wiki page (Aug. 20) *note: merged into map design wiki*
- [x] Design base map layout and update wiki page(Aug. 23)
- [x] Create base dimensions of map (Aug. 26)
- [x] Create cooking station layout (Aug. 28)

**Completion Deadline:** Aug. 29

# **Extras (optional)**
- [ ] Basic interactive elements or objects e.g. doors, benches, tables, plates, grills, sinks, chopping boards, cooking stations
- [ ] Update player sprite to fit cooking theme

# **Documentation**
- Refer to and update [Terrain documentation](../wiki/Terrain)
- Refer to and update [User interface documentation](../wiki/UI)
- Wiki page for [Colour Palette](../wiki/Colour-Palette) *note: merged into map design wiki*
- Wiki page for [Map Design](../wiki/Map-Design)

# **Members**
- Danh (@danhdinh98) (Danh Dinh)
- Sarah (@Sarahkhalek) (Sarah Abdulkhalek)
- Alex (@amacn13) (Alex Macnamara)
- Alex (@ATOApplett) (Alex Ong)
- Reza (@pineapple11111) (Reza Panday)
- Rakshit (@Rakshit31773 ) (Rakshit Singh)

**Comment by JTrenerry** [comment]
This seems like a lot of work for one sprint and your first, I recommend putting some stuff into Extras

**Comment by danhdinh98** [comment]
> This seems like a lot of work for one sprint and your first, I recommend putting some stuff into Extras

Thanks for the feedback @JTrenerry.
I have removed excess items from the scope and moved some goals into the extras.

**Comment by JTrenerry** [comment]
> > This seems like a lot of work for one sprint and your first, I recommend putting some stuff into Extras
> 
> Thanks for the feedback @JTrenerry. I have removed excess items from the scope and moved some goals into the extras.

Looks a lot better thank you.

**Comment by danhdinh98** [comment]
We found that we do not need to separate the colour palette and map design into two separate wikis as they are tightly coupled.

Therefore, we will be combining the colour palette wiki into the map design wiki and the colour scheme wiki will be deleted/ archived.

Please see the [map design wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/Map-Design) for colour scheme related documentation.
