### ISSUE TITLE
Spawn Items

### ISSUE THREAD

**Issue by Princess-Nx** [UQcsse3200/2024-studio-3#20]
**Task:** [Spawn Items].
**Feature:** [Items](#5)

The task involves implementing a system for spawning items in the game world. This will include creating food and meals by using component to show this item to the screen.
 
## **Example (optional)**

# **Dependencies**:

- Item Component, Meal Component and Food Component class need to be implemented

# **Milestones**

- [x] Create ItemFactory class  (Aug 20)
- [x] Factory with 5 items (Aug 23)
- [x] Add unit testing (Aug 27)
- [x] Add to wiki (Aug 30)

**Completion Deadline:** Aug. 30
 
# **Documentation**
[- [JavaDoc](JavaDoc/Location/Package/Class)](https://github.com/UQcsse3200/2024-studio-3/wiki/Entity-Component-System-(ECS))
 
# **Member**
- Jackson Van Duikeren
