### ISSUE TITLE
Pull Necessary Game Variable (Gold)

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#208]
# **Description**
**Task:** [Pull Necessary Game Variable (Gold)].
**Feature:** [Win Lose Checking] (#114)

This task involves pulling relevant game state variable, gold from other game components. This variable will be used by the CheckWinLoseComponent to evaluate whether the player has won or lost. The player's gold will be pulled using the CombatStatsComponent, which tracks the player's current gold status. The player’s gold will be set from the player.json config, and real-time changes (such as after an order is completed) will update the gold amount. This value will be evaluated to check for win or lose conditions.

## **Example (optional)**
- After each order completion, the player's current gold is updated. If the player's total gold exceeds the win amount, a win is triggered. If the player's gold falls below the lose threshold, a loss is triggered.

# **Dependencies**
- [x] Dependency on CombatStatsComponent for tracking gold. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Pull gold from CombatStatsComponent and integrate it into the win/lose logic (Sept. 9).
- [x] Test that getGold() is working within our game context (Sept. 11).
 
**Completion Deadline:** Sept. 11
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Win-Loss-Logic
- https://github.com/UQcsse3200/2024-studio-3/wiki/Currency-(Gold)
 
# **Member**
- Madeleine Coombs (@madeleinecoombs)
