### ISSUE TITLE
Trigger Win/Lose States

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#209]
# **Description**
**Task:** [Trigger Win/Lose States].
**Feature:** [Win Lose Checking] (#114)

This task involves triggering the appropriate win or lose state based on the conditions evaluated in the CheckWinLoseComponent. When a win condition is met at the end of the 'day' (e.g., total money exceeds the win amount), the game should transition to the good ending cutscene. Similarly, if a lose condition is met (e.g., store rating falls too low), the game should end with a failure screen. This task requires integration with the cutscene system to properly display the win/lose screens and end the game.
 
## **Example (optional)**
- If the player reaches the target amount of money at the end of the 'day', the game will trigger the good ending cutscene.

# **Dependencies**
- [x] Dependency on GoodEnd cutscene system for triggering the win state and then exiting. 
- [x] Dependency on BadEnd cutscene system for triggering the lose state and then exiting. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Integrate with GoodEnd cutscene and trigger win state (Sept. 10).
- [x] Integrate with BadEnd cutscene and trigger lose state (Sept. 10).
- [x] Test win/lose transitions in the game context to ensure they work correctly (Sept. 6).
 
**Completion Deadline:** Aug. 11
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Currency-(Gold)
- https://github.com/UQcsse3200/2024-studio-3/wiki/Cutscenes
 
# **Member**
- Madeleine Coombs (@madeleinecoombs)
