### ISSUE TITLE
Tooltip Functionality

### ISSUE THREAD

**Issue by Anshuman0157** [UQcsse3200/2024-studio-3#21]
# **Description**
**Task:** Tooltip Functionality for Interactable Objects
**Feature:** Player Action and Interaction (https://github.com/UQcsse3200/2024-studio-3/issues/4)

When the player comes within range of an interactable object and it is the closest object, a tooltip will appear to the top right of the player, displaying the button required to interact with the object and the item name will be shown above it.
 
## **Example**
- If the player is holding an onion and is near the chopping board, a tooltip displaying the interaction key for the chopping board is shown.

# **Dependencies**
- [ ] This ticket depends on the ItemFactory, as items must be defined and instantiated correctly for interaction to occur. 
(#20)

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement Tooltip Display with Interaction Key and Item Name  (Aug 19)
- [ ] Dynamic Update of Tooltip Content Based on Proximity (Aug 21)
- [ ] Document Tooltip Functionality (Aug 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-3/wiki/Player-Interactions)
 
# **Member**
- Anshuman Misra (Anshuman0157)
