### ISSUE TITLE
Create new stations 

### ISSUE THREAD

**Issue by AdamsZach** [UQcsse3200/2024-studio-3#214]
# **Description**
**Task:** [Create and design new stations required for the current recipes](#3)
**Feature:** [#122 ](#2)

This task invloves creating and designing new stations that will be required to carry out the creation of the recipes within the game. 
# **Dependencies**
This task does not have any dependencies.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Research the necessary stations required for existing recipes 
- [x] Collaborate with recipes team to ensure the stations align with the requirements of the current and future recipes
- [x] Design the sprites for the new stations 
 
**Completion Deadline:** Sep. 5
 
# **Documentation**
- [New stations with images](../wiki/stations)
 
# **Member**
- Zachary Adams (@AdamsZach)
