### ISSUE TITLE
Implement new main menu title screen

### ISSUE THREAD

**Issue by danhdinh98** [UQcsse3200/2024-studio-3#216]
# **Description**
Main menu title screen does not relate to current theme of the game "Beastly Bistros" and can be improved to further add to the immersion and design consistency. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Design title screen game logo (Sep. 5)
- [x] Implement new logo (Sep. 8)
- [x] Modify button design and layout (Sep. 10)
- [x] Change title screen background (Sep. 12)

**Completion Deadline:** Sep. 12

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)

# **Members**
- Danh (@danhdinh98) (Danh Dinh)
- Rakshit (@Rakshit31773) (Rakshit Singh)
