### ISSUE TITLE
Implement new main menu logo and buttons

### ISSUE THREAD

**Issue by danhdinh98** [UQcsse3200/2024-studio-3#217]
# **Description**
**Task:** [Implement new main menu logo and buttons](#217).
**Feature:** [Implement new main menu title screen](#216 )

Implement new logo relevent to the current theme of the game for "Beastly Bistros" and modify button layout and design to improve button accessibility, readibility and visuals.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design logo (Sep. 8)
- [x] Implement logo (Sep. 10)
- [x] Modify button design and layout (Sep. 11)
- [x] Documentation for new logo and button design choices updated on wiki (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
 
# **Member**
- Danh (@danhdinh98) (Danh Dinh)
