### ISSUE TITLE
Designing the background of the Main Menu

### ISSUE THREAD

**Issue by Rakshit31773** [UQcsse3200/2024-studio-3#220]
# **Description**
**Task:** To create an attractive background.
**Feature:** Designing the background of Main Screen of the game

Collect gifs of various animals that suit the theme and spin them around the background for an interesting look.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Collect gifs (Sep. 8)
- [x] Spin them and move across the map (Sep. 10)
- [x] Randomize the movement (Sep. 11)
- [ ] Documentation and update wiki (Sep. 12)
 
**Completion Deadline:** Sep 12

# **Member**
- Rakshit (@Rakshit31773)
