### ISSUE TITLE
Customer ordering

### ISSUE THREAD

**Issue by V4N5HM** [UQcsse3200/2024-studio-3#221]
# **Description**
**Task:** Make the Order tickets display actual customer preference orders instead of random orders.
**Feature:** [Customer Extended](https://github.com/UQcsse3200/2024-studio-3/issues/101)
 
 
# **Dependencies**
- [Ordering System](https://github.com/UQcsse3200/2024-studio-3/wiki/Ordering-System-Overview)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement a list to store the active spawned customers .(Sept. 6)
- [x] Create an order manager to retrieve the preferences and recipes from the json files. (Sept.9)
- [x] Using these components to display the actual customer preferences instead of random recipes in the MainGameActions (Sept. 10)
- [x] #393
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Ordering System](https://github.com/UQcsse3200/2024-studio-3/wiki/Ordering-System-Overview)
 
# **Member**
Vansh Mittal (@V4N5HM)
