### ISSUE TITLE
Fire gets created when timer goes below 0 for cooking an item

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#222]
# **Description**
**Task:** [Fire gets created when timer goes below 0 for cooking an item](#222).
**Feature:** [Fire Extinguisher Design and Implementation](#103)

When the timer for a station drops below 0, a fire gets created if the station is `hot`. If the station is not hot, this check does not occur.
- **Oven**: The oven is hot and if an item is left inside of it for too long then it catches alight.

# **Dependencies**
- [x] Fire component needs to be created
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawn flame at location on station (Sep. 12)
- [x] Add Documentation (Sep. 12)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Station-Components](../wiki/Station-Components)
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)
