### ISSUE TITLE
Fire is extinguished when a fire extinguisher is used on it by the player

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#223]
# **Description**
**Task:** [Fire is extinguished when a fire extinguisher is used on it by the player](#223).
**Feature:** [Fire Extinguisher Design and Implementation](#103)
When the player is holding a fire extinguisher and they interact with a fire, the fire is extinguished. This means that the fire is then removed from the station.

# **Dependencies**

- [ ] Fire component needs to have been created
- [ ] Stations need to be able to spawn a fire component
- [ ] (#222)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Remove fire when interact while holding a fire extinguisher (Sep 12)
- [ ] Document how the fire works (Sep 12)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Main description of feature](../wiki/TODO)
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Not able to be completed
