### ISSUE TITLE
Moving an Order Ticket 

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#23]
# **Description**
**Task:** Moving an Order Ticket (#23).
**Feature:** Order System (#8)
Implement a mechanism through which a rendered order ticket (`Ticket` class) may be moved, either to be pinned to the top of the screen alongside other orders, switching the placement of orders, or to be pinned on the side of the screen to be maximised. `Ticket` inherits from `ItemComponent`, and will have event handlers that will respond to user actions, namely clicking and dragging across the screen, or shuffling between pinned orders. The functionality will be integrated with the existing ticket display system to ensure that changes are reflected correctly in the UI.  

 
## **Example (optional)**
- [x] **Pinning Area** - When players drag an order ticket, there is a designated area where they are able to pin it. If time allows, the 'pinning area' will be implemented - when the ticket component is situated within this 'pinning area' it will automatically pin to the top alongside other order tickets. 

# **Dependencies**
- [x] Creating the `ItemComponent` class (#19)
- [x] Rendering the ticket on screen  (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Ticket class extended to incorporate properties that affect where the ticket is moved to(Aug. 19)
- [x] Added event handlers (Aug. 23)
- [x] Implemented ticket swapping functionality (Aug. 24)
- [x] Updated UI components (Aug. 27)
- [x] Merged with docket maximising code (Aug. 28)

 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia Waturuocha (@tia-w) (Tia Waturuocha)
