### ISSUE TITLE
Score System Component Testing

### ISSUE THREAD

**Issue by Sourav-RC** [UQcsse3200/2024-studio-3#232]
# **Description**
**Task:** Score System Component Testing.
**Feature:** [Meal Composition and Rating Interactions](https://github.com/UQcsse3200/2024-studio-3/issues/126)

Writing unit tests for Score System Component.

# Objective
Improve the test coverage for `ScoreSystemComponent.java` to ensure robustness, catch edge cases, and validate behavior under various scenarios.

# Testing Plan

### Unit Tests
- [x] Test `compareLists` for full match
- [x] Test `compareLists` for partial match
- [x] Test `compareLists` for no match
- [x] Test `compareLists` with empty lists
- [x] Test `getScoreDescription` for all score ranges
- [x] Test `getScoreDescription` with negative scores
- [x] Test `getScoreDescription` with scores above 100
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Sourav Roy Chowdhury (@Sourav-RC)
