### ISSUE TITLE
Expanding Order Ticket

### ISSUE THREAD

**Issue by shravya132** [UQcsse3200/2024-studio-3#24]
# **Description**
**Task:** Expanding Order Ticket.
**Feature:** Order System (#8)

This task focuses on implementing a component to expand an order docket so that the user can view its contents. Only a single ticket, which is positioned at the upper rightmost corner of the screen, will be expanded at a time. This task is constant throughout gameplay (ie. cooking and ordering map screens).
 
## **Example (optional)**
- **Part**: If the user wishes to view the order ticket, the upper right-most section will display and expand the docket after the user interacts with said ticket. 

# **Dependencies**
- [x] Initial ticket render (#27).
- [x] Location area of the unselected order dockets (#25). 
- [x] Movement mechanism of the docket (#23). 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Assign and position area for ticket expansion (Aug. 24)
- [x] Set measurements for enlarged and not enlarged dockets (Aug. 25)
- [x] Implement function to call ticket expansion and minimisation (Aug. 25)
 
**Completion Deadline:** Aug. 21
 
# **Documentation**
- [Main description of feature](../wiki/Ordering-System-Overview)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Shravya (@shravya132) (Shravya Chandrasekar)
