### ISSUE TITLE
Adding a Customer Component Sensor

### ISSUE THREAD

**Issue by bhavyamalik1** [UQcsse3200/2024-studio-3#245]
# **Description**
**Task:** Adding a Customer Component Sensor

The component will handle collision events to determine if a customer is within the specified radius and update the list of nearby customers accordingly. It will include methods to identify the closest customer for interaction, and once a customer is in range, it will trigger relevant events to allow the player to interact with the customer (for example, placing an order)

# **Dependencies**
N.A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create the interface for the component (Sep. 7)
- [x] Implement the customers entities in the component (Sep. 8)
- [x] Finish the sensor (Sep. 10)
- [x] Create unit tests for the sensor (Sep. 11)
 
**Completion Deadline:** (Sep. 12)
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Customer-Interaction
 
# **Member**
- Bhavya Malik (@bhavyamalik1 )
