### ISSUE TITLE
Pinned Docket Line

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#25]
# **Description**
**Task:** Pinned Docket Line (#25)
**Feature:** Order System (#8 )

There will be a section of the screen implemented by `DocketLineDisplay` class, where dockets are pinned and waiting to be completed by the player. Orders can appear on this pinned area when a new order is taken from a customer and when the player drags an order from the primary order area to the pin line. Dockets will be removed from the pin line when the order is complete or when the order is dragged out by the player to the main docket display area.

# **Dependencies**
- [x] (#24 ) to remove ticket out of pin line and into the primary docket area
 
# **Milestones**
- [x] Document a prototype of the layout of the pin area UI on the wiki (Aug. 19)
- [x] Get/create assets for UI that match the games style (Aug. 19)
- [x] Render `DocketLineDisplay` (Aug. 20)
- [ ] Document `DocketLineDisplay` class usage (Aug. 27)
- [x] Test `DocketLineDisplay` class (Aug. 28)
- [x] Merge with team4-order-system branch (Aug. 28)
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Ordering System Overview](../wiki/Ordering-System-Overview)
- [DocketLineDisplay](https://uqcsse3200.github.io/2024-studio-3/com/csse3200/game/components/ordersystem/DocketLineDisplay.html)
 
# **Member**
- Aadya (@abhat0) (Aadya Bhatia)
