### ISSUE TITLE
Display amount of cash

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#250]
# **Description**
**Task:** Display amount of cash
**Feature:** [End of Day Extended](#105)
 
Display amount of cash that the player has.
 
# **Dependencies**
 - [UI Component](https://github.com/UQcsse3200/2024-studio-3/wiki/UI)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Display amount of cash user has (Sept. 11)
- [x] Display amount in gold layout UI (Sept. 11)
- [x] Display coin UI (Sept.11)
 
**Completion Deadline:** Sept. 11
 
# **Documentation**
- [UI Component](https://github.com/UQcsse3200/2024-studio-3/wiki/UI)
- [End of Day](https://github.com/UQcsse3200/2024-studio-3/wiki/End-of-Day-Display)
 
# **Member**
Lei Su (@ImLeiSu)
