### ISSUE TITLE
Add keybinds to settings page UI

### ISSUE THREAD

**Issue by Marshall-Bullis** [UQcsse3200/2024-studio-3#26]
Task: Add the key binds to the settings so that they can be customised later
Feature: Player Action and Interaction (#4)

We are adding different forms of interaction such as picking up items moving through the inventory and interacting with stations. Players need to be aware of how these actions can be performed and given the freedom to change these key bindings. Documentation will need to be developed for this. A player has the ability to change the key binds but they are restricted to only 1 keyboard button and the buttons cannot overlap.
 
Example (optional)
- When in settings, a player can alter the interact button to 'q' but not 'qq'. And if 'q' is already bound, then it cannot be bound to a new event.

Dependencies
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add the UI label and input fields into the settings page (Aug 17)
- [ ] Create logic to test for valid key binds (non-duplicate, single buttons) (Aug 18)
- [ ] Save the new binds in the .json file so that they remain over time (Aug 19)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Marshall (Marshall-Bullis)
