### ISSUE TITLE
StationMealComponent for handling meal creation.

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#266]
# **Description**
**Task:** StationMealComponent for handling meal creation.
**Feature:** #126 

StationMealComponent is based on the the framework developed by the stations team to allow for dynamic recognition of a meal based on the items added to the station by the player. This component is added to combination station/s on their creation, and has a dynamically sized inventory that allows for more than 1 item to be added, as current recipes have 2 or more ingredients. 
 
# **Dependencies**
- [x] Check functionality of MealComponent
- [x] Station handling framework
- [x] DishFactory refactor
 
# **Milestones**
- [x] Design required features for the component, including getters and processing functions. 
- [x] Write implementation for detecting a meal if possible, given current ingredients.
- [x] Write implementation for creating the possible meal, and returning it to the station inventory.
- [x] Test integration with a bench component and player interations.
 
**Completion Deadline:** Sep. 11

# **Documentation**
- [Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki)
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-3/)
 
# **Member**
- Serene McCormack (@serenemccormack) (serene_mccormack)
