### ISSUE TITLE
Render Order Ticket Instance

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#27]
# **Description**
**Task:** Render Order Ticket Instance.
**Feature:** Order Ticket (#8)

Rendering a ticket object box at the correct area. Order tickets can be multiple and be rendered side by side horizontally. Order tickets can be disposed and disposal will trigger reRender() to reRender all remaining tickets.

## **Example (optional)**
- **Render Ticket**: Will render a ticket box in a  ticket area. 
- **Dispose Ticket**: Will dispose the ticket render and dispose the current render

# **Dependencies**
- [x] Order ticket render needs to be created in a Docket line (#25 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] OrderTicketDisplay class sketch and rough dimensions decision(Aug. 19)
- [x] Creating an OrderTicketDisplay class UML diagram with its details(Aug. 19)
- [x] Creating a simulation show button at menu (Aug. 21)
- [x] Creating an OrderTicketDisplay class with its details(Aug. 22)
- [x] Creating a create() method to render open order tickets to area ticket (Aug. 22)
- [x] Creating an update() method to reRender the current ticket details (time etc.) (Aug. 23)
- [x] Creating a dispose() method to dispose current rendered ticket (Aug. 23)
- [x] Stacking Order Tickets side by side (for multiple orders) (Aug. 26)

**Completion Deadline:** Aug. 26

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Airyl Harridzuan Bin Suaidi (@airylsuaidi)
