### ISSUE TITLE
Create Cutscenes for each start of the day. 

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#278]
# **Description**
Cutscene should be shown on the screen at the start of each day with dialogue, artwork and storyline. The player should be able to skip the cutscene if they want with the spacebar and this should be visible to the player on the screen.

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
- **Cutscene linking**: Cutscenes link to a specific level

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.
Cutscenes rely on different levels being made TODO

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] #279
- [x] #280
- [x] #281
- [ ] Cutscenes move to an assigned level (Sep. 21)
- [x] #288 Sep. 22
- [x] #329
- [x] #411
- [ ] #441 (Oct. 03)

**Completion Deadline:** (Oct. 4)

# **Extras (optional)**
- [ ] Add voice lines for the Dialogue
- [ ] Create animations for the cutscenes

# **Documentation**
- [Cutscenes - NEED TO CREATE](../wiki/Entity-Component-System-(ECS))
- [Character Art - NEED TO CREATE/LINK] (../wiki/Entity-Component-System-(ECS)

# **Members**
- Caleb Murphy (Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Still need to create the day 3, day 4 and day 5 cutscenes

**Comment by Caleb-J-Murphy** [comment]
Fully created now
