### ISSUE TITLE
Create Cutscene Component (Sep. 18)

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#279]
# **Description**
**Task:** [Create Cutscene Component](#279).
**Feature:** [Create Cutscenes for each start of the day](#278)

Create a component that acts as an intermediate level. It is called at the end of a level, it runs it's cutscene, then it calls the beginning of the next level. For example, when finishing level 2, there will be a cutscene that will provide context to level 3, then after this cutscene, level 3 will load in. This ticket involves the creation of this component as well as the game area.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] New level can be loaded (Sep. 16)
- [x] Create a new Game Area for cutscenes (Sep. 21)
- [x] Create a new Screen to Load Cutscenes from (Sep. 21)
- [x] Cutscene Game Area Creation (Sep .18)
- [x] Cutscene load next level when they end (Sep. 18)
- [x] #396
 
**Completion Deadline:** Sep. 20
 
# **Documentation**
- [Cutscenes](https://github.com/UQcsse3200/2024-studio-3/wiki/Cutscenes)
- ...
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Cutscenes Work Completely now, this is closed.
