### ISSUE TITLE
Create Inventory Feature Branch

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#28]
# **Description**
**Task:** Create Inventory Feature Branch
**Feature:** [Team 1] Inventory System

## **Description**
The development team requires a feature branch to begin work on the Inventory System. This allows or concurrent development worklows with the other teams on the Unnamed Animal Project. 

# **Dependencies**
N/A

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create feature branch on local repository (Aug. 16)
- [x] Push branch to main branch for team visibility (Aug. 16)
- [x] Check that team members can access feature branch (Aug. 17)
 
**Completion Deadline:** Aug. 17
 
# **Documentation**
- The branch name is team1/inventory
 
# **Member**
- Serene (@serenemccormack) (serene_mccormack)
