### ISSUE TITLE
Create Character Artwork for Cutscenes (Sep. 19)

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#280]
# **Description**
**Task:** [Create Character Artwork](#280).
**Feature:** [Create Cutscenes for each start of the day](#278)

Create character artwork for the cutscenes. Each character introduced should have their own sprite that can be shown within a game area.
 
## **Example (optional)**
- **Mob Boss**: The mob boss, which is a rhino has it's own 32px wide artwork for the game.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Mob Boss (Sep. 15)
- [x] Create Henchman (Sep. 15)
- [x] Create Mob Boss Daughter (Sep. 15)
- [ ] Create Food Inspector (Oct. 2)
- [ ] Create Chef Image (Oct. 2
- [ ] #286
- [ ] #287
 
**Completion Deadline:** Aug. 19
 
# **Documentation**
- TODO
 
# **Member**
- Caleb Murphy (Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
There are more characters that could be added. TBD

**Comment by Caleb-J-Murphy** [comment]
All character artwork has been added.
