### ISSUE TITLE
Create Cutscene Backgrounds (Sep. 20)

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#281]
# **Description**
**Task:** Create Cutscene Backgrounds
 
This task involves designing and implementing backgrounds for the cutscenes that play at the start of each day. 
 
# **Dependencies**
None.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design Graveyard Background (Sep. 18)
- [x] Design Failed Grave Scene (Sep. 19)
- [x] Design Restaurant Background (Sep 20)
 
**Completion Deadline:** Sept. 20
 
 
# **Member**
- Anshuman Misra (Anshuman0157)
- Caleb Murphy (Caleb-J-Murphy)
