### ISSUE TITLE
Migrating PlateComponent to extend ItemComponent

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#282]
# **Description**
**Task:** Migrating PlateComponent to extend ItemComponent.
**Feature:** Plate Component(#140)

Migrating PlateComponent class to extend ItemComponent instead of extending Component. To ease integration with InventoryComponent and etc.
 
## **Example **
**Part**: 
- Extend ItemComponent instead of Component
- Adding Constructors to allow extend 

# **Dependencies**

- [x] ItemComponent to be implemented (#19)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Extend ItemComponent instead of Component (Sep. 15)
- [x] Adding constructors to allow extending (Sep. 15)
- [x] Testing and debugging (Sep. 15)
- [x] Update Wiki (Sep. 15)
 
**Completion Deadline:** Sep. 15
 
# **Documentation**
- [PlateComponent Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/PlateComponent)
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
