### ISSUE TITLE
Save/load game

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#284]
# **Description**
The save/load game feature is a feature which is apart of mostly all games used to save progress of the user in the game. This is necessary for all games but for our game especially important as having to restart from day one would take a very long time. There will be multiple save files which will be able to save simple stuff as the coins, moral standing but also more complex stuff like inventories and customer positions. 

# **Dependencies**
- Main and pause menu working

# **Milestones**
- [x] #304
- [x] #354
- [ ] Create more advanced load game functionality (stores item locations, customer locations) (Oct 1)
- [x] Create tests (Oct 2)
- [x] Create wiki (Oct 3)

**Completion Deadline:** Oct 3

# **Documentation**

# **Members**
- Jackson Van Duikeren (aridspace10)

**Comment by JTrenerry** [comment]
Make sure you add it to the project
