### ISSUE TITLE
Backstory Cutscenes

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#285]
# **Description**
On starting the game, there will be animations/cutscenes which explain the games backstory. This feature should be in the game because it adds an extra layer of depth to game play.

Since a major component of this sprint is adding in cutscenes, that means the story needs to actually be written. A well planned and established backstory makes the writing of the actual story easier as it allows for the world and characters to be more fleshed out, as well as providing a "resource" that can be drawn upon in the actual story.

## SubFeature/component
- World backstory
- Characters backstories
- Location backstory
- Customer backstory

# **Dependencies**
- story creation (#??)

# **Milestones**
- [x] Stories created (Sep. 18)
- [x] All art finalised (Sep. 26)
- [x] All art rendered with text display (Sep. 30)
- [x] Tests (Oct. 2)
- [x] Documentation (Oct. 3)

**Completion Deadline:** Oct. 3

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
Aadya (@abhat0) (Aadya Bhatia)
Shravya (@shravya132) (Shravya Chandrasekar)
Michael (@IWontCauseAFuss) (Michael Kidd)
Lakshay (@LAKSHAYATREJA)(Lakshay Atreja)
Tia (@tia-w) (Tia Waturuocha)
Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
