### ISSUE TITLE
Write More Complex Inventory Methods

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#29]
# **Description**
**Task:** Write More Complex Inventory Methods
**Feature:** [Team 1] Inventory System

## **Description**
The Inventory Component will support interactions to add / pickup an item, remove / place an item, select an item, and swap an items between inventories (eg. between the player inventory and the station inventory). ._ 

# **Dependencies**
- [x] Create Feature Branch (#28 )
- [x] Initialise Inventory Component (#33 )
- [x] Item Type To Be Finalised By Other Team (#19)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write methods for adding / removing an item from the inventory (Aug. 23)
- [x] Write methods for checking an item at an index / first position / last position (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-3/)
 
# **Member**
- Serene (@serenemccormack) (serene_mccormack)
