### ISSUE TITLE
Team 2 Upgrades

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#290]
# **Description**
During the day, the NPC (penguin) enters and you have 10 seconds to decide whether you want to interact with it. You can only interact with the NPC by clicking on the penguin when the exclamation mark pops up. Once you interact with the NPC, the game pauses, and a UI popup appears with an upgrade decision and YES/NO buttons. A message of not enough gold will show if you don't have enough gold to purchase the upgrade. The NPC will only come once a day at a random time.

Each upgrade will have a cost - monetary or moral - and a duration.

## **Examples (optional)**
- Speed up movement
- Faster cooking time after fulfil a certain number of orders
- Double gold from orders
- Loan 100 gold

# **Dependencies**
- Gold (team 6)
- Order System (team 4) #8
- Integrate Dockets with Customers (team 4) #142 
- Moral System (team 8) #102 

# **Milestones**
- [x] Make upgrade classes - Speed boots, rage, extortion, loan (22/09)
- [x] Apply random upgrade (from keybind) (29/09)
- [x] Upgrade decision UI (27/09)
- [x] Upgrade NPC vendor (2/10)

**Completion Deadline:** Oct 3

# **Members**
- Joanna (@Joanna-Wang105)
- Calvin (@CalvinJohn99 )
- Willem (@willembor )
- Alex (@Ashom2 )
- Ashwin (@AshHarikrishna )
- Daleela (@daleelakhairil )

**Comment by CalvinJohn99** [comment]
![after_all_tests](https://github.com/user-attachments/assets/a838b410-b3f9-476c-a9f5-b7c50968ae53)
