### ISSUE TITLE
Extortion Upgrade

### ISSUE THREAD

**Issue by Ashom2** [UQcsse3200/2024-studio-3#292]
# **Description**
**Feature:** [Team 2 Upgrades](#290)

A class for handling the functionality for receiving the "extortion" upgrade. When the upgrade is applied, the player will receive double gold from completed orders at the cost reputation for 1 minute.
 
# **Dependencies**
- [x] Gold getter and setter methods (team 6)
- [ ] Orders implementation (team 4)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Define attributes (Sep. 20)
- [x] Write methods (Sep. 22)
- [ ] Unit testing (Sep. 27)
 
**Completion Deadline:** Sep. 27
 
# **Member**
- Alex (@Ashom2)
- Willem (@willembor)
