### ISSUE TITLE
Ending Cutscenes

### ISSUE THREAD

**Issue by jRusso03** [UQcsse3200/2024-studio-3#293]
# **Description**
Implement animated cutscenes to play when an end-game state is reached within the game. This will sum the story of the game up in a visually pleasing way and be more immersive and detailed than the current in-game cutscenes.

## SubFeature/component 

- Story/Lore design 
- [Win/Loss System](../wiki/Win-Loss-Logic)

# **Milestones**

- [x] Stories created (Sep. 18)
- [x] Cutscene art finished (Sep. 24)
- [x] Cutscene atlas files completed (Sep. 26)
- [x] Testing completed (Sep. 28)
- [x] Documentation Completed (Sep. 30)

**Completion Deadline:** Sep. 30

# **Documentation**
- [Ending Cutscenes](../wiki/Ending-Cutscenes)

# **Members**
- Jason @DistractedJ 
- Jordan @jRusso03 
- Princess @Princess-Nx

**Comment by JTrenerry** [comment]
Make sure you add it to the project
