### ISSUE TITLE
Player Backstory

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#294]
# **Description**
**Task:** Player Backstory(#294).
**Feature:** Backstory Cutscenes(#285)

Writing the narrative for the player backstory sequence of the intro backstory cutscenes. Once finalised, will be used to guide the making of the animated intro sequence. 
 
## **Example (optional)**
- **Pre-main game screen sequence**: When the player clicks the start button, the player backstory sequence will succeed the world backstory sequence. 

# **Dependencies**

- [x] Ending Cutscenes (#293) - ensure consistency with all other game cut scenes
- [x] In-game Cutscenes
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Player's core conflict (Sep. 18)
- [x] Player's main moral dilemmas (Sep. 18)
- [x] Player's emotional motivations (Sep. 18)
 
**Completion Deadline:** Sep. 18

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia(@tia-w) (teeyahisswag123)
