### ISSUE TITLE
Rage Upgrade

### ISSUE THREAD

**Issue by CalvinJohn99** [UQcsse3200/2024-studio-3#295]
# **Description**
**Feature:** Team 2 Upgrades (#290)

Once the player fulfills a certain number of orders, their rage meters fills up and have the option to go into "rage" mode. When the player goes into rage mode, the player is able to cook much faster for the rest of the day (or) for a certain time period. This may allow the player to fulfill orders if they are running out of time. However, there is a downside to "raging", i.e., your moral factor will be negatively affected and this will tie into the win-loss conditions for the game. The player will be allowed to exit rage mode before the meter is depleted for faster recharging and future "raging".

*Update*: Due to changes in the game direction, we will no longer manipulate the moral factor.

# **Dependencies**

- Cooking and Cook Times (Team 5)
- Order System (#8)
- Moral System (#102)
- Integrate Dockets with Customers (#142)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement rage meter and screen color change on key press (Oct. 25)
- [x] Add a multiplier for the cook time and decrease the moral factor (Aug. 25)
- [x] Implement ability to exit "rage" mode faster.
- [ ] Testing (Oct. 29)
- [x] Documentation of `rage` added to wiki (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Calvin John Shaji (@CalvinJohn99 ) (@degr8pheonix)
- Ashwin Harikrishna (@AshHarikrishna)
