### ISSUE TITLE
World Backstory

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#296]
# **Description**
**Task:** [World Backstory](#296)
**Feature:** #285

A vital part of the backstory is world building, as it establishes the tones and themes of the story, as well as informing/shaping the plot. World building would include establishing a history of major events, what the culture of the world is and what the current state of the world is. These inclusions would help provide a more compelling narrative for players to get invested in.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Establish a basic timeline/timeframe
- [x] Establish important historical moments in recent years
- [x] Establish the culture
- [x] Establish the state of the world
 
**Completion Deadline:** Sept. 25
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Michael Kidd (@IWontCauseAFuss) (idontwanttocauseafuss)
