### ISSUE TITLE
Station Spawing and Temporary Map Tweaks

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#297]
# **Description**
**Task:** Station Spawning and Functionality clean up
**Feature:** #276 

Work on creating and spawning stations necessary for other functionality and basic gameplay. Throughout this process troubleshoot backend component processing bugs.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Initial Overview and Basic Recipe Interaction (Sept. 17th)
- [ ] Backend Component Fixing (Sept. 24th)
- [ ] Functions to create all necessary stations with placeholder components where necessary (Sept. 28th)
- [ ] Implementation of final station spawning capabilities (Sept. 30th)
- [ ] Wiki documentation (Oct 1st)
- [ ] Testing updates to match updated components (Oct. 2nd)
 
**Completion Deadline:** Oct. 2nd)

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by Hayden-Elliott** [comment]
Unintended close
