### ISSUE TITLE
Station Processing Framework

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#3]
# **Description**
Framework and base implementation of generic station class for interaction and input of Item class. Design of exact station characteristics and related functionality. Stations include oven, bench, cooktop and cutting board. Stations will spawn in a set location to be aligned with map team. Not handling interaction input.

## SubFeature/component (optional)
- Generic entity for station
- Design of each other station and characteristics

# **Dependencies**
- #4 
- Item Class (Ticket pending upload)

# **Milestones**
- [ ] Set up Entity and related Components for Item intake and output (Aug. 16)
- [ ] Work on documentation for Wiki (Aug. 20)
- [ ] EventHandler and EventListener sections for component calls on specific stations.  Spawn stations in set position (Aug. 23)
- [ ] Test Entity Class

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Stations)

# **Members**
- Zach Adams (@AdamsZach)
- Andi Hamilton-Hart (@StrayIntellectual)
- Nicholas Nucifora (@nuciforan0)
- Callan Vragalis (@silagarv)
- Hayden Elliot (@Hayden-Elliott)

**Comment by JTrenerry** [comment]
Would like the milestones a bit more layed out, what components will be done on aug 16 and what are there purpose. Dependencies can also be linked to other feature tickets when they are made by doing # then the number / name, they could also be check boxes for more information on when stuff is done.

**Comment by CalvinJohn99** [comment]
Hi from team 2, we made the trigger for start cooking/chopping depending on the station in StationItemHandlerComponent.java as discussed with one of your team memebers (on our branch as of now, will be merged to main at some point). Please let me know if you have any issues or concerns.

**Comment by CalvinJohn99** [comment]
We're planning to improve the game logic to make it more of a game. To do this we're thinking of the stations that can cook food items to have a flag for whether it's "hot" or "warm" or "normal" to decrease or increase cooking times. You may need separate subclasses for such logic. Perhaps something to do for next sprint. The logic we suggest is, as soon as something finishes cooking, the state is set to "Hot" as the station remain idle or has no activity. This state gets set to "normal" or "warm" depending on time.

**Comment by Hayden-Elliott** [comment]
I agree that this kind of functionality is best to consider next sprint. First I have heard of it and is a bit late to integrate into our tickets now.

**Comment by CalvinJohn99** [comment]
Yes, yes. For next sprint.
