### ISSUE TITLE
Setup testing structure of inventory system

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#30]
# **Description**
**Task:** Setup testing structure of inventory system.
**Feature:** [Team 1] Inventory system #6 

Will implement the base structure and function stubs of the testing component of the inventory system. 
 
# **Dependencies**
- [ ] Inventory feature branch creation (#28)
- [ ] Setter and getter inventory methods (#xx)
- [ ] Complex inter-inventory methods (#29)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Create base structure for testing functionality(Aug. 19)
- [x] Step 2 Consider what broad aspects need to be tested (Aug. 20)
- [x] Step 3 Create function stubs for each test/section of testing (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- ...
 
# **Member**
- Anna Stevens (@goanna5)
