### ISSUE TITLE
Finalising sprint 2 changes (Bench/Collisions) and Improving map design & adding different layouts

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#300]
# **Description**
In this sprint, we are going to start by working on fixing the bench collisions as well as refactoring the bench class (creating Bench Generator) to make the spawning of the bench tiles easier. We are also working on changing the background of the game area based on the time of day. This means it will go from day to night by having the background progressively change.  In addition, we are also working on creating multiple maps for the different levels. During the sprint we will also try to work on improving the UI of the game (including stats and other components), as well as improve the layout of map. In the first half of the sprint we will be focusing on polishing our changes from the previous sprint (Bench/collisions). 

## SubFeature/component (optional)
#359 - Improving Map design
#309 - Adding different Map layouts

# **Dependencies**
No dependencies

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint. The dates might vary based on how much work can be done during the mid-sem break.
- [ ] Improve bench code layout and finalise collisions (21st Sept)
- [ ] Multiple map layouts (Oct 1)
- [ ] Integrate into different levels(Oct 2)
- [ ] Change game background (29 Sept)
- [ ] Final UI changes to the game and improve map design (30 Sept)

**Completion Deadline:** 2nd October 

# **Documentation**
[Map Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)
[Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
[Game Screen Background](https://github.com/UQcsse3200/2024-studio-3/wiki/Main-Game-Screen-Background)

# **Members**
- Danh Dinh (@danhdinh98)
- Sarah Abdulkhalek (@Sarahkhalek)
- Alex Macnamara (@amacn13)
- Alex Ong (@ATOApplett)
- Reza Panday (@pineapple11111)
- Rakshit Singh (@Rakshit31773 )

**Comment by Sarahkhalek** [comment]
Closed by #447
