### ISSUE TITLE
DishFactory fix for getRecipe

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#303]
# **Description**
**Task:** DishFactory fix for getRecipe
**Feature:** 
Current getRecipe() function in DishFactory does not perform required functionality of returning all possible recipes from given recipes. 

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Determine exact current functionality (Sep. 18)
- [ ] Write fix (Sep 18)
- [ ] Test fix (Sep. 18)

**Completion Deadline:** Sep. 18
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- e.g. Serene McCormack(@serenemccormack) (serene_mccormack
