### ISSUE TITLE
Create load game menu which links to main and pause menu (Sep. 21)

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#304]
# **Description**
**Task:** Create load game menu which links to main and pause menu (#304).
**Feature:** Save/load game(#284)

The load game menu will be important to picking which save to pick and load for the players. There will be 6 defined saves in a 2x3 formation which will initially be called save 1-6. 

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create basic LoadGameDisplay (Sep 17th)
- [x] Create linking between main menu and load game and vise versa (Sep 19th)
- [x] Allows saves to be pressable and to cause an event to load the game (Sep 21th)

**Completion Deadline:**  Sep 21
 
# **Documentation**
None
 
# **Member**
- Jackson Van Duikeren (@aridspace10)
