### ISSUE TITLE
Location Backstory 

### ISSUE THREAD

**Issue by LAKSHAYATREJA** [UQcsse3200/2024-studio-3#305]
# **Description**
**Task:** Location Cut-scene
**Feature:** [Feature which this tasks contributes to implementing](#2) Game Backstory

The cut-scene will describe about the location , when a backstory is presented at the starting of the game .The elaboration of location where 
## **Example (optional)**
Like every game start at a particular location from which it is carried forward like GTA is started at a bank proceeding with a robbery .
-It will give a brief Background for the game story to the player.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Describing the location(Aug. 19)
- [x] Creating atlas  (Aug. 22)
- [x] Create functional Cut-Scenes  (Aug. 24)

 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@LAKSHAYATREJA ) (
