### ISSUE TITLE
Customer Backstory

### ISSUE THREAD

**Issue by shravya132** [UQcsse3200/2024-studio-3#307]
# **Description**
**Task:** Customer Backstory (#307).
**Feature:** Backstory Cutscenes (#285 )

This task focuses on creating a detailed customer backstory that will be integrated into the game's storyline. It will provide insight into the customer's preferences and past experiences. This backstory will be reflected through various cutscenes, dialogue, and interactions within the game. 

# **Dependencies**
- [x] Dialogue script for the backstory cutscenes is written. 
- [x] Draft the customer backstory and key narrative points.
- [x] Implement dialogue triggers for backstory cutscenes.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create customer/character sprites for backstory cutscene.

**Completion Deadline:** Oct. 1
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Shravya (@shravya132) (Shravya Chandrasekar)
