### ISSUE TITLE
Customer Aggravation when Order/Food is Not Received

### ISSUE THREAD

**Issue by baulch-m** [UQcsse3200/2024-studio-3#308]
# **Description**
**TICKET IS WIP**
This feature adds an extra level of depth to the gameplay by making sure the player feeds the customers on time. If not, the customer may or may not (depending on the type/animal) interfere with the player's working space, punishing them for their incompetence. This process will be triggered when the timer on an order runs out, and the entity will have its walking path redirected into the kitchen, where it will act as an obstacle for a few seconds. The customer's sprite will also change to reflect this behaviour (i.e. add a red hue/filter to signify anger idk)

# **Dependencies**

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
- [ ] create a trigger for the anger event
- [ ] make "angry" sprites for each customer 
- [ ] configure wander path for the event

**Completion Deadline:** Oct 2

# **Members**
- Marcus Baulch (@baulch-m)
- Sui Lei
