### ISSUE TITLE
Add new map layouts per level.

### ISSUE THREAD

**Issue by pineapple11111** [UQcsse3200/2024-studio-3#309]
# **Description**
This is a sub-feature of #300. It consists of loading in a different map each day in the game. Every level should have a new map layout. This means that different maps will need to be designed as well as functionality regarding loading in the different maps will need to be implemented and tested. This requires a file reader and using text files. This will also require the BenchGenerator class to move lengthy bench spawning code out of ForestGameArea (and subsequent future areas)

# **Milestones**
- [x] Designing different map layouts based on which stations need to be included on the day (Sept 30)
- [x] Refactoring the bench class to be more efficient  (Sept 30)
- [x] Creating a reader for different text files (Oct 2)
- [x] Spawn tiles based on the file provided (Oct 2)

**Completion Deadline:** Oct 2

# **Documentation**
- [Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)

# **Members**
- Danh Dinh (@danhdinh98)
- Sarah Abdulkhalek (@Sarahkhalek)
- Alex Macnamara (@amacn13)
- Alex Ong (@ATOApplett)
- Reza Panday (@pineapple11111)
- Rakshit Singh (@Rakshit31773 )

**Comment by Sarahkhalek** [comment]
Closed by #447
