### ISSUE TITLE
Testing the setter and getter functions of the inventory system

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#31]
# **Description**
**Task:** Testing the setter and getter functions of the inventory system.
**Feature:** [Team 1] Inventory system(#6)

Create comprehensive tests of the getter and setter functions of the inventory class.

# **Dependencies**
- [x] Setup testing structure of inventory system (#30)
- [x] Inventory feature branch creation (#28)
- [x] Setter and getter inventory methods (#33)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Ideate how to test getter and setter methods (Aug. 19)
- [x] Step 2 Write tests for getter methods (Aug. 20)
- [x] Step 3 Write tests for setter methods (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Inventory System Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/Inventory-System)
 
# **Member**
- Anna Stevens (@goanna5)
