### ISSUE TITLE
Plate Game Cycle and Integration to Meal Creation

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#312]
# **Description**

Addition of the PlateComponent into the game cycle will mean another task for the Player to manage -- the processing of used plates to become clean (through a DishwasherStationComponent) and the integration of the PlateComponent into the requirements for a MealComponent to be created on a StationMealComponent. A Meal will now require a clean plate to be in the station inventory before a meal can be created. Additionally, the timed recycling of plates after customer use will be implemented to round out the plate cycle.

## SubFeature/component
- [x] DishwasherStationComponent: will have an inventory of x clean plates at the start of the game, and will be used to process used plates.
- [x] PlateComponent integration into meal creation: the automatic meal creation will now require a PlateComponent in the station inventory to create a meal.
- [ ] Recycling of plates back into the kitchen environment: the plate used for customer service of a meal will be recycling back onto a station (TBD) a certain amount of time after the meal is served. The player will then have to bring it to the DishwasherStation for processing. 

# **Dependencies**
N/A

# **Milestones**
- [x] Implement DishwasherStationComponent (Oct 18)
- [x] Test DishwasherStationComponent (Oct 18)
- [x] Implement PlateComponent integration (Oct 18)
- [x] Test PlateComponent integration (Oct 18)
- [x] Decide on the number of plates required per day of the game (Oct 18)
- [ ] Decide on the time taken for plates to be recycled (Oct 18)
- [ ] Implement plate recycling (Oct 18)
- [ ] Test plate recycling (Oct 18)

**Completion Deadline:** Oct 18

# **Extras**
- [ ] Alerts when a used plate is placed back in the kitchen

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
- e.g. Serene McCormack(@serenemccormack) (serene_mccormack)
