### ISSUE TITLE
Modifying the meal sprites on the dockets

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#313]
# **Description**
**Task:** Modifying the meal sprites on the dockets (#).
**Feature:** #

Modifying the docket images to include the new meal sprite images created last sprint.

# **Dependencies**

- [ ] Order system (#xx)
- [ ] Dependency 2 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Anna Stevens (@goanna5)
