### ISSUE TITLE
Backstory Cutscenes Storyboard

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#315]
# **Description**
**Task:** Backstory Cutscenes Storyboard(#3).
**Feature:** Backstory Cutscenes (#285)

Creating the storyboard for which the intro image sprites will be rendered according to. Each frame will be a different image rendered on screen. 
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Frames for each image sprite**: In the style of 'Papa's' games: 
<img width="641" alt="Screenshot 2024-09-19 at 3 42 51 pm" src="https://github.com/user-attachments/assets/2246d88b-1738-414a-93be-b0fa8f379274">
<img width="533" alt="Screenshot 2024-09-19 at 3 42 46 pm" src="https://github.com/user-attachments/assets/ff16e891-a669-44e2-a748-dfdb1a4c2fbf">
<img width="559" alt="Screenshot 2024-09-19 at 3 42 43 pm" src="https://github.com/user-attachments/assets/c5f0112d-2b0c-4bab-8959-e13077bb5939">

# **Dependencies**
None. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Location/ world backstory frames (Sep. 21)
- [x] Player backstory frames (Sep. 21)
- [x] Customer backstory frames (Sep 21.)
 
**Completion Deadline:** Sep. 21

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tia (tia-w) (teeyahisswag123)
