### ISSUE TITLE
Create a mapLayout class to read text files and load map

### ISSUE THREAD

**Issue by pineapple11111** [UQcsse3200/2024-studio-3#317]
**Description**
**Task:** [Create a mapLayout class to read text files and load map]
**Feature:** #300 #309 

This task is related to creating a class that can read text files containing information about the tiles of the map. It consist of reading letters and being able to create the correct map based on that text file. A class and different functions will need to be created for this. 

# **Dependencies**
- No dependencies for the reader but in order to load in all maps and complete this it depends on finish the design of all maps and the text files #301 #348. This also depends on the stations team to finish implementing their stations.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Creating a class for the layout (Sept 24)
- [ ] Creating a function that is able to load/read a text file (Sept 28)
- [ ] Handle different letters/tiles (Sept 30)
- [ ] Load the map in the game area/spawn elements (Oct 1)
- [ ] Implement different maps for each day/level (Oct 2)
- [ ] Test the code written (Oct 3)
 
**Completion Deadline:** Oct 3

# **Documentation**
-  [Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
 
# **Member**
- @Sarahkhalek 
- @ATOApplett

**Comment by pineapple11111** [comment]
added BenchLayout class for this, possibly going to add other map layout type classes to clean up ForestGameArea a bit more I think

**Comment by Sarahkhalek** [comment]
Closed by #447
