### ISSUE TITLE
Testing the StationMealComponent

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#318]
# **Description**
**Task:** Testing the StationMealComponent (#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Testing the StationMealComponent that was developed in the last sprint by Team 1. 
// note that this task ticket is still in progress
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Anna Stevens (@goanna5)
- Sourav (@Sourav-RC)
