### ISSUE TITLE
Creating UML Diagrams

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#32]
# **Description**
**Task:** Creating UML Diagram.
**Feature:** [Team 1] Inventory system (#6)

The aim is to create a UML diagram that visualises the design and architecture of the inventory system.

# **Dependencies**
- [x] Initialise a basic inventory system component with setter and getter methods (#33)
- [x] Extending inventory component to player inventory component (#44)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 - Finalise key concepts in designing and developing inventory system (Aug. 19)
- [x] Step 2 - Creating a list of used classes, relationships, methods, etc (Aug. 20)
- [x] Step 3 - Connecting the elements and establishing relationships, constraints, etc (Aug. 23)
- [x] Step 4 - Finalise and validate the UML with code (Aug. 23)
- [x] Step 5 - Publish to Wiki (Aug. 29) 
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Inventory System Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/Inventory-System)
 
# **Member**
- Bao Huynh (@bhuynh3004)
