### ISSUE TITLE
Create recipe shortcuts

### ISSUE THREAD

**Issue by AdamsZach** [UQcsse3200/2024-studio-3#324]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

The purporse of this task is to create recipe shortcuts that the player can type in. This will spawn the desired recipe into the players inventory which will be used for debugging and testing purposes throughout the development of the game. 
 
## **Example**
- **Servery Station**: If the servery station needs to be tested, the player can quickly spawn the recipe in using the command, for example if the order ticket requires a banana split, the user can type in ":get bananasplit", for fast testing functionality. 

# **Dependencies**
This task has no dependencies. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Recognise the command (Sep. 23)
- [x] Add recipe to inventory based off the command (Sep. 27)
- [x] Write tests (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zach Adams (@AdamsZach)
- Nicholas Nucifora (@nuciforan0)

**Comment by silagarv** [comment]
Close because done.
