### ISSUE TITLE
Creating station timers for item cooking and get item updating working with the timers.

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#328]
# **Description**
**Task:** [Station Cleanup](#)
This task aims to modify item cooking functionality to be able to use timers for item cooking/chopping. This includes starting, pausing, and stopping cooking. These timers will also be in some way integrated with the stations to allow for a station UI to be created which shows the cooking progress of the item.
 
# **Dependencies**
This task has no dependencies and may the station UI creation depends on this task.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Modify current item cooking functionality and create a plan for a new cooking system (Sep. 21)
- [x] Create a timer component and complete tests for it (Sep. 24)
- [x] Integrate the timer component within the cooking process so that the (Sep. 25)
- [x] modify Item factory to remove the texture render component for items and add the get texture path to each of the items (Sep. 25) (will be done in team5 branch)
- [x] Ensure complete integration and create methods to allow for the timer progress to be accessed for UI purposes (Sep. 26)
- [x] Merge main into branch and ensure it is all working (Sep. 26)
 
# **Documentation**
- Add documentation to the items system
- Add documentation to get accesss to the timer completion
 
# **Member**
- Callan Vragalis (@silagarv)
