### ISSUE TITLE
Initialise Inventory Component

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#33]
# **Description**
**Task:** Initialise Inventory Component
**Feature:** [Team 1] Inventory System

Modify the existing InventoryComponent class provided by the game engine by initialising its fields in the constructor and adding getter/setter methods for the fields. The fields that will be included in the Inventory component include: 
Items: Array<item_type>, an array that stores the item objects for this inventory component
Size: int, the maximum number of items that can be stored in the inventory 
There will also be a isFull() method used to determine if the inventory has reached its maximum number of items it can hold
 
# **Dependencies**

- [x] Create Feature Branch (#28)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finish constructor (Aug. 20)
- [x] Finish getter methods (Aug. 21)
- [x] Finish setter methods (Aug. 22)
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Main description of feature](../wiki/Inventory)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Benjamin (@benjamin-wang1)
