### ISSUE TITLE
Combination Option for Mixing Station

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#332]
# **Description**
**Task:** Adding combination action to mixing station
**Feature:** #276 

Implement a new PlayerAction that only works on mixing station that attempts to create a meal with current ItemComponents in station. Start with biggest recipes in terms of ingredients and move down. Current button for consideration for button is 'R'. Implementation will involve changes to current interaction structure and addition of event listeners and triggers.
 
## **Example (optional)**
- **Create a Banana Split**: Player has dropped each necessary item for recipe into station. Then player uses assigned button to begin a check on the items in station checking for potential creation of a meal.

# **Dependencies**
Should be no dependencies, building on current infrastructure, may be some delays in meal creation component from team1. No specific task ticket as of writing.
Feature ticket: #312 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add button to PlayerActions and interaction events (23rd. Sept)
- [x] Assign function calls to handleInteraction segment in mixing station component  (24th. Sept)
- [x] Add to tutorial (28th. Sept)
- [x] Add testing to relevant meal components (28th. Sept)
- [x] Wiki updates for new uses (28th. Sept)
 
**Completion Deadline:** Sept. 28th

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Hayden (@Hayden-Elliott ) (Hayden Elliott)

**Comment by silagarv** [comment]
Merged so closing ticekt
