### ISSUE TITLE
Support for Player Selection of Item to take from Mixing Station with a new button

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#333]
# **Description**
**Task:** Function in meal component to rotate inventory to update StationInventory display and give player option of which item to take
**Feature:** #276

Add functionality to make changes to the general mixing bench to reorganise station inventory such that player can select an item to take from station using visual reference from UI display
 
## **Example (optional)**
- **Take Banana**: Station is storing a strawberry, strawberry and banana. Player wants to take the banana, interact with station to rotate the banana to first position in inventory, so that if player has inventory they can take item in first position which is now banana.

# **Dependencies**
Should be all good
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] PlayerAction updates and listeners (Sept. 23rd)
- [x] Meal component functionality to update inventory (Sept. 28th) 
- [x] Wiki and testing updates (Sept. 28th)
- [x] Tutorial update (Sept. 28th)
 
**Completion Deadline:** Sept. 28th

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by silagarv** [comment]
Merged so closing ticket
