### ISSUE TITLE
Team 1 - Station interaction visualisation

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#334]
# **Description**
It is currently difficult to visualise what is happening in the game when interacting with stations as you cannot see what items are being held in the stations. 
Inventory hover displays will be added to each station to show the items they hold as icons above the station. Additionally, when chopping and cooking functionality is finalised, a progress bar will be added stations to show how chopped/cooked the item is.
For the mixing station, the inventory hover display will be able to rotate its items upon pressing a button to choose which item to take out of the mixing station (the item to remove will be highlighted. This will work like a stack: LIFO).

SPRINT 4:
Extend visualisation to include pop-up icons that show when you can interact with a station, and what button to press, so players don't have to memorise keybinds.

# **Dependencies**

InventoryComponent required to store items in stations (#6)
Station interaction and functionality required for cooking, chopping and combining ingredients into a meal 
Station inventory rotation functionality required to integrate hover display into mixing station (#333)
Keyboard input UI requires station interaction to be fixed from last sprint (##)

# **Milestones**
- [x] Create inventory hover display (Sep. 20)
- [x] Write up tests for inventory display (Sep. 27)
- [x] Write up tests for inventory hover display (Sep. 27)
- [x] Write up documentation for inventory hover display (Sep. 27)
- [x] Integrate inventory hover display into stations and add highlight/rotate functionality for the mixing station's display (TBD)
- [x] Create progress bar component (TBD)
- [x] Write up tests for progress bar component (TBD)
- [x] Write up documentation for progress bar component (TBD)
- [x] Add keyboard input UI functionality (Oct. 11)
- [x] Write up documentation for keyboard input UI (Oct17)

**Completion Deadline:** Oct 17. 

# **Documentation**
- [Station Visualisation](../wiki/Station-Inventory-and-Visualisation)
- [Stations](../wiki/General-Stations-Overview)

# **Members**
- Anna Stevens (@goanna5)
- Sourav Roy Chowdhury (@Sourav-RC)
- Benjamin Wang (@benjamin-wang1)
