### ISSUE TITLE
Creating Moral Decision Screens 

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#336]
# **Description**

**Task:** Creating Moral Decision Screens (#336)
**Feature:** Moral System Extended (#335)

This task focuses on creating detailed moral decision screens that will be integrated into the gameplay, as well as the game’s storyline. It will provide the player with different decisions each day, and once the player makes a decision (pressing the ‘yes’ or ‘no’ button), the consequences of their decision will be shown the next day.

## **Example (optional)**

- Day 3, the rhino boss wants to poison the health inspector during Day 4’s cycle.
- If the player presses ‘yes’, the rhino boss will give dialogue approving of the player’s choice. In Day 4’s cycle, once the health inspector collects their food they will become sick and die.
- If the player presses ‘no’, the rhino boss will give dialogue being disappointed of the player’s choice. In Day 4’s cycle, the health inspector will collect their food and leave the resturant normally.

# **Dependencies**

- [x]  Character art
- [x]  Dialogue script for the backstory cutscenes is written

# **Milestones**

- [x]  Storyboard each day’s moral screen (Sept 28)
- [x]  Create art for each day (Oct 1)
- [x]  Implement art for day 1 (Oct 2)
- [x]  Implement art for day 2 (Oct 2)
- [x]  Implement art for day 3 (Oct 2)
- [x]  Implement art for day 4 (Oct 2)

**Completion Deadline:** Oct 2

# **Documentation**

- [Storyline](https://github.com/UQcsse3200/2024-studio-3/wiki/Storyline)

# **Member**

- Amber (@ambs02)
