### ISSUE TITLE
Freezing the player when interacting with a station 

### ISSUE THREAD

**Issue by bhavyamalik1** [UQcsse3200/2024-studio-3#34]
# **Description**
**Task:**  Freezing the player when interacting with a station.
**Feature:**  Player Action and Interaction (#4)

This task involves freezing the player's movement when interacting with a station. The player will become unfrozen on one of the following conditions:
-a specified item is added to the player's inventory 
-the player is at the station for a particular amount of time

For now, this feature will be implemented with a timer (using a get_time function called on the specific station) until the stations and inventory teams build the functionality for what item is received at each station. 

## **Example**.
When the player is at the cutting table, the player's movement will remain frozen until they receive the chopped version of the food into their inventory.

# **Dependencies**

- [ ] Need to know the different type of stations and what they output (#3)
- [ ] Need to know how to interact with the inventory to check if an item is in it (#30)

# **Milestones**

- [ ]  Get the outputs of the stations (Aug. 26)
- [ ]  Make the function to freeze the player (Aug. 28)
- [ ] Documentation updated on the wiki (Aug. 30)

**Completion Deadline:** Aug. 28

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Bhavya Malik (@bhavyamalik1 )
