### ISSUE TITLE
Resize the map 

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#344]
# **Description**
**Task:** Resizing the map appropriately for the orders to fit
**Feature:** #300 

This consists of changing the dimensions of the map to create more space for the orders and a background. This consists of having a smaller area meaning fewer blue and orange tiles. This would also require us to center the map as well as redo the borders. 

# **Dependencies**
No dependencies for this task

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide on the size of the new map (Sept 23)
- [x] Resize and change the camera to center the map (Sept 23)
- [x] Redoing the border more efficiently and outlining the new size of the map (Sept 23)
 
**Completion Deadline:** Sept 23
 
# **Documentation**
[Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
 
 
# **Member**
- @Sarahkhalek

**Comment by Sarahkhalek** [comment]
Ckosed by #377
