### ISSUE TITLE
Designing the background for the game area 

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#345]
# **Description**
**Task:** Designing the background for the game area and changing based on time of day
**Feature:** #300 #358 

This tasks consists of using the background art designed by another team from the studio and using it as a background for the game area to make the game look nicer but also trying to change it based on the time of day. 
 
## **Example (optional)**
- **Morning**:  Sunrise
- **Afternoon**: Blue skies
- **Night**: Dark 

# **Dependencies**
To fully complete this task #344 needs to be completed since the background is based on how the new game area looks.

# **Milestones**
List of steps that need to be completed for this task
- [ ] Add a background to the game area instead of just a colour (Sept 22)
- [ ] Pick the background image/images wanted (Sept 22)
- [ ] Decide on what elements in the background would change throughout the day (color scheme) (Sept 22)
- [ ] Add different images for each time of day
- [ ] Implementing it in the code
- [ ] Testing it 
 
**Completion Deadline:** Sept 22
 
# **Documentation**
[Game screen Background](https://github.com/UQcsse3200/2024-studio-3/wiki/Main-Game-Screen-Background)
 
# **Member**
- @amacn13

**Comment by Sarahkhalek** [comment]
Closed by #377
