### ISSUE TITLE
Restructuring the tickets, making the tickets horizontal and making them smaller

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#346]
# **Description**
**Task:** Restructuring the tickets, making the tickets horizontal and making them smaller
**Feature:** #300 #359 

This feature consists of restructuring the order tickets to make them better fit on the game area map. This would allow for more space and better visibility when playing and a better outcome visually.

# **Dependencies**
No dependencies

# **Milestones**
List of steps that need to be completed for this task.
- [x] Making the tickets smaller (Sept 22)
- [x] Moving the tickets to the right all along the map (Sept 24)
- [x] Changing the rope at the top (Sept 25)
- [x] Making them more horizontal than vertical (Sept 29)
- [ ] Check if any testing is needed based on previous testing of the order system (Sept 30)
 
**Completion Deadline:** Sept 30

 
# **Documentation**
- [Map layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
 
# **Member**
- @Rakshit31773

**Comment by Sarahkhalek** [comment]
Closed by #447
