### ISSUE TITLE
UI components (Time left, cash...)  

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#347]
# **Description**
**Task:** Improve the UI components of the map
**Feature:** #300 #359 

This task is about improving the UI components on the map. This includes the time, the text on the left upper corner of the map like time left and other text. Make the design better and replace with pngs
 

# **Dependencies**
No dependencies

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Replace the text (Oct 2)
- [ ] Choose pngs for different elements and replace on the game area (Oct 2)
- [ ] Implement them into the game area (Oct 2)
 
**Completion Deadline:** Oct 2

# **Documentation**
- [Map Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)
 
# **Member**
- @Rakshit31773

**Comment by Sarahkhalek** [comment]
Closed by #447
