### ISSUE TITLE
Create text files based on map layouts

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#348]
# **Description**
**Task:** [Create text files based on map layouts](#3).
**Feature:** #300 #309 

This task consists of creating different text files based on the different maps for each level in order to load in the correct map. 

# **Dependencies**
- [x] Designing different map layouts (#301) 
- [x] Map layout/reader (#309)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide on letters for tiles (Sept 29)
- [x] Create a text file that can be read by our file reader (Oct 1)
- [x] Create all text files for each level and make sure they are loaded properly (Oct 2)
 
**Completion Deadline:** Oct 2
 
# **Documentation**
- [Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)

# **Member**
- @danhdinh98

**Comment by Sarahkhalek** [comment]
Closed by #447
