### ISSUE TITLE
JSON File

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#35]
# **Description**
**Task:** [JSON creation and loading file into factory](#3).
**Feature:** [Food Recipe](#9 )

Create a JSON file that includes all the recipe, loading into the Factory and create the cooking config that include all the variables inside the JSON file

# **Dependencies**
- Need to give recipe.json to the item team so they can handle the recipe and ingredients (#5)
- Create getter method to get recipe so #36 and the order team can use it

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create JSON file and add recipe into that file (Aug. 23)
- [x] Load the file into Factory - create DishFactory (Aug. 23)
- [x] Save data into the Config file (Aug. 23)
- [x] Create two different Config.java to handle the json file (SingleStationRecipeConfig and MultiStationRecipeConfig) since not all recipes have the same stations
- [x] Create getRecipe() function to get recipe when giving ingredients (Aug. 25)
- [x] Testing - Create JUnit test to ensure the recipe.json can be loaded and parsed into CookingConfig.java, allowing people to use the variables (Aug. 24)
- [x] Testing - Create JUnit test to ensure desired recipe is returned when ingredients are given (including edge cases where the ingredient is not associated with the recipe) (Aug. 25)
 
**Completion Deadline:** Aug. 28

# **Member**
- Joanna Wang @Joanna-Wang105

**Comment by Joanna-Wang105** [comment]
Task completed
