### ISSUE TITLE
Create Docket Triggers

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#350]
# **Description**
**Task:** Create Order Triggers
**Feature:** [Order System](#113 )

Implment triggers to create a docket. Each meal will have it's own trigger. These can be used by customers to create their prefered meal.

# **Dependencies**
- [x] (#8 ) is needed to create a docket
 
# **Milestones**
- [x] Create triggers (Sep. 25)
- [x] Test (Sep. 27)
- [x] Documentation and update Wiki (Sep. 29)
 
**Completion Deadline:** Sep. 29
 
# **Documentation**
- [Ordering System Overview](https://github.com/UQcsse3200/2024-studio-3/wiki/Ordering-System-Overview)
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
- Aadya (@abhat0 ) (Aadya Bhatia)
