### ISSUE TITLE
Team 2 Recipe Card

### ISSUE THREAD

**Issue by Ashom2** [UQcsse3200/2024-studio-3#352]
# **Description**
When the player approaches a location on the map, the game will pause and a UI popup illustrating how to create the various recipes will appear. This is to help players if they forget how to make a recipe.

# **Milestones**
- [x] Pause functionality with keybind (Sep. 29)
- [x] Create illustration (Oct. 3)

**Completion Deadline:** Oct. 3

# **Extras (optional)**
- [ ] Open recipe card when approached by player

# **Members**
- Joanna (@Joanna-Wang105)
- Calvin (@CalvinJohn99 )
- Willem (@willembor )
- Alex (@Ashom2 )
- Ashwin (@AshHarikrishna )
- Daleela (@daleelakhairil )
