### ISSUE TITLE
Fixing tutorial of the game

### ISSUE THREAD

**Issue by LAKSHAYATREJA** [UQcsse3200/2024-studio-3#353]
# **Description**
**Task:** fixing  tutorial and testing and remove Create Order Button
**Feature:** #146 

The tutorial for the game focuses on movement ,pick up items and order system .To ensure proper movement of tutorial step wise and testing it .
 
## **Example (optional)**
- when W/A/S/D is pressed then tutorial should move forward 
- remove Create Order Button
# **Dependencies**
- [x] #146 
- [x] #221 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fixing Movement on screen and pick up item  (Oct .2)
- [x] Fixing dependant on Create Order button to finish tutorial (Oct. 2)
- [x] Fixing game crashes when clicking 'Enter' at the end of game (Oct. 2)
- [x] Remove Create Order Button from TutorialScreen and MainGameScreen (Oct. 2)
- [x] Write tests for all tutorial related stuffs(Oct. 2)

 
# **Member**
- Name (@LAKSHAYATREJA ) (Lakshay Atreja)
- Airyl Harridzuan Bin Suaidi (@airylsuaidi)
