### ISSUE TITLE
Create simple load game functionality (stores money, level, moral status) (Sep. 23)

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#354]
# **Description**
**Task:** Create simple load game functionality (stores money, level, moral status) (#354).
**Feature:** [Feature which this tasks contributes to implementing](#284)

To begin, a simple load game functionality will be used to store the money, day and moral status within each save. 

# **Dependencies**
- Load game menu works to test #304 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create game state class to store internal data (Sep 24)
- [x] Create a save/load service wish will save data (Sep 25)
- [x] Add ability to load data from save/load service (Sep 27)
- [x] Integrate use of save service into main menu/ pause menu (Sep 29)
- [x] Integrate use of load service into main menu/ pause menu (Oct 1)
 
**Completion Deadline:** Oct 1
 
# **Documentation**
None
 
# **Member**
- Jackson Van Duikeren (@aridspace10)
