### ISSUE TITLE
Main Game Screen Background Update

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#358]
# **Description**
Update background of the main game screen from the solid yellow colour to an image showing the world outside the restaurant. Background should change over the course of the "day" to reflect time progression (the day night cycle)

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples**
- The game screen should initially load with a background showing the day time view of the outside world. As the level progresses, the background gradually changes to reflect the sunset/night time view of the restaurant

# **Dependencies**
- Setting background image and design (#345)
- Determining length of day from number of customers / level (and consequent timing of day progressions)
- Relies on restructured map layout (#344) for specific dimensions / layout of artwork

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Complete background artworks (Sep 26)
- [x] Background Image Setter (Sept 27)
- [x] Determine timings for each level (Sept 29)
- [x] Finalise background artworks after map redesign (Sept 29)
- [x] Implement timings into core game (Sept 1)
- [x] Finalise Wiki (Sept 1)
- [x] Testing (Sept 2)

**Completion Deadline:** Oct. 3

# **Extras (optional)**
- [x] Add unique backgrounds for different days depending on the level (i.e. for the final birthday party day, include decorations outside the restaurant) (Not completed due to memory and time restraints - see SAF)

# **Documentation**

# **Members**
- Alex M (@amacn13)

**Comment by Sarahkhalek** [comment]
This issue was closed by #377
