### ISSUE TITLE
Improving map design

### ISSUE THREAD

**Issue by danhdinh98** [UQcsse3200/2024-studio-3#359]
# **Description**
This is a sub feature of #300. It is related to redesigning the map in terms of layout. This is related to resizing the map, working on the dockets, redoing the border as well as making sure that all the items are spawned in the new map correctly.  Currently, the way dockets are spawned are confusing for the player and hard to read as they spawn on the left side of the screen. This can be improved by pushing dockets to the left from the right side of the screen as opposed to pushing dockets from left to right when a new docket is spawned. This will be actioned upon by moving the main docket to the far right corner of the screen and allowing dockets to be pushed further to the sides of the map.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Resizing the map and improving the border creation (Sept 29)
- [x] Improving the walls (Sept 29)
- [x] Improve docket spawning functionality and design (Sept 29)
- [ ] Improve UI components (Time, health...) IF we have time

**Completion Deadline:** Sept 29

# **Documentation**
- [Map design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)
# **Members**
- Danh Dinh (@danhdinh98)
- Sarah Abdulkhalek (@Sarahkhalek)
- Alex Macnamara (@amacn13)
- Alex Ong (@ATOApplett)
- Reza Panday (@pineapple11111)
- Rakshit Singh (@Rakshit31773 )

**Comment by Sarahkhalek** [comment]
Closed by #447
