### ISSUE TITLE
Cooking component class creation

### ISSUE THREAD

**Issue by willembor** [UQcsse3200/2024-studio-3#36]
# **Description**
**Task:** Cooking Component Class
**Feature:** #9 

The cooking component class will handle changing the state of an item and transforming it to a new item after being passed through a station. This will include constructors, simple variables and functions to handle changing the state of an item etc. Additionally, this class will inherit some functions from the station branch to assist in this implementation.
 
## **Example**
Some of the methods and variables will be;
- **create**: 
- **update**: 

# **Dependencies**
- [x] Need to use item handling component to handle items (#3 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create basic constructors (Aug. 25)
- [x] Implement Item handling component (Aug. 26)
- [x] Create functions to change state of item (Aug 27)
- [x] Implement Testing (Aug. 27)
- [x] Documentation Updated (Aug. 27)
 
**Completion Deadline:** Aug. 27

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Willem Bor @willembor
- Alexander Shomer @Ashom2

**Comment by nuciforan0** [comment]
There seems to be quite an overlap with the CookingComponent and the CookIngredientComponent, could y'all rectify this by merging these functions so we have one function for handling cooking components? Doesn't seem like the cookingComponent is being used anyways.
