### ISSUE TITLE
Extending and slightly reworking the Level System

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#360]
# **Description**

With the game now being more planned out in terms of the story and overall game (i.e. we now actually have a plan), the `LevelService` needs to have new functionality implemented in order to make tracking of the moral decisions a bit easier. The number of days needs to be changed in order to reflect the changes to the story, and also refinements to the `LevelComponent` so that customer spawn can be fine tuned based off of preferences.

# **Dependencies**

Level System (#106)

# **Milestones**

- [ ] Rework LevelService (Oct. 1)
- [ ] Extend LevelService (Oct. 1)
- [ ] Review LevelComponent (Oct. 1)
- [ ] (OPTIONAL) Rework LevelComponent (Oct. 1)
- [ ] Update documentation (Oct. 2)

**Completion Deadline:** Oct. 2

# **Documentation**
- ...

# **Members**
- Michael (@IWontCauseAFuss) idontwanttocauseafuss

**Comment by JTrenerry** [comment]
Is this a feature or just a task?
