### ISSUE TITLE
LevelService Updating

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#361]
# **Description**
**Task:** [LevelService Updating](#this).
**Feature:** [Extending and slightly reworking the Level System](#360) 

With it being decided that the game will only have five days, the `LevelService` needs to be updated to reflect that. Additionally, some variables for tracking moral decisions can be implemented in order to make ending checks a bit easier - and just in case no one has figured it out yet. This can include some methods for checking what ending will be achieved. 

# **Dependencies**

- [x] Level System (#106)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Rework level switching methods (Oct. 1)
- [x] Add variables for tracking moral choices (Oct. 1)
- [x] Add methods for checking total moral choices (Oct. 1)
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- ...
 
# **Member**
- Michael (@IWontCauseAFuss) idontwanttocauseafuss
