### ISSUE TITLE
Implement Rage Mode Into the Cooking / Chopping process

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#362]
# **Description**
**Task:** Rage mode task
**Feature:** Upgrades / Station Updates

This feature will implement rage mode into the cooking process. This will enable faster cook and chopping times whilst it is activated and go back to the normal times whilst rage mode is inactive. This feature will help to implement more functionality with stations and items, allowing for a more dynamic and changing kitchen process.
 
# **Dependencies**
No current dependencies as this is a standalone task which can be implemented now.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add event listeners to items (Sep. 26)
- [ ] Allow for rage mode to trigger the changes(Sep. 26)
- [ ] Create an algorithm for how cooking times are changed (Sep. 26)
 
**Completion Deadline:** Sep. 28
 
# **Member**
- Callan Vragalis @silagarv

**Comment by silagarv** [comment]
Merged
