### ISSUE TITLE
Tutorial  pop up button

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#364]
# **Description**
**Task:** Tutorial pop up button 
**Feature:** (#146)

Creating pop up button for players to choose wether or not they want to go into tutorial mode or no
 
## **Example (optional)**
- When a player clicks on Start Game, it will prompt the user to click on a button to go to tutorial or no

# **Dependencies**

- [x] Depends on Tutorial to be implemented (#146)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Drafting and sketching structure of code and doing popup images(Sep. 27)
- [x] Coding and implementing popup to screen (Sep. 29)
- [x] Documentation (Sep. 30)
 
**Completion Deadline:** Sep. 30

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Airyl Harridzuan Bin Suaidi (@airylsuaidi)
