### ISSUE TITLE
Customer Movement Extended

### ISSUE THREAD

**Issue by V4N5HM** [UQcsse3200/2024-studio-3#366]
# **Description**
Fixing up the customer movement. The bug in the trigger needs to be fixed making it functional and making the customers stop at different target points on the counter instead of pushing each other and disposing the customer when they exit the restaurant.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fixing the trigger (Sept 19)
- [x] Disposing the customers (Sept 23)
- [x] Setting different target points on the counter (Sept 30)

**Completion Deadline:** Sept. 30

# **Documentation**
- [Customers](https://github.com/UQcsse3200/2024-studio-3/wiki/Customers)

# **Members**
- Vansh Mittal (V4N5HM) 
- Sui Lei (ImLeiSu)
