### ISSUE TITLE
Event handling when ingredients inputted into a station 

### ISSUE THREAD

**Issue by AshHarikrishna** [UQcsse3200/2024-studio-3#37]
**Feature:** : #9 

This task involves implementing an event handling system to monitor the duration an item is stored in a station. The event handler will track the time from when the item is placed in the station until it is removed or if the station is turned off. Based on the time spent in storage, the system will update the item's state to indicate whether it is uncooked, cooked, or overcooked. The goal is to ensure accurate state transitions depending on the item's duration in the station (other factors will also be considered).

# **Dependencies**
-  #38 
- #17
- #19 
- #48

# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial design of event handler and timer (Aug. 23).
- [x] Timer functionality implemented (Aug. 25).
- [x] Implement start cooking and update methods (Aug. 27).
- [x] State transition logic integrated (Aug. 27).
- [x]  Implemented Chopping Component (Aug. 27).
- [x] Final testing and documentation update (Aug. 29).
 
**Completion Deadline:** (Aug. 29)

 
# **Member**
- Ashwin @AshHarikrishna (Ashwin Harikrishna)
- Calvin @CalvinJohn99 (Calvin John Shaji)
