### ISSUE TITLE
Item Handler Component for Interaction with Inventory Component

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#38]
# **Description**
**Task:** Item Handler Component for Interaction with Inventory Component
**Feature:** #3 

Create a handler component that calls to inventory component to provide interface for other teams. Improves modularity and reduces need to specify inventory component for each station therefore abstract inventory component. Better plug and play for future changes as well

# **Dependencies**
- [ ] #17 - Will change with updates to inventory component

# **Milestones**
List of steps that need to be completed for this task.
- [x] Set up base framework with calls to Inventory Component (Aug. 21)
- [ ] Ensure capability with calls from PlayerActions Component (Aug. 22)
- [ ] Wiki (Aug. 22)
- [ ] Tests (Aug. 22)
 
**Completion Deadline:** Aug. 23

 
# **Documentation** - Update when complete
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
