### ISSUE TITLE
Improving the SonarCloud Test Coverage for Team 3

### ISSUE THREAD

**Issue by bhavyamalik1** [UQcsse3200/2024-studio-3#381]
# **Description**
This feature will involve writing tests to improve the Sonar Cloud coverage for the interaction and cutscene components. The current coverage for CutsceneFactory.java and IntroCutscene.java is 94.1%, and for ColliderComponent.java and SensorComponent.java is 81.9%. 

# **Milestones**

- [ ] Write CutsceneFactory.java tests (Oct. 2)
- [ ] Write IntroCutscene.java tests (Oct. 2)
- [ ] Write ColliderComponent.java tests (Oct. 2)
- [ ] Write SensorComponent.java tests (Oct 2.)

**Completion Deadline:** (Oct 3.)

# **Documentation**
- [Player Interaction](https://github.com/UQcsse3200/2024-studio-3/wiki/Player-Interactions)
- [Cutscenes](https://github.com/UQcsse3200/2024-studio-3/wiki/Cutscenes)

# **Members**
- Bhavya Malik (@bhavyamalik1 )
