### ISSUE TITLE
Moral Decision Integration into Win/Loss Logic and Subsequent Triggering of Correct Cutscene 

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#385]
# **Description**
**Task:** [Moral Decision Integration into Win/Loss Logic and Subsequent Triggering of Correct Cutscene](#385).
**Feature:** [Expansion of Win/Loss System](#311)

This task will involve integrating moral decisions into the win/loss system. The player's decisions at the end of each day will be tracked and used to influence the player's final ending. While moral decisions will not immediately cause the player to lose, they will impact the game's outcome at the end. Moral decisions will also affect whether the player receives a "good" or "bad" ending upon winning. If the player wins but has made one or more "bad" moral decisions, the bad ending will be triggered. If no bad decisions are found and the player wins, the good ending will be triggered. In the case of a loss, morality will not be considered, and the losing ending will play automatically.
 
## **Example (optional)**
- Moral Decision Effect: If the player makes a morally "bad" decision, it will not cause an immediate loss but will be recorded. If the player wins and has made bad decisions, a bad ending will be triggered.
Ending Triggering Logic: If the player wins and no "bad" decisions are found, a good ending will be triggered. If the player loses, morality will not be checked, and the losing ending will play automatically.

# **Dependencies**
- [x] MoralDecision 
- [x] Decision
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Modify Win/Loss Logic: The win/loss logic in ForestGameArea will be modified to include the effects of moral decisions when determining the outcome. The game will trigger a bad ending if the player has won but made "bad" moral decisions, or a good ending if the player wins with only "good" decisions. If the player loses, morality will not be checked, and the losing ending will play (Aug. 30).
- [x] Testing and Integration: Testing will ensure moral decisions are applied, and the correct ending is triggered depending on the player's decisions and win/loss state (Oct. 1).
- [x] Wiki Documentation: The wiki will be updated with explanations of the moral decision system and how it influences the win/loss logic (Oct. 2).
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Win-Loss-Logic

# **Member**
- Madeleine Coombs (@madeleinecoombs)
