### ISSUE TITLE
Add requirement for player to interact with chopping station to chop item.

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#386]
# **Description**
Currently, when placing an item at a cooking and chopping station, the item starts the process itself. This may make sense for cooking, but for chopping this doesn't. So This feature will implement the requirement for a player to actively press a key in order for a given item to chop. This creates better interaction with the game instead of just having everything automated.

# **Milestones**
- [x] Choose key for this feature (Sep. 30)
- [x] Implement this into the game (Sep. 30)
- [x] Fix any bug / issues encountered (Sep. 30)

**Completion Deadline:** Oct. 1

# **Members**
Callan (@silagarv)

**Comment by silagarv** [comment]
Merged
