### ISSUE TITLE
Rework day night service and player service to be able to retrieve the current time and player variables

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#388]
# **Description**
**Task:** Save/Load game (#284).
**Feature:** Rework day night service and player service to be able to retrieve the current time and player variables (#2)

The day night service needs to be reworked so the day and current time can be used by the SaveLoad system #284. Also the player service need to able to actually retrieve the player so it can access the combat component

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add getters and setters for the day the user is on (Sep 30)
- [x] Add player to player service with getter and setter (Sep 30)
- [x] Rework time checking to be stored in DayNight service (Oct 1)
- [x] Check tests are covering all code and working well (Oct 2)
**Completion Deadline:** Aug. 23

# **Documentation**
- DayNight cycle wiki https://github.com/UQcsse3200/2024-studio-3/wiki/Day-Night-Cycle
 
# **Member**
- Jackson Van Duikeren (@aridspace10)
