### ISSUE TITLE
Spawning Controller for Customer

### ISSUE THREAD

**Issue by AidenRichards03** [UQcsse3200/2024-studio-3#39]
# **Description**
**Task:** [Spawning Controller for Customer](#39).
**Feature:** #7  

The customers created will need the capabilities to spawn on the map. This ticket aims to create a spawn controller for the customers that can be utilised regardless of spawn location or the type of customer spawning. The spawn controller will be inside the GameArea class.
 
# **Dependencies**
- []Making Customer Entity(#22)
- []Colour Palette/ Map Design(#2)

e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Spawn Controller in GameArea(Aug. 23)
- [x] Define Alterations for larger customers (Aug. 24)
- [x] Define Spawn location for game area (Aug. 25)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@AidenRichards03 ) (Aiden Richards)
