### ISSUE TITLE
Improve main menu screen

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#392]
# **Description**
**Task:** Improve main menu screen
**Feature:** #300 #359 

This task is related to improving the main menu screen by improving the background and modifying the logo.

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task (Sept 26)
- [ ] Creating a Main menu background display class (made it easier when implementing) Sept 26)
- [ ] Add a background instead of plain colour (Sept 28)
- [ ] Design a new logo (Sept 28)
- [ ] Add the new logo (Sept 28)
 
**Completion Deadline:** Sept 28
 
# **Documentation**
- [Map design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)

# **Member**
- @Sarahkhalek

**Comment by Sarahkhalek** [comment]
Closed by #377
