### ISSUE TITLE
Player Action and Interaction

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#4]
# **Description**
As the player moves throughout the play space, they have the controls as a UI at the bottom of the page (e.g. WASD) and when they come into the range of an interactable object and it is the closest one, the object is outlined and a tooltip of the button to interact with it is shown to the top right of the player and the item name shown above it.

## **Examples**
- **Item Outline**: When a player is near a chopping board, the outline of the sprite is shown.
- **Tool Tip**: When a player has an onion in their hand, and they are near a chopping board, the tooltip for the interaction with the chopping board is shown.

## **Dependencies**
_Add dependencies_
Items relies on this ticket, as they cannot be interacted with without this interaction.
This ticket relies on how the inventory is set up.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Key binding for interactions with items [Aug 17]
- [ ] Alter settings page UI to include keybinds [Aug 18]
- [ ] Key binding for interactions with equipment [Aug 19]
- [ ] Outline of sprite when able to interact with it, with the title of the interactable [Aug 21]
- [ ] Tooltip of button that needs to pressed to interact [Aug 22]
- [ ] Animating basic movement of the player [Aug 22]
- [ ] Stop player movement while interacting with a station
- [ ] Write tests for checking for outline [Aug 22]
- [ ] Write tests for checking within range of interactable [Aug 22]
- [ ] Write tests for checking event triggers [Aug 22]

**Completion Deadline:** Aug. 23

# **Extras (optional)**
- [ ] Switching inventory items

# **Documentation**
- [Main description of feature](../wiki/Player-Interactions)

# **Members**
- Caleb Murphy (Caleb-J-Murphy)
- Bhavya Malik (bhavyamalik1)
- Sanchit Dayal (Sanchitt16)
- Anshuman Misra (Anshuman0157)
- Marshall Bullis (Marshall-Bullis)
- Manpreet Singh (Manpreetingh)
