### ISSUE TITLE
Upgrades NPC

### ISSUE THREAD

**Issue by willembor** [UQcsse3200/2024-studio-3#410]
# **Description**
When the game is first started, a penguin NPC will approach the counter and once clicked, will prompt the user if they wish to spend gold on a random upgrade which will benefit the player.

#**Sub Feature/Component**
- Be able to click the interact with penguin
- involve the upgrades system

#**Dependencies**
- #290 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create code space in ForestGame (Sep. 28)
- [x] Make NPC able to be clicked (Sep. 29)
- [x] Implement upgrade functionality (Sep. 30)
- [x] Testing & Documentation (Oct 2)

# **Members**
- @CalvinJohn99 Calvin
- @AshHarikrishna Ashwin
