### ISSUE TITLE
Team 1 - Score System Implementation

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#413]
# **Description**
The player in this game is expected to serve customers food and make enough money to survive everyday. The player must navigate the stressful kitchen environment to produce food accurately and quickly in order to not lose their customers, otherwise they would lose the game. However, there have not been any system implemented to reward players for their efforts or punish them for their mistakes, which is why the Score System was devised. This system considers the accuracy of the meal the player has served to a particular customer, and lets the player know whether the customer is satisfied with their meal or not. If they are happy with their meal, the customer will tip the player, while if the customer is unhappy with their meal, they will underpay the player. This system therefore incentivises the player to perform via positive and negative reinforcement.

# **Dependencies**

- StationServingComponent to submit meal to the customer.
- MainGameOrderTicketDisplay to appropriately show and select order tickets.
- Station interaction and functionality required for cooking, chopping and combining ingredients into a meal.
- InventoryComponent to get meals (#6).
- ScoreSystem to call and compare player meal with ordered meal to generate customer satisfaction score (#164).

# **Milestones**
- [x] Change the HoverBoxComponent to display ordered meals. (Sep. 28th)
- [x] Create scoreMeal() method to generate customer satisfaction score. (Sep 30th)
- [x] Update HoverBoxComponent to display customer satisfaction after meal is submitted. (Sep 30th)
- [x] Increment gold according to customer satisfaction score and ordered meal prices. (Oct. 2nd)
- [x] Display and update gold correctly according to the incrementation. (Oct. 2nd)

**Completion Deadline:** Oct. 3rd

# **Documentation**
- [Scoring System](../wiki/Scoring-System)

# **Members**
- Benjamin Wang (@benjamin-wang1)
- Quoc Bao Huynh (@bhuynh3004)
