### ISSUE TITLE
Team 4 unit test improvements

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#418]
# **Description**
**Task:** 
**Feature:** 

Improving unit tests for classes including `MainGameActions`, classes in tutorial folder, and backstory cutscene classes. Tests will be improved based on SonarCloud code coverage.

# **Dependencies**
- [x] #350 
- [x] #285 
- [x] #364 
- [x] #353 
 
# **Milestones**
- [x] Check SonarCloud for relevant classes (Oct. 2)
- [x] Add unit tests (Oct. 3)
- [x] Update SAF (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- 
 
# **Member**
- Aadya (@abhat0 ) (Aadya Bhatia)
