### ISSUE TITLE
Implementing scoreMeal() Method

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#419]
# **Description**
**Task:** Create scoreMeal() method for generating customer score.
**Feature:** [Score System Implementation](#413)

The task is to implement a scoreMeal() method that calls the Score System to compare two things: 1) The player's meal's ingredients and 2) The customer's ordered meal's ingredients. By this comparison, an accuracy rating is determined based on how many ingredients are matching. The more ingredients match, the higher the score, which also means higher customer satisfaction. The method will also increment the gold according to the accuracy of the ingredients and the advertised price of the meal the customer initially ordered.

# **Dependencies**

- [x] StationServingComponent to submit meal to the customer.
- [x] InventoryComponent to get meals (#6).
- [x] ScoreSystem to call and compare player meal with ordered meal to generate customer satisfaction score (#164).
- [x] Station interaction and functionality required for cooking, chopping and combining ingredients into a meal.
 
# **Milestones**

- [x] Get the player's meal from their inventory, and also get the meal from the order ticket. (Sep. 28th)
- [x] Compare the ingredients of both meals in scoreMeal(). (Sep. 30th)
- [x] Increment gold according to ingredients accuracy and the ordered meal price. (Sep. 30th)
- [x] Update the game UI to reflect the gold incrementation. (Oct. 1st)
- [ ] Handle case where the player takes too long to make the meal and the ticket expires. (Oct. 2nd)
 
**Completion Deadline:** Oct. 3rd
 
# **Documentation**
- [Scoring System](../wiki/Scoring-System)
 
# **Member**
- Quoc Bao Huynh (@bhuynh3004)
