### ISSUE TITLE
Update HoverBox Display

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#420]
# **Description**
**Task:** Update HoverBox Display.
**Feature:** [Score System Implementation](#413)

When the game starts, the customers spawn in with a HoverBox over their heads, which display the item that they have ordered. After the player submits the meal they've created to the customer, the HoverBox will update, replacing the meal image with a face type that reflects their satisfaction level with their meal. This satisfaction level is based on the accuracy of the meal's ingredients.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] StationServingComponent to submit meal to the customer.
- [x] Implementation of scoreMeal() to update HoverBox (#419).
- [x] Station interaction and functionality required for cooking, chopping and combining ingredients into a meal.
 
# **Milestones**

- [x] Add HoverBox component to NPC spawning logic with switch case statements that fetch the NPC's preferences and call specific image paths to generate the correct meal image.
- [x] Link customer to their own order ticket by generating a unique order number. (Sep. 28th)
- [x] Create CustomerManager to connect customer to their ticket. (Sep. 30th)
- [x] Implement new HoverBox update texture method that allows the displayed image to be updated. (Sep. 30th)
- [x] Create switch case statements in scoreMeal() to fetch the score and call specific image paths to generate the correct face type. (Sep 30th)
- [x] Call the HoverBox update texture method inside scoreMeal(). (Sep. 30th)
- [ ] Handle case where the player takes too long to make the meal and the ticket expires, which upsets the customer. (Oct. 2nd) 
 
**Completion Deadline:** Oct. 3rd
 
# **Documentation**
- [Scoring System](../wiki/Scoring-System)
 
# **Member**
- Quoc Bao Huynh (@bhuynh3004)
