### ISSUE TITLE
Player Inventory Component Extension

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#44]
# **Description**
**Task:** Extending the inventory component into the player inventory component.
**Feature:** [Team 1] Inventory System (#6)

Taking the base level inventory component and implementing it into the player's inventory.

# **Dependencies**
- [x] Inventory feature branch creation (#28)
- [x] Setter/getter/initialising inventory system (#33)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Test functionality of base level inventory component (Aug. 19)
- [x] Step 2 Modify/add additional code to create player inventory component (Aug. 20)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Inventory System Wiki](https://github.com/UQcsse3200/2024-studio-3/wiki/Inventory-System)

# **Member**
- Bao Huynh (@bhuynh3004)
