### ISSUE TITLE
Increase coverage for cutscene files

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#441]
# **Description**
**Task:** [Increase coverage for cutscene files](#441).
**Feature:** [Create Cutscenes for each start of the day](#278 )

The current coverage for the cutscene folder is 45%
![Cutscene Coverage](https://github.com/user-attachments/assets/f33f6de9-a773-4eef-b832-69885b4fb833)
This ticket aims to increase this score to about 80%.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Test for Day2Cutscene.java (Oct. 03)
- [ ] Create Test for BackgroundRenderComponent.java (Oct. 03)
- [ ] Create Test for CutsceneFactory.java (Oct. 03)
 
**Completion Deadline:** Oct. 03

# **Documentation**
- [Sonar Cloud Stats](https://sonarcloud.io/component_measures?metric=new_coverage&selected=UQcsse3200_2024-studio-3%3Acore%2Fsrc%2Fmain%2Fcom%2Fcsse3200%2Fgame%2Fcomponents%2Fcutscenes&id=UQcsse3200_2024-studio-3)
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Not completed in the sprint. Will be done by another team.
