### ISSUE TITLE
Basic Player Animation 

### ISSUE THREAD

**Issue by Manpreetingh** [UQcsse3200/2024-studio-3#45]
# **Description**
**Task:** Basic Player Animation
**Feature:** Player Action and Interaction #4

Adding the animation to the movement of the player 

# **Dependencies**
- [x] Setting the animation of the player according to the key binding in (#26)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Base Sprites (Aug. 20)
- [x] Adding animations (Aug. 22)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Manpreet Singh @Manpreetingh  (Manpreet Singh)
