### ISSUE TITLE
Team 3 Cleanup

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#451]
# **Description**
Cleaning up all old branches, pull requests, wiki pages that need to be updated.
- Fire extinguisher needs to be merged into the stations

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Delete Old Branches that are NOT in use (Oct. 8)
- [x] Close any old pull requests (Adding information as what they do, remember to review) (Oct. 8)
- [x] Updated Fire Extinguisher wiki to go into the stations wiki (Oct. 8)
- [x] Close any old issues (Oct. 8)
- [x] Update the cutscene overview Wiki page to make the cutscene implementation more clear to other teams. (Oct 6)

**Completion Deadline:** Oct 10

# **Documentation**

# **Members**
- Caleb Murphy (@Caleb-J-Murphy)
- Anshuman Misra (@Anshuman0157)
- Manpreet Singh (@Manpreetingh)
