### ISSUE TITLE
Improve Save/Load System

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#452]
# **Description**
The save load system currently built needs improvements which will allows it to be used and make it more user friendly

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Fix why load/game isn't working in main (Sep 7th)
- [ ] Add ability for user to enter name of the save (Sep 9th)
- [ ] Improve UI design for save menu (Sep 11th)
- [ ] Add ability to load game in pause menu (Sep 15th)

**Completion Deadline:** Sep 17th

# **Documentation**
- None

# **Members**
- Jackson (@aridspace10)
