### ISSUE TITLE
End Cutscene Fixes

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#453]
# **Description**
The end cutscenes are done, but they don't work in main and this is a little problematic. Additionally only one of three are currently animated, a little less then what we set out to achieve. Thus cutscene calls need to be fixed, and the final two cutscenes will be animated. We will also attempt to provide better test coverage for this system where possible.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Animate non-animated cutscenes (Oct. 10)
- [x] Fix cutscene bugs (Floating textbox, end-of-cutscene transitions, etc.) (Oct. 12)
- [x] Add testing for animated cutscenes (Oct. 14)
- [x] Fix code smells and add Javadoc (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
- [Ending Cutscenes](../wiki/Ending-Cutscenes)
- ...

# **Members**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jason Mauchline (DistractedJ)
- Jordan Russo (jRusso03)
