### ISSUE TITLE
Code Smell: components/stations

### ISSUE THREAD

**Issue by Anshuman0157** [UQcsse3200/2024-studio-3#456]
# **Description**
**Task:** [Code Smell: components/stations](#456).
**Feature:** [Code Smells] (#455)
Fix all **90** code smells located in the test folder, specifically the `/game/components/station/` folder.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] BenchTest.java (Oct. 9)
- [ ] CookingComponentTest.java (Oct. 9)
- [x] FireExtinguisherHandlerComponentTest.java (Oct. 9)
- [x] IngredientStationHandlerComponentTest.java (Oct. 9)
- [x] StationChoppingComponentTest.java (Oct. 9)
- [x] StationCollectionComponentTest.java (Oct. 9)
- [x] StationCookingComponentTest.java (Oct. 9)
- [x] StationItemHandlerComponentTest.java (Oct. 9)
- [x] StationMealComponentTest.java (Oct. 9)
 
**Completion Deadline:** Oct. 9
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
CookingComponentTest.java seems to have been commented out. Might need to bring this up mid sprint
