### ISSUE TITLE
Cutscene Fixes

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#457]
# **Description**
Reimplement the cutscenes and functionality that was deleted.
Allow cutscenes to move to a specific level
Allow levels to move to a specific cutscene
Add Day 5 cutscene
Update Day 2 cutscene

# **Dependencies**

Depends on cutscenes being fully implemented

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Reimplement Old Cutscene Changes
- [ ] Cutscenes move to a specific level
- [ ] Level moves to a specific cutscene

**Completion Deadline:** Oct 10

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Caleb Murphy (@Caleb-J-Murphy)
- Anshuman Misra (@Anshuman0157)
- Manpreet Singh (@Manpreetingh)
