### ISSUE TITLE
Finalise + fix station spawning

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#459]
# **Description**
Finalise station spawning through MapLayout to fix the following issues:
- Collisions and interactions are buggy when stations are spawned (interactions are inconsistent)
- Station layout (particularly benches) can spawn in wrong order / with wrong assets (benches overlap unnaturally)
- Designate stations such as fire extinguisher and trash can (currently spawn as an asset on top of a bench)
- Improve layout designs and finalise them
- Fix Game area background as well as make sure this works by implementing more testing
We should also work on finalising the UI by including the components and making sure with other teams that there are no bugs with the visual aspect of the game. 
- Polish code/documentation

## SubFeature/component (optional)
1. Debug station spawning from MapLayout (calling station spawn functions work (as shown when the restaurant layout was hardcoded) so issue should be here)
2. Fix how benches are loaded in
3. Finalise fire extinguisher/trash can (miscellaneous stations) implementation

# **Dependencies**
- Stations are finalised and working correctly (collisions were being finalised towards end of sprint 3)

# **Milestones**
- [X] Testing and improve MapLayout (12 Oct.)
- [X] Fix bench layout designs (9 Oct)
- [X] Fixing the background issues (12 Oct)
- [X] Finalising design/UI (14 Oct)
- [X] Fix miscellaneous stations (9 Oct) (Talk with stations team?)

**Completion Deadline:** Oct 14

# **Documentation**
- [Map Layout](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
- [Map Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)
- [UI](https://github.com/UQcsse3200/2024-studio-3/wiki/Redesign-of-Gold-and-Time-UI)
- [Game Background](https://github.com/UQcsse3200/2024-studio-3/wiki/Main-Game-Screen-Background)

# **Members**
- @Sarahkhalek 
- @ATOApplett 
- @amacn13 
- @pineapple11111 
- @danhdinh98 
- @Rakshit31773

**Comment by Sarahkhalek** [comment]
Closed by #542
