### ISSUE TITLE
Item-Cooking Paradigm

### ISSUE THREAD

**Issue by jRusso03** [UQcsse3200/2024-studio-3#46]
# **Description**
**Task:** [Item-Cooking Paradigm](#3)
**Feature:** [Items](#2)

This task focusses on how our (food) items will interact with the cooking stations (chopping board, oven, stove, etc.). In particular, how will items go in, get changed, and come out of a food station in a new form. This new form shall have an effect on gameplay via changing the items visuals and allowing it to be used to make meals. This form change will be recorded in the food entities ItemComponent component, in particular, its itemState (which can be raw, cooked or burnt) and isChopped member variables. 

 
## **Example**
- **Interaction**: Players can go up to a station, place their selected item in/on the station, wait for the item to cook/be chopped, then be able to pick up their newly cooked/chopped item.

# **Dependencies**

- [ ] Team 5 has created station entities/components (#16)
- [ ] Each cookable item has a texture for when it is raw, cooked and burnt
- [ ] Each chop-able item has a texture for when it is chopped or not

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create textures for basic food items (Aug. 23)
- [ ] Create a method within the station class for inputting food items (Aug. 24)
- [ ] Create a method within the station class for updating food items (Aug. 25)
- [ ] Player can retrieve cooked item (Aug. 26)
 
**Completion Deadline:** Aug. 26

 
# **Documentation**
- [Items](https://github.com/UQcsse3200/2024-studio-3/wiki/)

 
# **Member**
- Jordan (@jRusso03)
