### ISSUE TITLE
Balancing the game loop so its possible to complete all orders within the time limit

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#460]
# **Description**
Balance the game by altering recipe timers, customer spawn times, and types of customers spawning so that it is actually possible to complete all customer orders if playing optimally. This is an essential feature in this game since players need to be able to actually be given orders that are possible to complete within the timeframe given different ingredients spawning on different levels, and recipe timings. Once this feature has been implemented it will ensure the game is playable and possible to complete the core gameplay - making and serving meals.

# **Dependencies**
- Order system for docket timings
- Customer system with regard to spawn times and customer types

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Adjust ticket timers (Oct.17)
- [x] Adjust customer spawn times (Oct.17)
- [x] Adjust ingredient availability to make sure it is possible to create the required meals for each day (Oct.17)

**Completion Deadline:** Oct.17

# **Documentation**
- [Customer spawning wiki](..//wiki/Customers#customer-spawning)
- [Order system wiki](../wiki/Ordering-System-Overview)

# **Members**
- Anna Stevens (@goanna5)
- Serene McCormack (@serenemccormack)
- Quoc Bao Huynh (@bhuynh3004)
- Sourav Roy Chowdhury (@Sourav-RC)
- Benjamin Wang (@benjamin-wang1)
