### ISSUE TITLE
MORE EXTENDED end of day display

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#463]
# **Description**

Extend the End of Day screen by showcasing the successful and unsuccessful customers that are served throughout the day. This will then segue into the moral decision that players will make at the end of the day that will impact the next day.

# **Dependencies**

Feature ticket relies on End of Day #247 

# **Milestones**

- [x]  Show successful customers served
- [ ]  make customer ID connect to the order
- [x]  Improve update customers list UI

**Completion Deadline:** Oct 17

# **Documentation**

- [End of Day](https://github.com/UQcsse3200/2024-studio-3/wiki/End-of-Day-Display)

# **Members**

Lei Su (@ImLeiSu)
