### ISSUE TITLE
Bug fix for beef animation being shown as banana

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#464]
# **Description**
Title and also will attempt to have inventory updating as soon as the player's item changes.

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix bug of beef being shown as banana (Oct. 7)
- [x] Attempt to change the component to only being called when player item changes (Oct. 10)
- [x] Fix player animation not changing unless a key is pressed
 
# **Member**
- Callan (@silagarv)
