### ISSUE TITLE
Tutorial Extended

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#469]
# **Description**
The tutorial is necessary to help the user understand how to play the game. Adding a clickable keybind info button on `MainGameScreen` which displays the list keybinds will help with this.

`This should be roughly a one paragraph description of the features / ideas on which your team plans to work. It should very briefly touch on why you think it should be in the game (e.g. "Adds an extra layer of depth to game play"). It should also describe how it will appear or be used in the final product (e.g. "On starting a level, the game will generate a random, procedurally-generated map").`

## SubFeature/component (optional)

Misc
- [ ] Fix code smells, improve code coverage, reduce duplications
- [x] Make tutorial a separate level (Level 0). Should fix multiple bugs.
- [x] When finishing the tutorial and starting the main game, the docket order numbers continue incrementing from the tutorial instead of restarting at order number 1.
- [x] Add an info button on the `MainGameScreen` to show the game's keybind 

Adding to tutorial
- [ ] Full tutorial on the ordering process, how customer's patience affects order docket timers, 
- [x] Full tutorial on how to prepare and cook meals.
- [ ] Full tutorial on how to serve meals, what affects the 'success' of a meal, and how the day ended (all orders timed out??)
- [x] Full tutorial on upgrades and 'rage mode' (what happens when a customer runs out of patience)
- [ ] Full tutorial on how moral dilemma works, how it will affect the end of game. 

Bugs:

- [x] On tutorial popup, when clicking `no`, the docket line is gone
- [x] Player movement doesn't work in tutorial
- [x] When pressing `enter` to exit tutorial, sometimes the game glitches because pause menu also uses `enter`
- [x] On tutorial popup, when clicking `yes`, double dockets spawn

## **Examples**

# **Dependencies**

# **Milestones**
- [x] Keybinds Info button (Oct. )
- [x] Bug fixes (Oct. )
- [x] Player movement (Oct. )
- [ ] Fix code smells and duplications
- [ ] Tests and code coverage (Oct. )
- [ ] Documentation (Oct. )

**Completion Deadline:** Oct. 

# **Documentation**
- 

# **Members**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
- Aadya (@abhat0) (Aadya Bhatia) 
- Tia (@tia-w) (teeyahisswag123)
