### ISSUE TITLE
Meal Items

### ISSUE THREAD

**Issue by jRusso03** [UQcsse3200/2024-studio-3#47]
# **Description**
**Task:** [Meal Items](#3)
**Feature:** [Items](#2)

This task focusses on how meals will be made from their individual ingredients, through the creation of a MealComponent  component and MealFactory Factory. MealComponent will be added to meal entities, which will be created via the MealFactory. These meals will eventually be used to give to customers for some monetary reward. MealComponent will contain the essential member variables/methods for meal items, such as its name, price, ingredient list and quality and their getters/setters. 

The MealFactory will contain the methods used when creating meals, such as createBaseMeal() or for example createSteakMeal(). These meal entities will be served to customers and, based on their quality, will return a monetary value to the player.

# **Dependencies**

- [x] Ingredients must be able to be cooked(#46)
- [x] There must be a specified station for making meals (#16)
- [x] Meal Textures must be created
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create initial MealComponent Component (Aug. 23)
- [x] Create MealFactory Factory (Aug. 25)
- [x] Create calculateQuality() Function within MealComponent (Aug. 26)
- [x] Source Meal Pixel Art (Aug. 26)
- [x] Testing (Aug. 27)
- [x] Write Documentation (Aug. 27)

 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Items](../wiki/Items)
- https://github.com/UQcsse3200/2024-studio-3/wiki/Food-Items#meals
- https://github.com/UQcsse3200/2024-studio-3/wiki/Items#mealcomponent

 
# **Member**
- Madeleine (@madeleinecoombs)
