### ISSUE TITLE
Keybinds Info Button

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#470]
# **Description**
**Task:** Keybinds Info Button (#470)
**Feature:** Tutorial Extended (#469 )

A button on the main game screen that can be clicked to show all the games keybinds.

`A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")`
 
## **Example (optional)**
List of keybinds:

- `WASD` - move player
- `e` - pick up / put down / interact
- `q` - chop
- `p` - end day screen
- `o` - pause 
- `enter` - pause
- `enter` - next cutscene
- `[` `]` - move dockets
- `L` - increase currency

# **Dependencies**
None.

# **Milestones**
- [ ] Gather list of keybinds from different teams (Oct. 6)
- [ ] Create button on main game screen (Oct. 7)
- [ ] Create popup when clicking button with the list of keybinds (Oct. 8)
- [ ] Tests (Oct. 9)
- [ ] Documentation (Oct. 10)
 
**Completion Deadline:** Oct. 11
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Aadya (@abhat0 ) (Aadya Bhatia)
