### ISSUE TITLE
Refining Backstory Cutscenes

### ISSUE THREAD

**Issue by tia-w** [UQcsse3200/2024-studio-3#473]
# **Description**
Fixing all bugs and UI-related issues/ discrepanices related to backstory cutscenes. 

## SubFeature/component (optional)
- [x] Add a skip button to backstory
- [x] Change appearance, position and size of text display
- [x] Background image resizing to fit different screens 
- [x] Add more tests

# **Dependencies**

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Change appearance, position and size of text display, reduce duplicate code for text display. (Oct. 15)
- [x] Update font and colour for text display where applicable. (Oct. 16 )
- [x] Add skip button for cutscenes (Oct. )

**Completion Deadline:** Oct. 17

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Tia (@tia-w) (teeyahisswag123)
