### ISSUE TITLE
Rework textdisplay class

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#478]
# **Description**
**Task:** Rework textdisplay class

The TextDisplay class was implemented in sprint 2 and has been useful in creating textboxes within the game however. The textboxt display however has been only been implemented for the MainGameScreen however it is needed for new screen created by other teams such as for cutscences or the tutorial. This has caused multiple textbox display class to be created causing increased duplicated lines and less code coverage. It has also been asked that a small tweaks is made to TextDisplay so full text will appear when pressing enter then move to next text line. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add full text display when pressing enter and then move to next set of text (Oct 8)
- [x] Make textbox display work for all screens (Oct 9)
- [x] Integrate changes to use central textbox display class instead of the other ones (Oct 10)
- [x] Communicate changes at studio meeting or on discord so they are aware of changes (Oct 10)
 
**Completion Deadline:** Oct 10th
 
# **Documentation**
None
 
# **Member**
- Jackson Van Duikeren (@aridspace10)
