### ISSUE TITLE
Improve map layouts (correct bench tile types + all stations included)

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#479]
# **Description**
**Task:** Improve map layouts (correct bench tile types + all stations included)
**Feature:** #459 

This task is about finalising the layouts for each level to make sure we are using the right tiles.
 

# **Dependencies**
No dependencies

# **Milestones**
List of steps that need to be completed for this task.
- [x] Choose the correct bench tile types (Oct 8)
- [x] Make sure all stations are included each day/include if not (Oct 8)
- [x] Replace them in text file (Oct 8)
- [x] Make sure it works (Back-end works - check with stations team)(Oct 9)
 
**Completion Deadline:** Oct 9

# **Documentation**
- [Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)

# **Member**
- @Sarahkhalek

**Comment by Sarahkhalek** [comment]
Closed with #542
