### ISSUE TITLE
Create Ingredient Component Class

### ISSUE THREAD

**Issue by DistractedJ** [UQcsse3200/2024-studio-3#48]
# **Description**
**Task:** [Meal Items](#3)
**Feature:** [Items](#2)

This task focuses on the creation of a specific subset of items labeled as ingredients through the implementation of an IngredientComponent and IngredientFactory. IngredientComponent will be added to ingredient entities which will be spawned via the ingredient factory. These ingredients will then be used to create the meals needed to be given to customers. IngredientComponent will include unique variables such as itemState to keep track of what condition the ingredient is in an cookTime to determine how long the ingredient needs to be operated on by a player, as well as required getters and setters for these variables.

The IngredientFactory will contain the methods used when creating the ingredients, such createMeat(). These ingredient entities will be utilised by the player to create meals.

# **Dependencies**

- [x] Item Component Class must exist (#19)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create IngredientComponent Component (Aug. 23)
- [x] Source Ingredient images (Aug. 26)
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Items](../wiki/Items)

 
# **Member**
- Jason (@DistractedJ)
