### ISSUE TITLE
Testing for Bench and Map Layout

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#480]
# **Description**
**Task:** Testing for Bench and Map Layout
**Feature:** #459 

This feature is about testing the Bench Generator and Bench Layout classes that are being used to spawn Benches. We also need better testing for MapLayout that is used to spawn the different map layouts based on the day/level. 

# **Dependencies**
No dependencies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Testing for Bench classes (Oct 11)
- [x] Adding/improving MapLayout with methods that facilitate testing (Oct 12)
- [x] Implement additional testing for these classes (Oct 12)
 
**Completion Deadline:** Oct 12
 
# **Documentation**
- [Map Layouts]()
 
# **Member**
- @Sarahkhalek 
- @pineapple11111 
- @ATOApplett

**Comment by Sarahkhalek** [comment]
Closed by #620
