### ISSUE TITLE
Fixing collisions

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#481]
# **Description**
**Task:** Fixing collisions
**Feature:** #459 

This task is related to fixing the collisions modified when creating MapLayout. This is to make sure that a player cannot walk over a bench or a station to ensure adequate gameplay when cooking and making different meals that need to be delivered to customers. 
 
# **Dependencies**
Would be good to finish finalising MapLayout and testing #480 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Bench Collisions (Oct 11)
- [x] Stations Collisions (Oct 11)
- [x] Fix any other issues that are faced when player moves (Oct 12)
 
**Completion Deadline:** Oct 12
 
# **Member**
- @danhdinh98 
- @Rakshit31773

**Comment by Sarahkhalek** [comment]
Closed by #533 (with team 5)
