### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Sarahkhalek** [UQcsse3200/2024-studio-3#483]
# **Description**
**Task:** Improve documentation
**Feature:** #459 

This task is related to improving documentation in our Map Layout, Map design and Background to make sure we add UML class diagrams and sequences diagrams. This would provide a more detailed explanation of our code implementations and the relations between classes. 
 
# **Dependencies**
No dependencies 

# **Milestones**
- [x] Add missing documentation from Sprint 3 (Oct 12)
- [x] Add new changes from this sprint (Oct 12)
- [x] Add UML diagrams and flow charts (Oct 12)

**Completion Deadline:** Oct 13

# **Documentation**
- [Map Design](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-designs)
- [Map Layouts](https://github.com/UQcsse3200/2024-studio-3/wiki/Different-map-layouts)
- [Background Game Screen](https://github.com/UQcsse3200/2024-studio-3/wiki/Main-Game-Screen-Background)
 
# **Member**
- @Sarahkhalek 
- @ATOApplett 
- @amacn13 
- @pineapple11111 
- @danhdinh98 
- @Rakshit31773
