### ISSUE TITLE
Code Smell: components/player

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#486]
# **Description**
**Task:** [Code Smell: components/stations](#456).
**Feature:** [Code Smells] (#455)
Fix all **74** code smells located in the main game folder, specifically the `/game/components/player/` folder.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] InventoryComponent.java (Oct 9)
- [x] InventoryDisplay.java (Oct 9)
- [x] InventoryDisplayHoverComponent.java (Oct 9)
- [x] KeyboardPlayerInputComponent.java (Oct 9)
- [x] PlayerActions.java (Oct 9)
- [x] PlayerAnimationController.java (Oct 9)
- [x] PlayerItemSpriteManager.java (Oct 9)
- [x] PlayerStatsDisplay.java (Oct 9)
- [ ] TouchPlayerInputComponent.java (Oct 9)
 
**Completion Deadline:** Oct. 9
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)
