### ISSUE TITLE
Player Collider Components Updates

### ISSUE THREAD

**Issue by Hayden-Elliott** [UQcsse3200/2024-studio-3#489]
# **Description**
**Task:** [Task Name](#3).
**Feature:** #454

Changes to player collider component architecture to allow for fixes to interaction as a total. 

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Investigate current architecture and errors introduced end of previous sprint (Oct 11th)
- [x] Make technical updates to player components in accordance with design patterns (Oct 13th)
- [x] Docs and testing updates (Oct 13th)
 
**Completion Deadline:** Oct 15
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by Hayden-Elliott** [comment]
After long deep dive no fix apparent or working on current main. Am going to checkout commits until breaks

Works at Oct 1st 11:05 GMT #387

**Comment by Hayden-Elliott** [comment]
Works on #417

**Comment by Hayden-Elliott** [comment]
Does not work #450

**Comment by Hayden-Elliott** [comment]
Works #443

**Comment by Hayden-Elliott** [comment]
Does not work #447 after map team merge. Logs indicate some kind of texture is attempting to be loaded but buffer crash occurring, further investigation

**Comment by Hayden-Elliott** [comment]
Issue potentially identified as lack of use of StationFactory and use of a new thing called Bench class
