### ISSUE TITLE
Code Smell: components/moral

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#492]
# **Description**
**Task:** [Code Smell: components/moral](#492).
**Feature:** [Code Smells] (#455)
Fix all **68** code smells located in the main game folder, specifically the `/game/components/moral/` folder.
Fix all **40** code smells located in the test game folder, specifically the `/game/components/moral/` folder.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] MoralConsequences.java (Oct 10)
- [x] MoralDayFour.java (Oct 10)
- [x] MoralDayOne.java (Oct 10)
- [ ] MoralDayThree.java (Oct 10)
- [ ] MoralDayTwo.java (Oct 10)
- [ ] MoralDecision.java (Oct 10)

Test Files:
- [ ] MoralDayFourTest.java (oct 10)
- [ ] MoralDayOneTest.java (oct 10)
- [ ] MoralDayTwoTest.java (oct 10)
- [ ] MoralDecisionTest.java (oct 10)
 
**Completion Deadline:** Oct. 10
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)

**Comment by Caleb-J-Murphy** [comment]
Completed in a seperate ticket
