### ISSUE TITLE
Code Smell: components/station

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#493]
# **Description**
**Task:** [Code Smell: components/station](#493).
**Feature:** [Code Smells] (#455)
Fix all **72** code smells located in the main game folder, specifically the `/game/components/station/` folder.
Fix all **10** code smells located in the test game folder, specifically the `/game/components/station/` folder.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] FireExtinguisherHandlerComponent.java (Oct 10)
- [x] IngredientStationHandlerComponent.java (Oct 10)
- [x] StationCookingComponent.java (Oct 10)
- [x] StationItemHandlerComponent.java (Oct 10)
- [x] StationMealComponent.java (Oct 10)
- [x] StationProgressDisplay.java (Oct 10)
- [x] StationServingComponent.java (Oct 10)

Test files
- [ ] CookingComponentTest.java (Oct 10)
- [x] FireExtinguisherHandlerComponentTest.java (Oct 10)
- [x] StationChoppingComponentTest.java (Oct 10)
- [x] StationCollectionComponentTest.java (Oct 10)
 
**Completion Deadline:** Oct. 10
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)
