### ISSUE TITLE
Code Smell: components/factories

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#494]
# **Description**
**Task:** [Code Smell: components/factories](#494).
**Feature:** [Code Smells] (#455)
Fix all **67** code smells located in the main game folder, specifically the `/game/components/factories/` folder.
Fix all **56** code smells located in the test folder, specifically the `/game/components/factories/` folder.

# **Dependencies**
N/A
 
# **Milestones**
List of steps that need to be completed for this task.
Game Files
- [x] DishFactory.java (Oct 10)
- [x] ItemFactory.java (Oct 10)
- [x] LevelFactory.java (Oct 10)
- [x] NPCFactory.java (Oct 10)
- [x] ObstacleFactory.java (Oct 10)
- [x] PlateFactory.java (Oct 10)
- [x] PlayerFactory.java (Oct 10)
- [x] StationFactory.java (Oct 10)
- [x] UIFactory.java (Oct 10)

Test Files
- [ ] NPCFactoryCustomerTests.java (Oct 10)
- [ ] StationFactoryTest.java (Oct 10)
 
**Completion Deadline:** Oct. 10
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)
