### ISSUE TITLE
MORE EXTENDED customer moving

### ISSUE THREAD

**Issue by ImLeiSu** [UQcsse3200/2024-studio-3#499]
# **Description**
This feature ensures that customers will wait in front of the counter for the same amount of time it takes for their order to be prepared. By synchronizing the waiting time with the order preparation time, this adds a layer of realism to the gameplay, making the customer interactions feel more dynamic. It also creates a more immersive experience for players, as they manage both the kitchen's efficiency.

# **Dependencies**

Customer Extended (#101 ).
Customer movement to counters and leaving restaurants (#175).

# **Milestones**
- [ ] Wait Time Synchronization implementation (Oct. 17)
- [ ] Customer leaves when order timer becomes 0 (Oct. 17)
- [ ] Customer leaves when order submitted (Oct. 17)
- [ ] Fix Customer Black Box Bug (Oct. 17)

**Completion Deadline:** Oct. 17

# **Documentation**
- [Customers](https://github.com/UQcsse3200/2024-studio-3/wiki/Customers)

# **Members**
- Vansh Mittal (@V4N5HM)
- Lei Su(@ImLeiSu)
