### ISSUE TITLE
Creating Items

### ISSUE THREAD

**Issue by Princess-Nx** [UQcsse3200/2024-studio-3#5]
# **Description**
Items will be at the core of the gameplay and will be used by all other teams. Items will include basic food which will be given to the player to be used in food recipes. These will be all created through a basic items component which will be different depending on the type of item and have a pixel art design developed in the future. 

## Examples
Current food items will be like:
- White bread
- Grain bread
- Chicken 
- Beef
- Lettuce 
- Tomato
- Cheese

## **Dependencies** ##
- customers (#7): Need to know what animals are being made to theme food around them
- recipes (#9): Need to know what food is being planned so matching ingredients can be made

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #19 
- [ ] Create simple item functions which will be used by the interaction (delete, spawn, etc) (Aug. 21)
- [x] Have a basic placeholder item on the screen (Aug. 25)
- [x] Have multiple items which are distinct on the screen (Aug. 29)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- Add more advanced functionality which can be used by other teams
- Begin to add pixel art for said items
- Work with interaction teams to allows items to be picked up

# **Documentation**
https://github.com/UQcsse3200/2024-studio-3/wiki/Entity-Component-System-(ECS)
# **Members**
- Princess Emeka-Ugwunali (Princess-Nx)
- Jackson Van Duikeren (aridspace10)
- Jason Mauchline (DistractedJ)
- Madeleine Coombs (madeleinecoombs)
- Jordan Russo (jRusso03)

**Comment by CalvinJohn99** [comment]
Hi from team 2,  we made the trigger for start cooking/chopping depending on the station in StationItemHandlerComponent.java. Please let me know if you have any issues or concerns.

**Comment by CalvinJohn99** [comment]
We're planning to improve the game logic to make it more of a game. To do this we're thinking of the stations that can cook food items to have a flag for whether it's "hot" or "warm" or "normal" to decrease or increase cooking times. You may need separate subclasses for such logic. Perhaps something to do for next sprint. The logic we suggest is, as soon as something finishes cooking, the state is set to "Hot" as the station remain idle or has no activity. This state gets set to "normal" or "warm" depengin on time.
