### ISSUE TITLE
Add key press tooltip functionality to the InventoryDisplayHoverComponent

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#509]
# **Description**
**Task:** Add key press tooltip functionality to the InventoryDisplayHoverComponent (#509).
**Feature:** Station interaction visualisation (#334)

Extend inventory visualisation to include pop-up icons that show when you can interact with a station, and what button to press, so players don't have to memorise keybinds.

# **Dependencies**
- [x] InventoryDisplayHoverComponent (#316)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add keyboard input UI functionality (Oct. 11)
- [x] Write up documentation for keyboard input UI (Oct17)
- [ ] Write tests for keyboard input UI (Oct.17)
 
**Completion Deadline:** Oct.17

# **Documentation**
- [Station Interaction Visualisation](../wiki/Station-Inventory-and-Visualisation)
 
# **Member**
- Benjamin (@benjamin-wang1)
- Sourav (@Sourav-RC)
