### ISSUE TITLE
Fix issues with the sensor component.

### ISSUE THREAD

**Issue by silagarv** [UQcsse3200/2024-studio-3#511]
# **Description**
Fix issues with the sensor component not correctly getting the current station and not updating to the most nearby station for interactions. This has caused issues with being able to use items, for getting them from baskets, to putting them in stations, to chopping them... This will hopefully resolve those issues.

# **Dependencies**
The tips for using the station need to be done so that this can be updated. They are currently complete.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a basic approach to use to fix this issue (Oct. 10)
- [x] Implement the approach to be able to work with the display tips (Oct. 11)
- [x] Update the sensor component tests to be in line with the new component (Oct. 11)
- [x] Check for any bugs and fix them (throughout process)
 
**Completion Deadline:** Oct. 12
 
# **Member**
- Callan @silagarv

**Comment by silagarv** [comment]
Complete
