### ISSUE TITLE
Adjusting the timings and customer spawnings in the game so that customers can be served appropriately

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#516]
# **Description**
**Task:** Adjusting the timings and customer spawnings in the game so that customers can be served appropriately (#516).
**Feature:** Balancing the game loop so its possible to complete all orders within the time limit (#460).

Essentially updating the timings so all the customers don't spawn at once and instead spawn throughout the day. Also investigating into making only customers spawing who have a meal that can be created from the ingredients on each day.

**Day 1:** recipe(s): salad; customer(s): John (goat)
**Day 2:** recipe(s): salad, fruit salad; customers(s): John (goat), Hank (gorilla)
**Day 3:** recipe(s): salad, steak meal; customers(s): John (goat), Silver (snow fox)
**Day 4:** recipe(s): banana split, acai bowl, fruit salad; customers(s): Moonki (monkey), Lewis (goose), Hank (gorilla)
**Day 5:** recipe(s): *all* (salad, steak meal, banana split, acai bowl, fruit salad); customers(s): *all* (John (goat), Silver (snow fox), Hank (gorilla), Moonki (monkey), Lewis (goose))

 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Modify the timings so that customers don't spawn all at once (Oct 17).
- [x] Modify the customers so that only customers that meals can be created for spawn in on the relevant level (Oct 17).
- [ ] Fine tune the customer spawn times so they don't all spawn at once (Oct 17).
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Anna Stevens (@goanna5)
