### ISSUE TITLE
Making tutorial at level 0

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#518]
# **Description**
**Task:**(#469 ).
**Feature:** Making tutorial at level 0

 
## **Example (optional)**
- Currently, levels are starting at tutorials (if tutorials) are initiated

# **Dependencies**

- [x] (#106)
- [x] (#107)
- [x] (#171)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Setting tutorial to start at level 0 (Oct 15.)
- [x] Writing tests and Javadocs (Oct. 16)
- [x] Documentation and Wiki update (Oct. 16)
 
**Completion Deadline:** Oct 16.

 
# **Documentation**
- [Level System Overview](https://github.com/UQcsse3200/2024-studio-3/wiki/Level-System-Overview)
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
