### ISSUE TITLE
Docket ticket numbers continuing from Tutorials

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#519]
# **Description**
**Task:** Docket ticket numbers continuing from Tutorials
**Feature:** (#469)

Since, dockets are spawning as well during tutorials, when in game (post tutorial) the docket number continues
 
## **Example (optional)**
- **Expected behaviour**: The docket numbers should reset and not continue from tutorials when in game

# **Dependencies**

- [x] (#469)
- [x] (#8)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Rectify files and make changes to file (Oct. 15)
- [x] Update tests coverage (Oct. 16)
- [x] Documentation and wiki update (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
