### ISSUE TITLE
Create JSON file 

### ISSUE THREAD

**Issue by daleelakhairil** [UQcsse3200/2024-studio-3#52]
# **Description**
**Task:** Creating JSON file and parsing it into factory
**Feature:** Food Recipe (#9)

Create a JSON file that includes all the recipe, load into the factory, and create the cooking config that includes all the variables inside the JSON file

### **Dependencies**
Need to give recipe.json to the item team so they can handle the recipe and ingredients (https://github.com/UQcsse3200/2024-studio-3/issues/5)
Create getter method to get recipe so https://github.com/UQcsse3200/2024-studio-3/issues/36 and the order team can use it

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create JSON file and add recipe into that file 
- [x] Load and parse it into factory
- [x] Save all the data into the config file 
- [x] add it into team branch 
- [x] make some changes on the config file  
- [x] make the recipe documentation
- [x] Create the recipe documentation
 
**Completion Deadline:** Aug. 23
