### ISSUE TITLE
UI Sprite Update

### ISSUE THREAD

**Issue by StrayIntellectual** [UQcsse3200/2024-studio-3#529]
# **Description**
UI Sprite Update

# **Dependencies**
Relies on existence and functionality of ui and menus. Low impact change as only sprites are being altered.

# **Milestones**
- [x] Update Upgrade Menu (14/10)
- [x] Update Pause Menu (15/10)
- [x] Update UI icons (16/10)

**Completion Deadline:** 16/10

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Andi (@StrayIntellectual)
