### ISSUE TITLE
Finish Extortion and Dance Party upgrades

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#539]
# **Description**
**Task:** Fully implement the extortion and dance party upgrades
**Feature:** #410 

Ensure extortion can double the gold from the ticket and dance party can stop the ticket timing until the upgrade finish
 
# **Dependencies**
- [ ] Ensure ticket didn't disappear when the dance party upgrade is activate (#142)
- [ ] Double gold for ticket when extortion is activate (#141)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Finish implementation for extortion (Oct 16)
- [x] Finish implementation for dance party (Oct 16)
- [x] Ensure dance party is added to UI when upgrade menu display (Oct 16)
- [x] Testing (Oct 16)
 
**Completion Deadline:** Oct 17

# **Documentation**
- [Upgrade](https://github.com/UQcsse3200/2024-studio-3/wiki/Upgrades)
 
# **Member**
- Willem (@willembor) 
- Ashwin (@AshHarikrishna)
- Alex (@Ashom2)
- Joanna (@Joanna-Wang105)
- Daleela (@daleelakhairil)
- Calvin (@CalvinJohn99)
