### ISSUE TITLE
Testing for Upgrade

### ISSUE THREAD

**Issue by Joanna-Wang105** [UQcsse3200/2024-studio-3#540]
# **Description**
**Task:** Testing for Upgrade
**Feature:** #290 #410 

Finish the testing for all the upgrades and upgrade display to ensure we have high code coverage 
 
# **Dependencies**
- [x] Rage upgrade  (#295)
- [x] Speed Boot upgrade (#291)
- [x] Extortion and Dance party upgrade (#539)
- [x] Upgrade display (#410)
 
# **Milestones**
- [x] Finish all upgrade testing (Oct 14)
- [x] Finish upgrade display testing (Oct 16)
- [x] Finish other testing if founded (Oct 17)
 
**Completion Deadline:** Oct 17

# **Member**
- Calvin (@CalvinJohn99 )

**Comment by CalvinJohn99** [comment]
![after_all_tests](https://github.com/user-attachments/assets/ae558d3a-e2f3-4321-8cd3-c9dd69924dd5)
