### ISSUE TITLE
Refactor InventoryDisplayHoverComponent and add more detailed key tooltip information

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#541]
# **Description**
**Task:** Refactor InventoryDisplayHoverComponent and add more detailed key tooltip information (#541).
**Feature:** Station interaction visualisation (#334)

Add the following functionality to the key tooltips displayed by InventoryDisplayHoverComponent:
 - Split the interact [E] tooltip into 4 distinct actions that can be done when pressing the E button: placing an item, taking an item, submitting a meal and disposing of an item. The correct action will be shown depending on which action is currently possible by the player (i.e. if the player is holding an item, the place tooltip will be shown when standing near a bench)

To do this, a refactoring of InventoryDisplayHoverComponent will be done since the current code structure is getting quite messy, making it harder to add new tooltip types. It will be converted to a new abstract component, StationHoverComponent, which can be extended to create a station hover component class for each different type of station. StationHoverComponent will provide the core inventory displaying functionality for each station, whereas each child class can implement the tooltip behaviour specific to each station.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x]  Base Key tooltip functionality required (#334)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactor InventoryDisplayHoverComponent to become StationHoverComponent (Oct. 15)
- [x] Re-implement existing tooltips by extending StationHoverComponent for each station type (Oct. 16)
- [x] Add new tooltip functionality (Oct. 16)
- [x] Write documentation (Oct. 17)
- [ ] Write tests (Oct. 17)
 
**Completion Deadline:** Oct.17

# **Documentation**
- [Station Visualisation](../wiki/Station-Inventory-and-Visualisation)
 
# **Member**
- Benjamin (@benjamin-wang1)
- Callan
