### ISSUE TITLE
Level Service Extended

### ISSUE THREAD

**Issue by airylsuaidi** [UQcsse3200/2024-studio-3#543]
# **Description**
**Task:** Level Service Extended
**Feature:** (#107 )

Extending level service to have set level function to ease level upgrade and level downgrade.

# **Dependencies**

- [x] (#106)
- [x] (#107)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Creating setter functions for Level Service class (Oct. 15)
- [x] Creating getter functions for Level Service class (Oct. 15)
- [ ] Tests and Javadoc writings (Oct. 16)
- [ ] Documentation and wiki update (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Level System Wiki]https://github.com/UQcsse3200/2024-studio-3/wiki/Level-System-Overview
 
# **Member**
- Airyl (@airylsuaidi ) (Airyl Harridzuan Bin Suaidi)
