### ISSUE TITLE
Adjusting camera position and game area dimensions

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#55]
# **Description**
**Task:** Adjusting camera position and game area dimensions
**Feature:** [Map Design / Colour Palette](#2)

Focusing on the game area and the layout of the map
 
# **Dependencies**
- Design of the map/layout had to be done on photoshop - Task ticket #53 

# **Milestones**

- [ ] Move camera position to centre the game area while leaving space for the 'stats' on the left side

- [ ] Adding some padding on the top, left, right and bottom so that the game area does not take up the whole screen

- [ ] Setting the map dimensions needed for adequate tile filling of the map 

**Completion Deadline:** Aug. 25

# **Documentation**
- [Map Design](../wiki/Map-Design)
 
# **Member**
- @Sarahkhalek
