### ISSUE TITLE
Orange and blue floor tiles

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#56]
# **Description**
**Task:** Orange and blue floor tiles 
**Feature:** [Map Design / Colour Palette](#2)
 
This ticket concerns creating the orange and blue floor tiles on the game area. This concerns leaving a small portion of the map for customers/animals (the blue area). This task is about filling in the tiling map area with the orange and blue tiles we designed in the earlier weeks. 
 

# **Dependencies**
- No dependencies

# **Milestones**
- [x] Making the whole area orange
- [x] Update .assets with created textures
- [x] Redefine _TerrainFactory_ and _ForestGameArea_ to use updated assets
- [x] Update _ForestGameArea_  to generate tiles in the shape of layout
- [x] Added the blue area and making the orange area smaller 
 
**Completion Deadline:** Aug. 24

# **Documentation**
- [Map Design](../wiki/Map-Design)

# **Member**
- @Sarahkhalek

**Comment by danhdinh98** [comment]
Rough design completed and compared options. All documented here https://github.com/UQcsse3200/2024-studio-3/wiki/Map-Design
