### ISSUE TITLE
End of Day Summary

### ISSUE THREAD

**Issue by nimeshgarg** [UQcsse3200/2024-studio-3#57]
# **Description**
Providing end of Summary of the events.
 - Amount of money gained/lost
 - Moral Decision
 - List customer that were passed/failed

## SubFeature/component (optional)
None 

# **Dependencies**

- #8 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] End of Screen UI (Aug. 25)
- [ ] Pause Game
- [ ] Resume game at same In-Game time as Pause
- [ ] Functions of populate screen dynamically (Aug. 28)

**Completion Deadline:** Aug. 28

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Lei Su (@ImLeiSu )
- Marcus Baulch (@baulch-m) 
- Amber CHen (@ambs02)
