### ISSUE TITLE
Adjusting the recipe timers and customer spawn delays for optimal game play

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#571]
# **Description**
**Task:** Adjusting the recipe timers and customer spawn delays for optimal game play(#571).
**Feature:** Balancing the game loop so its possible to complete all orders within the time limit(#460).

Currently the recipe timers are too short (~20 secs for each meal except steak meal (~50 secs)) so it is impossible for the player to complete orders and serve them before the customer leaves. This task aims to adjust the timings on the recipes to make it possible for the player to complete all orders in a reasonable time and actually serve the customers and play the game.
 
# **Dependencies**
- [ ] Customer spawning (#xx)
- [ ] Recipe JSON file & tests (#xx)
- [ ] Level system for spawning customers (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Adjust the timings on tickets (Oct. 17)
- [x] Adjust the customer spawn times (Oct. 17)
- [ ] Adjust the end of day to trigger when last customer has despawned? (Oct. 17)
- [x] Test by playing the game and change the timings as required (Oct. 17)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Anna Stevens (@goanna5)
