### ISSUE TITLE
Extending Tutorial

### ISSUE THREAD

**Issue by LAKSHAYATREJA** [UQcsse3200/2024-studio-3#578]
# **Description**
**Task:** Extend the Tutorial
**Feature:** [Feature which this tasks contributes to implementing](#2) Tutrial

The tutorial introduces the new user or player to the functionalities of the game .So to cover all the features and give brief introduction adding more tutorials .
 
## **Example (optional)**
- **Part**: The rage mode tutorial
- A feature of game .

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

 The implementation of these features in main by the designated team:
- [x] Dependency 1 (#xx)Combine food
- [x] Dependency 2 (#xx)Rotating
- [x] Dependency 3(#xx)chopping

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Adding rage mode tutorial (Aug. 13)
- [x] Cutting tutorial (Aug. 14)
- [x] Rotate tutorial  (Aug. 15)
- [x] Combine food Tutorial (Aug. 16)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (LAKSHAYATREJA)
- e.g. Lakshay (@Lakshay)
