### ISSUE TITLE
Docket Status Indicator

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#58]
# **Description**
**Task:** Docket Status Indicator(#58).
**Feature:** Order System(#8)

Status indicator functionality will be added to the dockets. Colours will be used in order communicate to the player roughly how much time they have left before a customer gets angry, with "harsher" colours representing less time left. This task involves creating an `atlas`, `json` and sprite map to create a `Skin` instance, which will then be rendered by the renderer.
 
## **Example**
- **Colour Change**: The longer an order is "active" and has not been fulfilled, the colour on the bottom of the docket will change in order to indicate how close it is to expiring. Tickets will start with green, then go to orange/yellow, then to red and finally to black when the time has expired.

# **Dependencies**

- [x] Render Order Ticket Instance (#27)
 
# **Milestones**
NOTE: Order of step two and step three is not rigid
- [x] Create PNG containing all ticket status sprites (Aug. 24)
- [x] Create atlas (Aug. 25)
- [x] Register skin for rendering (Aug. 27)
- [x] Implement functionality for updating docket background after certain time (Aug 28.)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michael (@IWontCauseAFuss) (idontwanttocauseafuss)
