### ISSUE TITLE
[Team 1] Inventory System

### ISSUE THREAD

**Issue by goanna5** [UQcsse3200/2024-studio-3#6]
# **Description**
Adds a generic inventory component that can be used for a variety of entities as a way to keep track of items held/stored by that entity. Most notably, it will be used to give the player 1 inventory slot (can hold 1 item), however, the component can be initialised with any amount of slots to be used for a variety of features. Functionality for adding/removing items from inventory will be implemented. No stacking functionality will be implemented. The inventory feature is essential to gameplay, allowing players to pick up, transport, and deposit items around the map. 

## SubFeature/component 
- Main functionality will be: adding, removing, and selecting items.

## **Examples**
- Mix between Overcooked and Minecraft in that the player can only pick up a set amount of items (1 at this stage) and they can select & remove them as they wish.

# **Dependencies**
- [x] Number of items (#5): influences size of inventory.
- [x] Interaction with the cooking station (#3): selecting/removing/adding items in inventory.
- [x] Relies on player action and interaction in general (#4): functionality for picking up/placing items.

# **Milestones**
- [x] Implement base inventory structure (Aug. 20)
- [x] Implement selecting functionality (Aug. 23)
- [x] Implement adding and removing functionality (Aug. 25)
- [x] Write tests for inventory functionality (Aug. 27)
- [x] Consider UI element & write documentation (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras**
- [x] Add a larger inventory as you level up.
- [x] Show the item selected in hand.

# **Documentation**
- [Inventory System](../wiki/Inventory-System)

# **Members**
- Anna Stevens (@goanna5)
- Serene McCormack (@serenemccormack)
- Quoc Bao Huynh (@bhuynh3004)
- Sourav Roy Chowdhury (@Sourav-RC)
- Benjamin Wang (@benjamin-wang1)

**Comment by JTrenerry** [comment]
can you make your dependencies a list and use some check boxes please.
Like below please
- [ ] errrrmmmm
- [ ] hello
