### ISSUE TITLE
Currency System

### ISSUE THREAD

**Issue by aridspace10** [UQcsse3200/2024-studio-3#60]
# **Description**
**Task:** Items #5 
**Feature:** Currency System

The currency system is important for the user to see as they can know much money they will have at the end of day and how well they are doing. This will be displayed on the screen (undecided where) and will increment as more dishes are sold. 
## **Example (optional)**
![image](https://github.com/user-attachments/assets/43cdf4d2-9d17-472a-adbe-71cc86a21582)

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find/draw design for money (Aug 24)
- [x] Write methods to Increment/Decrement Cash (Aug 25)
- [x] Display to screen (Aug 26)
- [x] Write tests (Aug 27)
- [x] Write Wiki (Aug 28)
 
**Completion Deadline:** Aug.28
 
# **Documentation**
- [Documentation] https://github.com/UQcsse3200/2024-studio-3/wiki/UI
 
# **Member**
- Jackson Van Duikeren (aridspace10)
