### ISSUE TITLE
Link PlayerStatsDisplay and DayNightService Day Iteration

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#601]
# **Description**
**Task:** [Link PlayerStatsDisplay and DayNightService Day Iteration.
**Feature:** [Improving Integration of Win/Loss System into Game](#600 )

This task will focus on linking the PlayerStatsDisplay and DayNightService day iteration (as they are currently independent of each other) and resolving any issues that result. 

# **Dependencies**

- [ ] PlayerDisplayStats
- [ ] DayNightService
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Link PlayerStatsDisplay and DayNightService day iteration (Oct. 14)
- [ ] Resolve bugs that result (Oct. 15)
- [ ] Alter DayNightServiceTest.java accordingly (Oct. 15)
- [ ] Write Wiki (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Win-Loss-Logic
 
# **Member**
- Madeleine Coombs (@madeleinecoombs)
