### ISSUE TITLE
Create Dishwasher component + infrastructure for addition to maps. 

### ISSUE THREAD

**Issue by serenemccormack** [UQcsse3200/2024-studio-3#610]
# **Description**
**Task:** Create Dishwasher component + infrastructure for addition to maps. 
**Feature:** #312 

Create the Dishwasher component for allowing spawning in of plates for the player to handle, 

# **Dependencies**

N/A
 
# **Milestones**

- [x] Write DishwasherStationComponent.
- [x] Write functionality for creating an instance of Dishwasher station type.
- [x] Ensure map can spawn in this new station type. 
- [x] Write tests for the component. 
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Serene McCormack (@serenemccormack) (serene_mccormack)
