### ISSUE TITLE
Improve LoadGameDisplay UI

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#617]
# **Description**
**Task:** [Improve LoadGameDisplay UI](#3).
**Feature:** [Improve Save/Load System](#452 )

Improve the LoadGameDisplay UI to make it aesthetically more appealing, and to make it match the 'theme' of the rest of the game's UI. 

# **Dependencies**
- [x] LoadGameDisplay class code from Sprint 3
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add a thematically appropriate background (Oct. 15)
- [x] Incorporate coin icon (Oct. 16)
- [x] Improve formatting, text size and spacing (Oct. 17)
- [x] Write Wiki (Oct. 17)
- [x] Test Visually (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-3/wiki/Save-and-Load-Game

# **Member**
- Madeleine Coombs (@madeleinecoombs)
