### ISSUE TITLE
Increase test coverage for cutscene folder

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#618]
# **Description**
Increase the coverage for any low coverage files in the `components/cutscene folder` using tests.

- BackgroundRendererComponent.java: 66.7%
- BackstoryCutsceneDisplay.java: 0.0%
- Cutscene.java: 47.3%
- GoodEnd.java: 0.0%
- MoralDay1Cutscene.java: 0.0%
- MoralDay2Cutscene.java: 0.0%
- MoralDay3Cutscene.java: 0.0%
- MoralDay4Cutscene.java: 0.0%

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] BackgroundRendererComponent.java
- [x] BackstoryCutsceneDisplay.java
- [x] Cutscene.java
- [x] GoodEnd.java
- [x] MoralDay1Cutscene.java
- [x] MoralDay2Cutscene.java
- [x] MoralDay3Cutscene.java
- [x] MoralDay4Cutscene.java

**Completion Deadline:** Oct 17

# **Documentation**
- 
- ...

# **Members**
- Caleb Murphy (@Caleb-J-Murphy)
