### ISSUE TITLE
Placeholders for Docket Data

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#62]
# **Description**
**Task:** Placeholders for Docket Data (#62).
**Feature:** Order System (#8)

Will create placeholders for data that will be displayed on the dockets. `MainGameOrderTicketDisplay` class will access the placeholder data. This data will include specific recipe information that the docket needs for displaying and setting the timer. Once `MainGameOrderTicketDisplay` can recieve changing data, the placeholder will be replaced with real recipe data.
 
# **Dependencies**
- [x] (#52 ) to retreive recipe data for the dockets
 
# **Milestones**
- [x] Create placeholder data (Aug. 25)
- [x] Ensure MainGameOrderTicketDisplay can display different data (Aug. 25)
- [x] Replace placeholder data with real recipe data (Aug. 28)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Ordering-System-Overview](../wiki/Ordering-System-Overview)
- [MainGameOrderTicketDisplay](https://uqcsse3200.github.io/2024-studio-3/com/csse3200/game/components/ordersystem/MainGameOrderTicketDisplay.html)
 
# **Member**
- Aadya (abhat0) (Aadya Bhatia)
