### ISSUE TITLE
Reimplement moral screens as cutscene (Oct 10)

### ISSUE THREAD

**Issue by ambs02** [UQcsse3200/2024-studio-3#627]
# **Description**

**Task:** **Reimplement moral screens as cutscene**
**Feature:** MORE EXTENDED moral system #462

Reimplement moral screens as cutscenes instead of UIComponents. 

# **Milestones**

List of steps that need to be completed for this task.

- [x]  Implement scenes as cutscenes
- [x]  Implement dialogue for each day
- [x]  Draw yes and no buttons
- [x]  Implement yes and no buttons and dialogue

**Completion Deadline:** Oct 17

# **Documentation**
- [Moral Decision Display](https://github.com/UQcsse3200/2024-studio-3/wiki/Moral-Decision-Display)

# **Member**

Amber Chen (@ambs02)
