### ISSUE TITLE
Door and walls of the restaurant

### ISSUE THREAD

**Issue by Rakshit31773** [UQcsse3200/2024-studio-3#64]
# **Description**
**Task:** [Structure](#3).
**Feature:** [Border of the restaurant](#2)

Creates a black border across the map along with adding entry and exit doors. Also adding the top and bottom walls.
 
# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a black border
- [x] Add entry and exit doors
- [x] Add the walls
 
**Completion Deadline:** Aug. 28
 
# **Member**
- Rakshit (@Rakshit31773)
