### ISSUE TITLE
Code Smells: components/cutscenes

### ISSUE THREAD

**Issue by Caleb-J-Murphy** [UQcsse3200/2024-studio-3#652]
# **Description**
**Task:** [Code Smell: components/cutscenes](#652).
**Feature:** [Code Smells](#455)
Fix all **22** code smells located in the main game folder, specifically the `/game/components/cutscenes/` folder.
Fix all **49** code smells located in the test game folder, specifically the `/game/components/cutscenes/` folder.

# **Dependencies**
N/A
 
# **Milestones**
The game files that need to fixed:
- [x] BackstoryCutscene.java
- [x] Cutscene.java
- [x] CutsceneActions.java
- [x] CutsceneArea.java
- [x] CutsceneFactory.java
- [x] CutsceneScreenDisplay.java
- [x] CutsceneTextDisplay.java
- [x] Day2Cutscene.java
- [x] Day3Cutscene.java
- [x] IntroCutscene.java

The test files that need to be fixed:

- [x] AnimatedSceneTest.java
- [x] BackgroundCutsceneTest.java
- [x] BackstoryCutsceneDisplayTest.java
- [x] BackstoryCutsceneTest.java
- [x] BadEndCutsceneTest.java
- [x] CutsceneScreenDisplayTest.java
- [x] CutsceneTest.java
- [x] Day2CutsceneTest.java
- [x] Day3CutsceneTest.java
- [x] Day4CutsceneTest.java
- [x] GoodEndCutsceneTest.java
- [x] GoodEndTest.java
- [x] IntroCutsceneTest.java
- [x] LoseEndTest.java
- [x] MoralDay1CutsceneTest.java
- [x] MoralDay2CutsceneTest.java
- [x] MoralDay3CutsceneTest.java
- [x] MoralDay4CutsceneTest.java

 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- ...
 
# **Member**
- Caleb Murphy (@Caleb-J-Murphy)
