### ISSUE TITLE
Adding additional scoring parameters to Scoring System

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#655]
# **Description**
**Task:** Adding additional scoring parameters to Scoring System (#655).
**Feature:** Score System Implementation (#413)

The task is to extend upon the scoring system by introducing more than one variable that affects the customer's rating towards the meal that they have been served. Prior to this extension, the score is only based on the accuracy of the player's meal when compared to the customer's order. After implementing this extension, the score is now based on three evenly-weighed factors: the accuracy of the player's meal, the serving speed, and the completion status of the ingredients used in the meal (i.e. if they are cooked or chopped).
 
# **Dependencies**
 
# **Milestones**

- [x] Implement scoring logic for service speed into ScoreSystem.java (Oct. 15th)
- [x] Implement scoring logic for ingredient's completion status into ScoreSystem.java (Oct. 16th)
- [x] Call the scoring logic from StationServingComponent.java (Oct. 17th)
- [x] Update documentation on wiki (Oct. 17th)
- [x] Extension: Add customer anger logic when the customer leaves without being served any food (Oct. 17th)
 
**Completion Deadline:** Oct. 17th
 
# **Documentation**
- [Scoring System](../wiki/Scoring-System)
 
# **Member**
- Quoc Bao Huynh (@bhuynh3004)
