### ISSUE TITLE
Testing the HoverBox Component

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#656]
# **Description**
**Task:** Writing unit tests for the HoverBox Component (#656).
**Feature:** Score System Implementation (#413)

The aim of this task ticket is to create unit tests to test the functionality of the HoverBox Component in HoverBoxComponent.java.

# **Dependencies**

- [x] Generating Customer Rating Score (#164)
 
# **Milestones**

- [x] Finalise and compile HoverBoxComponent.java (Oct. 15th)
- [x] Ideate and determine ways to write unit tests (Oct. 15th)
- [x] Implement unit tests and attempt builds (Oct. 17th)
- [x] Update testing documentation to wiki (Oct. 17th)
 
**Completion Deadline:**  Oct. 17th

 
# **Documentation**
- [Scoring System](../wiki/Scoring-System)
 
# **Member**
- Quoc Bao Huynh (@bhuynh3004)
