### ISSUE TITLE
Create simple InventoryDisplay component

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#66]
# **Description**
**Task:** Create simple InventoryDisplay component 
**Feature:** [Team 1] Inventory System (#6)

Implement a basic InventoryDisplay component used to display the slots and items held in an inventoryComponent to the user. The inventory will be displayed as either text to show the current item selected, or as a box.

# **Dependencies**

- [x] Item component needs to be implemented to properly display items in the inventory (#5)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Extend UIComponent class (Aug. 26)
- [x] Create basic text display (Aug. 26)
- [x] Add inventory display to UI (Aug. 26)
- [ ] Possibly extend to a box display (Aug. 27)

**Completion Deadline:** Aug. 27

# **Documentation**
- [Inventory Display Component](../wiki/Inventory-System)
 
# **Member**
- Benjamin (@benjamin-wang1)
