### ISSUE TITLE
Update Customer Reaction Splash Art

### ISSUE THREAD

**Issue by bhuynh3004** [UQcsse3200/2024-studio-3#666]
# **Description**
**Task:** Updating Customer Reaction Splash Art (#666).
**Feature:** Score System Implementation (#413)

The goal of this task ticket is to create and update the customer reaction splash art, which will be displayed above the heads of the customers once the player serves them their meals. The previous splash art was both unprofessional and unoriginal, and also inconsistent with the design choices of Beastly Bistro. Therefore, new versions of the splash art was made to provide a more consistent user interface while maintaining a high level of professionalism.

# **Dependencies**
 
# **Milestones**

- [x] Research the currently available design aesthetics and choose a starting base (Oct. 15th)
- [x] Create the splash art for each customer reaction (Oct. 16th)
- [x] Remove the old splash art files from the assets folder of the game (Oct. 17th)
- [x] Add the new splash art files into the assets folder of the game (Oct. 17th)
 
**Completion Deadline:** Oct. 17th
 
# **Documentation**
- [Scoring System](../wiki/Scoring-System)
 
# **Member**
- Quoc Bao Huynh (@bhuynh3004)
