### ISSUE TITLE
Add selection functionality to the inventory component

### ISSUE THREAD

**Issue by benjamin-wang1** [UQcsse3200/2024-studio-3#69]
# **Description**
**Task:** Add selection methods to the inventory component.
**Feature:** [Team 1] Inventory System (#6)

Add selection functionality to the inventory component, allowing it to keep track of a currently selected item. Will add methods to select an item and retrieve the currently selected item.

# **Dependencies**

- [x] Inventory component is created (#33)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add required fields (Aug. 26)
- [x] Add required methods (Aug. 26)

**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Inventory System](../wiki/Inventory-System)
 
# **Member**
- Benjamin (@benjamin-wang1)
