### ISSUE TITLE
Bench Collisions and Map Design

### ISSUE THREAD

**Issue by ATOApplett** [UQcsse3200/2024-studio-3#70]
# **Description**
**Task:** Bench Collisions and Map Design (#70)

Implement collisions with the benches such that the player can't walk out of the working area. Additionally, implementing some more functions to handle different types of objects, (i.e. tables, chairs). Implementing different kinds of objects to spice up the map and the collision handling of those objects. 
 
## **Example (optional)**
- **Correct collisions with benches**: Implementing this so the player can't walk out of the "working space"
- **Decoration**:  A glass display area instead of just an enclosed area with benches.

# **Dependencies**
Map design and layout (#2)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create hitboxes and collisions for the benches (Aug. 25)
- [ ] Add more functions to handle different types of benches/objects (i.e. chairs) (Aug. 26)
- [ ] Edited Basic UI (Name of the game, list of orders) (Aug. 26)
- [ ] Add more benches to conceal the "working area" (Aug 27)
 
**Completion Deadline:** Aug. 27

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Alex (@ATOApplett)
