### ISSUE TITLE
Order System

### ISSUE THREAD

**Issue by abhat0** [UQcsse3200/2024-studio-3#8]
# **Description**
The feature involves the human taking the order of the animal. As the player listens to the animal’s order, each item is dynamically displayed on the order ticket. Once the animal has finished ordering, the ticket is automatically pinned to the top of the screen. The player is able to minimize and maximize the receipt/order ticket to view it in closer detail without interrupting the game flow. Different colors of the order ticket represent the status of the order ie. green for completed order, yellow for orders that are in progress and red for when you’re running out of time. 

## SubFeature/component (optional)

Upon customer order, generates a ticket/receipt. 
Appears: top of game screen
Current order list
History of completed orders 
Real-time updates; color representing order status
Have recipe items appear on ticket
Have customer timings on ticket

Implement an order system that takes orders from customers and displays order receipts similar to the Papa’s games. 

## **Examples (optional)**

# **Dependencies**

- [ ] Items/Recipes - Team 2 (#9)
- [ ] Customers - Team 8 (#7)

# **Milestones**

- [x] Rendering single order (Aug. 22)

- [x] Rendering multiple orders (Aug. 22)

- [ ] Moving an order (Aug. 23) 

- [ ] Pinning single order to top of screen (Aug. 23)

- [x] Pinning multiple orders (Aug. 24) 

- [ ] Test implementation (Aug. 27)

- [ ] Finalise documentation (Aug. 28)

**Completion Deadline:** Aug. 29

# **Extras (optional)**
- [ ] Order Screen to Map Screen Switch Mechanism (blank windows for order and map?)
- [ ] Currency system
- [x] Change order status. Assign colours to different order statuses (Aug. 26)
- [ ] Implement basic ticket UI (expanding on ticket when clicked on) (Aug. 22)

- [ ] Backend (storing the recipe info, which customer it is for, etc...) (Aug. 20)

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Aadya (@abhat0) (Aadya Bhatia)
- Shravya (@shravya132) (Shravya Chandrasekar)
- Airyl (@airylsuaidi) (Airyl Harridzuan Bin Suaidi)
- Michael (@IWontCauseAFuss) (Michael Kidd)
- Lakshay (@LAKSHAYATREJA)(Lakshay Atreja)
- Tia (@tia-w) (Tia Waturuocha)

**Comment by JTrenerry** [comment]
Hey guys, this seems like a lot of work so far, let's try to make it a bit smaller and have some of the things you are planning to do in the Extras section :)
