### ISSUE TITLE
Bench and Wall Collision Mechanics

### ISSUE THREAD

**Issue by amacn13** [UQcsse3200/2024-studio-3#85]
# **Description**
**Task:** Bench and Wall Collision
**Feature:** [Map Design / Colour Palette](#2)

Update the creation of the benches and restaurant walls to include collision mechanics as seen in the original game engine example
 
## **Example**
- When coming into contact with a wall or bench object, the player's movement should cease until the player has moved around it

# **Dependencies**
- [x] All assets need to be created (#53)
- [x] Benches need to be spawned (#75)
- [x] Walls need to be spawned (#64)
- [x] Player spawning functionality needs to be initialised (for testing) (#83)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Add collision physics to all bench objects
- [x] Add collision physics to all wall objects
 
**Completion Deadline:** Aug. 27

# **Documentation**
- [Map Design](../wiki/Map-Design)
 
# **Member**
- Alex Macnamara (@amacn13)
