### ISSUE TITLE
Fix alignment/scaling of benches

### ISSUE THREAD

**Issue by pineapple11111** [UQcsse3200/2024-studio-3#87]
# **Description**
**Task:** Fix alignment of benches (#3).
**Feature:** implement/design benches (#2)

Due to some issues with how entities are scaled, every single bench was being scaled differently (2 benches with the same width would scale completely differently with matching input for their generation if they had different heights). Due to this, aligning the benches correctly was not possible, so some placeholders were used temporarily. Additionally, collisions were also not functioning correctly because of this issue.
The Bench class and createBench function need to be reworked to correct this. 

# **Dependencies**
- [x] (#53)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] clean up code for spawnBenches in ForestGameArea
- [x] change bench scaling method so that all are scaled equivalently 
- [x] place benches in the map 
- [x] align benches with one another 
 
**Completion Deadline:** Aug. 27

# **Member**
- Reza Panday (pineapple11111)

**Comment by pineapple11111** [comment]
fixed
