### ISSUE TITLE
Food Recipes

### ISSUE THREAD

**Issue by willembor** [UQcsse3200/2024-studio-3#9]
# **Description**
Food recipes are a combination of different ingredients like potatos, bread, vegetables etc to combine for a product to give to the animals. There will be 5 recipes with a combination of very simple recipes to a few slightly complex ones. The player will be able to collect these ingredients and interact with other features such as the oven, stove, deep fryer to create the food item. These different recipes and varying complexity add a layer of depth to the game which can make it more difficult every day the game is played.

<u>**Task Tickets:**</u>
- #35, #52 : The information relating to recipe and food/ingredient item cooking times will be stored in json and processed via a Config class. Currently we are planning to store recipe information in a Dish entity, and passing the information to a Dish component.
- #36: The logic to handle the recipe, item combinations and transitions to a dish/meal is handled as part of the station.
- #37 : When an event notifies that an ingredient is placed on a station, and that the station is turned on, the ingredient will get cooked. The item state is updated to cooked, overcooked, or burnt.

## SubFeature/component (optional)
- Cooking the ingredient
- Preparing the ingredient
- Variable cooking time (can burn or undercook ingredients)
- Cooking time can be dynamic (faster for example, if the station had just been used)
- Different animals prefer different food items based on cooking time

## **Examples (Food Recipes)**
- Beef Sandwich
- Chicken Sandwich

## Reliant Features
- #5 
- #3
- #7 
- #6 
- #4

# **Milestones**
- [x] Create recipes - 20 Aug
- [x] Decide ingredients (need to talk to item group and customer types group) - 23 Aug
- [x] Implement cooking functionality - 29 Aug
- [x] Testing Code - 29 Aug
- [x] Documentation - 29 Aug
- [x] Sprint Achievement Form - 29 Aug

**Completion Deadline:** Aug. 29

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Willem Bor @willembor 
- Alexander Shomer @Ashom2 
- Joanna Wang @Joanna-Wang105 
- Ashwin Harikrishna @AshHarikrishna 
- Calvin Shaji @CalvinJohn99 
- Daleela @daleelakhairil

**Comment by JTrenerry** [comment]
Right hand side (assignee, labels project needs to be filled out)
