### ISSUE TITLE
Docket Positioning and Indenting

### ISSUE THREAD

**Issue by IWontCauseAFuss** [UQcsse3200/2024-studio-3#94]
# **Description**
**Task:** Docket Positioning and Indenting(#58).
**Feature:** Order System(#8)

When dockets are removed from the screen, the remaining dockets need to be moved to fill in the empty space (if applicable). Additionally, they need to be placed relatively on the screen, so no matter the screen size, they are at the same location.
 

# **Dependencies**

- [x] Render Order Ticket Instance (#27)
- [x] Docket Status Indicator(#58) 
 
# **Milestones**

- [x] Fix Y coordinate positioning for dockets 
- [x] Rewrite existing code so UI is able to be tracked
- [x] Implement code so that when a docket is deleted, all dockets that need to move are moved
- [x] Ensure code from #58 is functional
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michael (@IWontCauseAFuss) (idontwanttocauseafuss)
